### ISSUE TITLE
POST : 500 Internal Server Error

### ISSUE THREAD

**Issue by huguangju** [typicode/json-server#102]
I am follow [https://egghead.io/lessons/nodejs-creating-demo-apis-with-json-server](https://egghead.io/lessons/nodejs-creating-demo-apis-with-json-server) step by step to do , when i send post request, an error occurred(from response): 
![qq20150524-1 2x](https://cloud.githubusercontent.com/assets/6972433/7787269/c5bd7660-0235-11e5-94c1-95a3783087bc.png)

TypeError: undefined is not a function<br> &nbsp; &nbsp;at Function.module.exports.insert (/usr/local/lib/node_modules/json-server/node_modules/underscore-db/src/index.js:59:18)<br> &nbsp; &nbsp;at baseWrapperValue (/usr/local/lib/node_modules/json-server/node_modules/lowdb/node_modules/lodash/index.js:2761:30)<br> &nbsp; &nbsp;at LodashWrapper.wrapperValue (/usr/local/lib/node_modules/json-server/node_modules/lowdb/node_modules/lodash/index.js:6075:14)<br> &nbsp; &nbsp;at LodashWrapper.&lt;anonymous&gt; (/usr/local/lib/node_modules/json-server/node_modules/lowdb/src/index.js:35:35)<br> &nbsp; &nbsp;at LodashWrapper.insert (/usr/local/lib/node_modules/json-server/node_modules/lowdb/node_modules/lodash/index.js:3320:35)<br> &nbsp; &nbsp;at create (/usr/local/lib/node_modules/json-server/src/router.js:164:8)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/usr/local/lib/node_modules/json-server/node_modules/express/lib/router/layer.js:82:5)<br> &nbsp; &nbsp;at next (/usr/local/lib/node_modules/json-server/node_modules/express/lib/router/route.js:110:13)<br> &nbsp; &nbsp;at next (/usr/local/lib/node_modules/json-server/node_modules/express/lib/router/route.js:104:14)<br> &nbsp; &nbsp;at Route.dispatch (/usr/local/lib/node_modules/json-server/node_modules/express/lib/router/route.js:91:3)

> GET request is OK!

**Comment by typicode** [comment]
Hey @huguangju 
I don't have WebStorm, so I can't test with it. But could you copy/paste your `db.json`?

I've tried with:

```shell
$ cat db.json 
{"people": []}
$ json-server -v
0.7.9
$ json-server db.json
# ...
$ curl --data "name=foo" http://localhost:3000/people
{
  "name": "foo",
  "id": 1
}
```

**Comment by andRyanMiller** [comment]
Experiencing the exact same error. 

`db.json` is as follows: 
```json
{
  "login": {
    "token": "123"
  }
}
```

POSTing to `http://localhost:3000/login` returns a 500 with the same error @huguangju mentioned above. A GET request to `/login` returns the object as expected.

**Comment by typicode** [comment]
@andRyanMiller Thanks for the feedback. Currently you need to have arrays in your `db.json` for routes to work.

So a work-around would be to use the project as a module and add a custom login route:

```javascript
var jsonServer = require('json-server')

var server = jsonServer.create()
var router = jsonServer.router('db.json')

server.use(jsonServer.defaults)

// For example
server.get('/login', function (req, res) {
  res.jsonp({ token: '123' })
})

server.use(router)

server.listen(3000)

**Comment by typicode** [comment]
Just as an update, there's another way now to work with single resources.

`routes.json`

```json
{
  "/login": "/logins/1"
}
```

`db.json`

```json
{
  "logins": [ { "id": 1, "token": "123" } ]
}
```

`json-server db.json --r routes.json`
