### ISSUE TITLE
Non-existing url does not return 404

### ISSUE THREAD

**Issue by kilinochi** [typicode/json-server#1025]
![2019-09-21_10-43-11](https://user-images.githubusercontent.com/34065879/65370055-7a186880-dc5d-11e9-9f74-706ab32c20e6.png)
![2019-09-21_10-41-51](https://user-images.githubusercontent.com/34065879/65370056-7a186880-dc5d-11e9-98e7-1a8bd56cc5ea.png)

And how I can return 404?

**Comment by ragnarokatz** [comment]
@kilinochi

in the code, it is indeed returning a response with a status of 404. however, the returned data object does not contain enough information to show that this is indeed the case.

```
router.use((req, res) => {
    if (!res.locals.data) {
      res.status(404)
      res.locals.data = {}

    router.render(req, res)
  })
```

**Comment by ragnarokatz** [comment]
I have opened a PR here for this issue: #1041 
I have changed the returned object to:

```
router.use((req, res) => {
    if (!res.locals.data) {
      res.status(404)
      res.locals.data = {status_code: 404, error: 'Page not found'}
    }
...
```

**Comment by kilinochi** [comment]
solve my problem, tnks!
