### ISSUE TITLE
Possible to default from "id" to "_id"?

### ISSUE THREAD

**Issue by DylanPiercey** [typicode/json-server#103]
This would be handy for example mongodb/couchdb servers.

It would be nice to make this configurable.

**Comment by typicode** [comment]
Not right now.
I agree, I'll see what can be done.

**Comment by edm00se** [comment]
I would definitely geek out over having this available; emphasis on the configurability.

:grinning:

**Comment by typicode** [comment]
Just released some new features and it's possible now :)

```bash
json-server --id _id --watch db.json 
```

**Comment by edm00se** [comment]
W00t! Thank you.

**Comment by DylanPiercey** [comment]
Awesome, thanks for this.

**Comment by typicode** [comment]
You're welcome ;)

**Comment by nishantshreshth** [comment]
Thank you!

**Comment by jinpeichen** [comment]
how to config by configuration file ,my json-server.json file is blow ,but it's not work
`{
  "id":"_id",
  "port":3000
}`
can you help me? thanks

**Comment by jinpeichen** [comment]
@typicode

**Comment by ThierryDD** [comment]
@fresherchen 

I was also wondering how to do that when using json-server as a module.

I needed:
* --id _id
* --foreignKeySuffix _id

(*MongoDB style*)

Here is my JSON Server:

```js
const path = require('path');
const jsonServer = require('json-server')
const data = require('./server.json')

const app = jsonServer.create()
const port = process.env.PORT || 3000

const router = jsonServer.router(data, {foreignKeySuffix: '_id'})
router.db._.id = '_id';

console.log(path.join(__dirname, '../../dist'));

app.use(jsonServer.defaults({
    logger: process.env.NODE_ENV !== 'production',
    static: path.join(__dirname, '../../dist')
}))

app.use(router)
  
app.listen(port, () => {
  console.log('JSONPlaceholder listening on http://localhost:' + port)
})
```

This allowed me to properly use relationships and  `_expand` such as in:

```
GET http://localhost:3000/categories/3/albums
GET http://localhost:3000/albums/5?_expand=category
```

**Comment by akymtl** [comment]
Could t

> Just released some new features and it's possible now :)
> 
> ```shell
> json-server --id _id --watch db.json 
> ```

Could this be mentioned in the README.md as well at someplace, if possible.
