### ISSUE TITLE
How can I delete or put or push or patch using similar SQL's where?

### ISSUE THREAD

**Issue by coconilu** [typicode/json-server#107]
I have read the total README.DOC 
and can do successfully the example.

But I have a problem ,how can I delete the post with its title instead of its id.
example:
{
  "posts": [
    {
      "id": 1,
      "title": "json-server",
      "author": "typicode"
    },
    {
      "title": "rest",
      "author": "Alpha",
      "id": 5
    },
    {
      "course": "restful",
      "teacher": "Mr.Alpha",
      "id": 6
    },
    {
      "id": 7,
      "title": "hello kit",
      "author": "alpha",
      "titles": "hello kit",
      "titless": "hello kit"
    },
    {
      "title": "hello world",
      "id": 8
    }
  ],
  "comments": [
    {
      "id": 1,
      "body": "some comment",
      "postId": 1
    }
  ]
}

Can I delete the post which title is hello world ? 
I know I can do it with DELETE /posts/8.

Thanks for the trouble.

**Comment by ryantemple** [comment]
You'd need to find the post(s) with the specific title you are looking for using the "q" parameter in the collection

GET /posts?q="hello world"

Then grab the IDs from the response for the DELETE call.  As far as I know there is no way to go straight to the title (or any other attribute).

**Comment by coconilu** [comment]
A little disappointment,but thanks for your answer.    :)
