### ISSUE TITLE
404 error on home page with the 0.16 version using npx

### ISSUE THREAD

**Issue by kuncevic** [typicode/json-server#1079]
Once switched to 0.16 version stated getting an 404 error in home page using `npx`:

`npx json-server --watch db.json` - 404 error when navigating the home page
`npx json-server@0.15.1 --watch db.json` - no error

my `db.json`
```
{
  "video": [
   {
      "id": "hiOjK992bPU",
      "title": "LINDEMANN - Steh auf (Official Video)",
      "views": "8812123",
      "likes": "219234",
      "dislikes": "4389"
    },
    {
      "id": "NeQM1c-XCDc",
      "title": "Rammstein - Deutschland (Official Video)",
      "views": "88123123",
      "likes": "22543345",
      "dislikes": "75123"
    }
  ]
}
```

**Comment by oaydinyilmaz** [comment]
same issue on windows 10 with VS Code.

I'm able to see the objects but not dashboard(home page)

![image](https://user-images.githubusercontent.com/8834587/75027457-adcb1900-54af-11ea-8b62-8d286d3a8738.png)

**Comment by typicode** [comment]
Thanks for the heads-up! It should be good now.

**Comment by JimiSweden** [comment]
I still have the problem of 404 on the home page, exactly as @oaydinyilmaz reported

```
node_modules\.bin\json-server -v
0.16.1

windows 10, 
node -v
v13.7.0
```

**Comment by myshov** [comment]
@JimiSweden There is an issue if `public` directory already exists in your project. json-server attempts to serve index.html from there https://github.com/typicode/json-server/issues/1100#issue-578574593

**Comment by hhagay** [comment]
I am afraid this issue still exists.
Please Note:
json-server is version 0.16.1

**Comment by MMG606** [comment]
The same thing happened to me, I'm my case I wasn't specifying the db route which was in a folder named database, 
for example:
json-server --watch db.json
should be 
json-server --watch database/db.json

**Comment by Mohowk** [comment]
Daaang now i have this too ! can anybody tell me how to solve it or what to do ? Please i feel so dumb
