### ISSUE TITLE
Getting a range

### ISSUE THREAD

**Issue by ObjectiveTruth** [typicode/json-server#108]
Is it possible to filter based on a range?

for example if I have items with a price field

```JSON
id: 0,
price : 10
```

do something like get all items with price between 10 and 20? and paginate?

P.S. Great library!

**Comment by fzaninotto** [comment]
+1, I'd love to be able to filter like that:

```
GET /products?price={gte:10,lte:20}
```

or maybe

```
GET /products?price__gte=10&price__lte=20
```

gt, lt, gte, lte are widely used (MongoDB, ElasticSearch, Django...)

**Comment by typicode** [comment]
Just added the feature in `v0.7.28`. Thank you for the feedback and suggestions :)

**Comment by fzaninotto** [comment]
Awesome, you rock!
