### ISSUE TITLE
_embed the other way around

### ISSUE THREAD

**Issue by goffreder** [typicode/json-server#110]
Is it possible to use `_embed` the other way around? Like in the README example, get `post` info from a  `comment`.

Something like `GET /comments/1?_embed=posts` which should return

    "comments": [
        {
            "id": 1,
            "body": "some comment",
            "postId": 1,
            "post" : { "id": 1, "title": "json-server", "author": "typicode" }
        }
    ]

**Comment by yalkanani** [comment]
alkanani
بتاريخ ٠٣‏/٠٦‏/٢٠١٥ ٦:٢٧ م، جاء من "Emanuele Biancardi" <
notifications@github.com>:

**Comment by typicode** [comment]
Not right now. But if you need it, it can be added.

**Comment by goffreder** [comment]
Well, I think it could be useful, it could prevent from doing multiple calls to "expand" an object. Maybe there could also be a "depth" parameter which says how many levels of expansion we want.

**Comment by adamsea** [comment]
+1 for this feature.  It might even make sense to have an expand parameter that could indicate when relationships should be expanded, e.g.

`GET /comments/1?_expand=posts,authors`

**Comment by adamsea** [comment]
@typicode I submitted #130 to add an `_expand` parameter to json-server.  What do you think of this approach?  It will still take multiple query string parameters like `_embed` does.

Thanks!

**Comment by typicode** [comment]
@adamsea sorry for the delay.

Actually, I think `_expand` is coherent with the way `_embed` work and the code is good. So kudos for that and thanks :)

However, I'm wondering if the feature responds to a common case or is it just a "nice to have" but not really needed. More user feedback would help.

Embedding children like in `/posts/1?_embed=comments` seems to me quite common case and allowed to resolve some issues. The other way, I don't know.

I'd like to avoid making the project bloated or too complicated.

Is the PR responding to an issue you have with JSON Server?

**Comment by eshaham** [comment]
+1 for this feature.
I prefer not to make to different calls just to get a referenced resource.

**Comment by typicode** [comment]
Thank you for you patience, just merged @adamsea's PR :)
`_expand` is now available in `v0.7.24`.

One slight difference, the value need to be singular (i.e. `/comments/1?_expand=post`).
