### ISSUE TITLE
How to debug console.log in json-server middleware ?

### ISSUE THREAD

**Issue by abbish** [typicode/json-server#111]
Hi, 
i want to rewrite something use middleware, 
may i know how to console log debug message at here ?

`````
// Use rewrite middlewares if you don't want to have HTTP redirections
server.use('/custom/route/:id', function (req, res) {
  console.log(req); // <---- how to debug ?
  res.redirect('/posts/' + req.params.id)
})
``````

**Comment by typicode** [comment]
Hi @abbish,

If you go to `/custom/route/1` you should get `console.log` output and be redirected to `/posts/1`.
Was that your question?

**Comment by abbish** [comment]
@typicode Yes, i want to know where can i get ```console.log``` ?

**Comment by typicode** [comment]
You need to start the server in your terminal and make a request to `/custom/route/1`, you'll see `console.log` output in the logs:

```bash
~$ node server.js
GET /posts/1 304 28.533 ms - -
# console.log content:
{ _readableState: 
   { objectMode: false,
     highWaterMark: 16384,
     buffer: [],
     length: 0,
# ...
```

**Comment by abbish** [comment]
Oh i see, 
I start json-server by script in gulp task, maybe gulp catched the console.log

**Comment by typicode** [comment]
Ok makes everything clear now ^_^

**Comment by abbish** [comment]
@typicode Thank u
