### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by gagansingh198661** [typicode/json-server#1125]
my db.json looks like this but i am constantly getting internal server error :

[
   {
      "id":1,
      "title":"to learn angular",
      "completed":false
   },
   {
      "id":2,
      "title":"to learn french",
      "completed":true
   },
   {
      "id":3,
      "title":"to learn some",
      "completed":false
   }
]

**Comment by Brossco85** [comment]
Hi @gagansingh198661 

your json needs to be structured slightly differently, something similar to the below should work

```
{
  "topics": [
    {
      "id": 1,
      "title": "to learn angular",
      "completed": false
    },
    {
      "id": 2,
      "title": "to learn french",
      "completed": true
    },
    {
      "id": 3,
      "title": "to learn some",
      "completed": false
    }
  ]
}
```

**Comment by gagansingh198661** [comment]
yup , working now , could you maybe explain it ?
