### ISSUE TITLE
Can we delay responses?

### ISSUE THREAD

**Issue by vijayrawatsan** [typicode/json-server#113]

**Comment by typicode** [comment]
On Chrome, if you open devtools and go into "mobile" mode, you can select a network profile (3G, EDGE, ...).

Not sure, but on Firefox, you should be able to do that too.

**Comment by typicode** [comment]
Also, there's [express-delay](https://github.com/boo1ean/express-delay) a middleware that can delay responses and be used with the project.

**Comment by vijayrawatsan** [comment]
No like that. I am using your server to mock some API I just want some network delay in client code. I could have used mitmproxy, or sleep my thread or write my own server. But it would be nice to have a feature where in we can paas minimum delay param or header value in the API.

Thanks for the wonderful library.

**Comment by wguldin** [comment]
I had to wrap my AJAX calls in a short 100ms setTimeout because of this issue too. They were loading data before my views were fully ready. It's not hard to do, but it was tough to figure out why my views were only rendering half of the time. 

A default, short delay could prevent the problem for others. A great tool overall though!!

**Comment by typicode** [comment]
@vijayrawatsan @wguldin thanks for the nice words :) and sorry for the late update.

After giving more thoughts, just added a `--delay` option to the CLI. Especially, since only Chrome offers network throttle right now, I hope the option will make things easier.

**Comment by asoneji** [comment]
can we delay  w request and not other? I want to mock delay to some request and not to all. How can I do that?

**Comment by Mantisimo** [comment]
Incase anyone is using the modular approach. 

```
const pause = require('connect-pause');

server.use(pause(7000));
```
