### ISSUE TITLE
son-server GET 404 error

### ISSUE THREAD

**Issue by tliut** [typicode/json-server#1135]
Hi, 
I'm new to json-server and installed and have it up and running on port 3004. Have a sampleData.json file and am getting a 404 error when issuing a CURL localhost:3004/writers command on terminal. Can someone please help...

{
    "writers": [
      {
      {
        "id": "osho",
        "name": "Rajneesh (Osho)",
        "born": "December 11, 1931",
        "deceased": "January 19, 1990",
        "description": "Indian spiritual guru, considered as a Godman and leader of the Rajneesh movement.
        "image": "http://www.sannyas.wiki/images/5/5f/Osho_HD_083.jpg"
      }
    ]
  }

ERROR on the server console

GET /writers 404 1.850 ms - 2

**Comment by AhmedHlaimi** [comment]
can you please giv us more details about ur problem

**Comment by tliut** [comment]
I've fixed the problem...the source file was not in the correct directory as such the json-server was unable to load it. Once I moved the source json file...worked like a charm. Thank you...this is such an awesome developer productivity tool to keep front-end going without heavy lifting reliance on the backend. BIG THUMBS UP!!!
