### ISSUE TITLE
Get distinct keys

### ISSUE THREAD

**Issue by fayazara** [typicode/json-server#1139]
Is it possible to get distinct keys from the database?

For example I have 
```
{
    "users": [
        {
            "name": "ABC",
            "job": "Engineer",
            "age" : 28
        },
        {
            "name": "XYZ",
            "job": "Product Manager",
            "age" : 32
        },
        {
            "name": "ASD",
            "job": "HR Manager",
            "age" : 325
        }
    ]
}
```
I want to get a array of jobs
```
["Engineer", "Product Manager", "Human Resource"]
```

**Comment by EternalWinter** [comment]
users.map(i => i.job).filter((e, i, self) => self.indexOf(e) === i)
i hope it will helpful for u

**Comment by fayazara** [comment]
You still have to do this once you get all the data, would be nice if we could get distinct values. I dropped using this module, thanks anyways.
