### ISSUE TITLE
json-server and ie caching

### ISSUE THREAD

**Issue by Semigradsky** [typicode/json-server#114]
Hi!

I usually add `Date.now()` to query for preventing caching ajax request in IE.
But this not working for `json-server`. [Example](http://jsonplaceholder.typicode.com/posts?1434015555155). `json-server` returns empty answer.

What is the best way to do this with `json-server`?

**Comment by typicode** [comment]
Hi @Semigradsky!

I've added no cache headers based on this https://support.microsoft.com/en-us/kb/234067 in `v0.7.14`.
Could you tell me if that solves the problem?

**Comment by Semigradsky** [comment]
Great! That should helped. :+1:
