### ISSUE TITLE
json-server requires at least version 10 of Node, please upgrade 

### ISSUE THREAD

**Issue by osman144** [typicode/json-server#1145]
``json-server requires at least version 10 of Node, please upgrade``
``error Command failed with exit code 1.`` 

```
node -v
v8.17.0

npm --v
6.13.4
```

```
 "scripts" : {
              ....
              ....
              "serve": "json-server --watch ./mocks/api.json"
   }

```

**Comment by aikrez** [comment]
The message says that you need at least NodeJS v10 and you have NodeJS v8.17.0 so you need to upgrade your version of NodeJS
