### ISSUE TITLE
POST request won't save parameters

### ISSUE THREAD

**Issue by Flashrob** [typicode/json-server#1149]
Hi!

```
let addReq = new XMLHttpRequest;
addReq.open("POST", "http://localhost:3000/cards?title="+title+"&column_id="+column_id, true);
addReq.setRequestHeader("Content-Type", "application/json");
addReq.send();
```

Above code runs, but will only save the id of the next item.
I also tried sending a json in .send();
Also tried sending the parameters in .send();
Multiple tutorials on the internet advise on these methods.

Could you please help me solve this issue?

**Comment by VPRAK-prog** [comment]
Same !

**Comment by abhishekdhapare9392** [comment]
Same issue occurred. But one observation its working fine with postman but not with fetch(as per my code). Is there any header or permission to add please let me know. Because its very strange behavior.

**Comment by rkulinski** [comment]
What happened here?
