### ISSUE TITLE
command not found 

### ISSUE THREAD

**Issue by Flavio10-debug** [typicode/json-server#1150]
command not found not found on mac, by typing the command at the terminal:
json-server --watch db.json

does anyone know what may be happening?

**Comment by CONCMLMCGCG** [comment]
Did you install it globally?

**Comment by Flavio10-debug** [comment]
Yes, I had it installed Globally, I had a user permission problem in one of the installation steps so this error occurred, I decided by adding the command "sudo".

anyway thanks for responding!
