### ISSUE TITLE
full text search on specific fields

### ISSUE THREAD

**Issue by masciugo** [typicode/json-server#1157]
I would like to use fulltext search but limited to one ore more properties:

```
GET /post?q=bar&qFields=title,author
// something like SELECT * FROM post WHERE (title LIKE '%ba%r') OR (author LIKE '%bar%')
```
makes sense?

thank you

**Comment by gsouf** [comment]
see #558

**Comment by gsouf** [comment]
@masciugo the problem is that the repo seems to be abandoned by its maintainer because this is a quite old PR

**Comment by masciugo** [comment]
@gsouf do you know any good alternative or mantained fork?

**Comment by gsouf** [comment]
@masciugo nothing that I know that would be as easy as json-server to setup and that would store json files. I'm myself using json-server and I just accepts its limitation as it's nothing I use in production.

If you're looking for a rest api that stores the data on the file system then I believe that this loopback framework has a connector for this: https://loopback.io/doc/en/lb3/Storage-connector.html however it's definitely more setup than json-server.

**Comment by idembele70** [comment]
to search by title for example : YOUR_URL/post?title_like=YOUR_SEARCH_TEXT
that should filter in your json server db by title so it YOUR_FIELD_NAME followed by _like
this article explain a lot of feature of json_server : https://blog.eleven-labs.com/en/json-server/
I don't know why they cannot  put this all on their documentation ...
hope it help people and let me know if it
