### ISSUE TITLE
Does deep querying not work?

### ISSUE THREAD

**Issue by rr1000** [typicode/json-server#116]
I have some JSON here - http://breakfast-pizza.herokuapp.com/patients (disclaimer: this is fake data)

```json
[
  {
    "resourceType": "Patient",
    "id": "a2a05493-1a87-475e-9686-176ac2ccab7c",
    "identifier": [
      {
        "use": "official",
        "label": "SSN",
        "value": "00000000",
        "system": "urn:oid:1.2.36.146.595.217.0.1",
        "period": {
          "start": "1986-10-31"
        },
        "assigner": {
          "display": "Adipisicing Healthcare"
        }
      }
    ],
    "name": [
      {
        "use": "usual",
        "family": [
          "White"
        ],
        "given": [
          "Larry",
          "Ronald"
        ]
      }
    ],
...
```

However when querying for a name I expected to receive the full object with the following request: http://breakfast-pizza.herokuapp.com/patients?name=White

That doesn't seem to work. Further more I'd expect something like this to work as well `http://breakfast-pizza.herokuapp.com/patients?name=Smith&gender=F` , is this too optimistic?

**Comment by typicode** [comment]
It doesn't work right now.

But `http://breakfast-pizza.herokuapp.com/patients?name=Smith&gender=F` should work with first-level properties (i.e. `"name": "Smith"` instead of an array).

**Comment by ryancrosser** [comment]
The deep querying is specific to the ```q``` parameter. So if you did ```http://breakfast-pizza.herokuapp.com/patients?q=white```, then it would return the record you indicated. The potential problem with this approach is you would get all records that have a value containing ```white```, so ```color: 'white'``` or the string ```'The White House'```, etc.

@typicode Would this functionality be worth implementing? I considered doing it when I set up deep querying, but decided to wait for the request?

**Comment by typicode** [comment]
I've just updated the project to make use of lodash new ability to use paths for filters, as suggested by @ryancrosser.

@rr1000 now you can make requests like /patients?identifier[0].label=SSN

But I'd rather not go to far or ahead of what lodash offers to keep code simple.

**Comment by rr1000** [comment]
@typicode @ryancrosser Sorry, guys. I wasn't getting notifications for this thread. Really appreciate the suggestions and improvements. This definitely helps a lot.

**Comment by typicode** [comment]
No worries, thanks for the update.
Glad it helps :)
