### ISSUE TITLE
put fails

### ISSUE THREAD

**Issue by yyy898** [typicode/json-server#1162]
when i run this code with axios.post, no problem but for some reason axios.put gets an 404 error, anybody any clue on how i can solve this ??

`var dmxlib = require('dmxnet');`
`const express = require('express');`
`var bodyParser = require('body-parser')`
`const jsonServer = require('json-server');`
`const axios = require('axios');`
`const app = express();`
`app.use(bodyParser.urlencoded({ extended: false }));`
`app.use(jsonServer.router('db.json'));`
`app.listen(8080);`
`axios.put('http://localhost:8080/Outputs', {id: 5, universe: "test2"}).then(resp => {`
`}).catch(error => {`
`console.log(error);`
`});`

**Comment by DuyLuongPhung** [comment]
Update endpoint as:

PUT /Outputs/:id 

=> your call should be: 
```
axios.put('http://localhost:8080/Outputs/5', {id: 5, universe: "test2"}).then(resp => {
}).catch(error => {
console.log(error);
});
```

**Comment by yyy898** [comment]
thanks, that solved it
