### ISSUE TITLE
request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

### ISSUE THREAD

**Issue by mattfrancis888** [typicode/json-server#1164]
npm i json-server no longer works now that request is deprecated. Any workarounds?
![image](https://user-images.githubusercontent.com/22691408/90575289-1823f400-e189-11ea-9db7-dae496c43269.png)

**Comment by mattfrancis888** [comment]
I don't think you could ignore the warning? It won't let me install JSON server because of the warning.

**Comment by wll8** [comment]
I can install normally.
- os win10x64
- node v11.0.0
- npm v6.4.1

**Comment by mattfrancis888** [comment]
Thank you wll8! I tried it again, it works now!
