### ISSUE TITLE
Can I run multiple json files?

### ISSUE THREAD

**Issue by JitterDev** [typicode/json-server#1190]
Hi, I was wondering if there was a way where I could run multiple json files at once.

If this matters:

I'm on an Ubuntu 20.04.1 LTS server.

EDIT: If possible I would like these under the same port/ip! If this isn't possible, I would appreciate if you could link me to a npm app that can do that while still being similar to this.

**Comment by calinafox** [comment]
@JitterDev have you found a solution on this?

**Comment by JitterDev** [comment]
I don't remember to be honest. I think I found a solution, but I don't remember.
