### ISSUE TITLE
Possible to run with namespaces?

### ISSUE THREAD

**Issue by brandonparsons** [typicode/json-server#12]
Given the following JSON:

```
{

  "speakers": [
    {
      "id": 1,
      "name": "Bugs Bunny"
    },
    {
      "id": 2,
      "name": "Wile E. Coyote"
    },
    {
      "id": 3,
      "name": "Yosemite Sam"
    }
  ]

}
```

Is it possible to run `json-server` such that it responds to `/api/v1/speakers` rather than `/speakers`?

**Comment by palerdot** [comment]
It seems there is an option to run based on this documentation - https://github.com/typicode/json-server#add-custom-routes
