### ISSUE TITLE
json-server CLI does not add middleware to the server

### ISSUE THREAD

**Issue by tsjohns9** [typicode/json-server#1202]
Using v 0.16.3 the documentation says you can add middleware from the CLI with the `-- middlewares` flag. The CLI allows you to pass the flag and the file, but does not hook the middleware up to anything. This can be confirmed by running the example provided in the documentation found here https://github.com/typicode/json-server#add-middlewares

As the documentation states, I should be able to create a middleware file like so
```
// hello.js
module.exports = (req, res, next) => {
  res.header('X-Hello', 'World')
  next()
}
```
and upload it to the server
```
json-server db.json --middlewares ./hello.js
```

Upon making a request to the server you will see that there is no 'X-Hello' header added.

A similar issue has been created for this [here](https://github.com/typicode/json-server/issues/996), but the solution was to not use the CLI and instead use the json-server module. That is fine for those who want to take that approach, but in this case the CLI is what I need to use, and since the documentation states that it can be done and provides an example there should be a real solution for using it from the CLI. 

The example from the docs should add a header to the response. When curling one of the default endpoints provided by the json-server, this is what is found in the response headers
```
~ » curl -I http://localhost:3000/posts
HTTP/1.1 200 OK
X-Powered-By: Express
Vary: Origin, Accept-Encoding
Access-Control-Allow-Credentials: true
Cache-Control: no-cache
Pragma: no-cache
Expires: -1
X-Content-Type-Options: nosniff
Content-Type: application/json; charset=utf-8
Content-Length: 77
ETag: W/"4d-49G7XbVRP2NKipc5uj9Z4hcUq3Y"
Date: Thu, 03 Dec 2020 17:57:39 GMT
Connection: keep-alive
```

As you can see the 'X-Hello' header is not found.

**Comment by ezranbayantemur** [comment]
@tsjohns9 Did you find a solution?
