### ISSUE TITLE
How can you POST (append) new data to an existing record?

### ISSUE THREAD

**Issue by crevulus** [typicode/json-server#1215]
Hi all,

I want to update and append to an existing record, but don't want to replace the record. `PUT` replaces the whole thing so it's no use to me, unfortunately.

For example, I have the following object in my `db.json` that I'd like to update when I hit `/profiles/1`:

```
"profiles" :[
  "userInfo": {
        "name": "aaa aaa",
        "title": "",
        "pro": false,
        "description": "",
        "location": "",
        "email": "aaa@aaa.com",
        "telephone": "",
        "website": "",
        "profession": ""
      }, 
    ],
  "id": 1
]
```

I want to be able to update some of those empty values (`description`, `location` etc.) with new requests. 

How can I achieve that on json-server?

**Comment by shajanjp** [comment]
Did you try `PUT /profiles/1`

**Comment by crevulus** [comment]
> Did you try `PUT /profiles/1`

Yes, but `PUT` replaces the data object entirely. `PATCH` does the functionality that I wanted (adds or replaces data within existing object)

**Comment by crevulus** [comment]
For anyone that finds themselves here, you should use `PATCH` instead of `POST` or `PUT` for adding new data to an existing data object.
