### ISSUE TITLE
Fetches all data when using full text search on the "e" word.

### ISSUE THREAD

**Issue by Arsh1a** [typicode/json-server#1229]
I have a data like this:
`{
  "names": [
    { "id": 1, "title": "Jacob", "author": "typicode" },
    { "id": 2, "title": "Elon", "author": "typicode" },
    { "id": 3, "title": "Moses", "author": "typicode" },
    { "id": 4, "title": "Siri", "author": "typicode" }
  ],
  "profile": { "name": "typicode" }
}`

When I access data with full text search using the word 'e' `http://localhost:3005/names?q=e`, I get all of data instead of getting only 'Elon' and 'Moses'.

**Comment by skShekhar** [comment]
`q=` does a full text search. All the items will be returned since `e` is present in `author` ("typicode"). You can use `http://localhost:3005/names?title_like=e` for search only by `title`.
