### ISSUE TITLE
Server reporting repeated calls to unknown endpoint (/api/iot/url)

### ISSUE THREAD

**Issue by crevulus** [typicode/json-server#1230]
Json-server seems to independently be making calls to an endpoint I've never seen before, and certainly haven't coded.

In [these screenshots](https://imgur.com/a/BEzOBlo) you can see:

1) No results for 'api/iot/url' in my codebase
2) Repeated calls to that endpoint in my json-server terminal view (middle panel, calls happening about once every ten seconds, not triggered by any user interaction)
3) My network requests, where /api/iot/url is no where to be seen and doesn't show up even when the reports show up in my json-sevrer terminal
4) The two places in my code where I am calling the json-server.

How you can recreate: I'm really not sure, tbh... Json sevrer has been working fine for me for months, just seen it for the first time today.

My version: `"json-server": "^0.16.3"`

**Comment by MDnexus** [comment]
api faliur/int/msp fo reset#@json - server

**Comment by MDnexus** [comment]
api/iot /url is not no wherer done show up even wen the reports show uo in my jsoin -server termainal
the two places in my code where i am calling the jsion serever.
