### ISSUE TITLE
No data stored from POST, but create empty object with incremental ID

### ISSUE THREAD

**Issue by vasotelvi** [typicode/json-server#1247]
Where can be problem?

![1621786502154](https://user-images.githubusercontent.com/13215239/119268538-18f82380-bbfc-11eb-95f2-ca3e89844e98.png)

**Comment by ThisUsernameIsAllreadyTaken** [comment]
Hi, you are probably missing the Content-Type header. Add this to you request:
headers: {
        'Content-Type': 'application/json'
      },

**Comment by vasotelvi** [comment]
> Hi, you are probably missing the Content-Type header. Add this to you request:
> 
> ```
> headers: {
>         'Content-Type': 'application/json'
>       },
> ```

Unfortunately, request already was sent with this headers. It blurred on previous screenshot on line 6, or You can see on same screenshot marked with green bellow.
![1621858271932](https://user-images.githubusercontent.com/13215239/119346919-798e6b80-bca3-11eb-8ae9-1ec4ddd628ed.png)
![1621858374954](https://user-images.githubusercontent.com/13215239/119346924-7bf0c580-bca3-11eb-91c6-8d2cdcfb9f4c.png)

**Comment by ThisUsernameIsAllreadyTaken** [comment]
1. You are missing a 'p' in 'application', which might be the problem.
2. put Accept in '' for consistency.
3. Try JSON.stringify(event)

**Comment by vasotelvi** [comment]
> 1. You are missing a 'p' in 'application', which might be the problem.
> 2. put Accept in '' for consistency.
> 3. Try JSON.stringify(event)

Thanx so much! English is not my permanent language.

**Comment by mikyweb** [comment]
I have the same problem with application/json correct format
