### ISSUE TITLE
Is it possible to return this whole object at root URL?

### ISSUE THREAD

**Issue by Hongbo-Miao** [typicode/json-server#1256]
First thanks for this tool. It is so convenient!

I have a db.json file like

```json
{
  "posts": [
    { "id": 1, "title": "json-server", "author": "typicode" }
  ],
  "comments": [
    { "id": 1, "body": "some comment", "postId": 1 }
  ],
  "profile": { "name": "typicode" }
}
```

Currently, the root URL http://localhost:3000/ returns a static page.
Is there an option to return this whole object above at root URL?

Thanks!

**Comment by supermamon** [comment]
GET `http://localhost:3000/db`

https://github.com/typicode/json-server#database

**Comment by Hongbo-Miao** [comment]
Thanks @supermamon! I was hoping to return on the top level `/` though.
But I end up going other directions, so I guess this one can be closed now.
