### ISSUE TITLE
How to define error messages in response?

### ISSUE THREAD

**Issue by ouchxp** [typicode/json-server#126]
I would like to have error code and messages for testing error handling for my application. How could I achieve that?

![image](https://cloud.githubusercontent.com/assets/1253729/8225267/821b3e8c-15e6-11e5-8db5-dd58195b3b50.png)

**Comment by typicode** [comment]
You need to use the project as a module for this and modify the response before it's sent.

For example:

```javascript
var jsonServer = require('json-server')

var server = jsonServer.create()
var router = jsonServer.router('db.json')

router.render = function (req, res) {
  var data = res.locals.data
  if (res.statusCode >= 400) {
    data = {
      code: res.statusCode,
      message: 'Error'
    }
  }
  res.jsonp(data)
}

server.use(jsonServer.defaults)
server.use(router)

server.listen(3000)
```

**Comment by ouchxp** [comment]
It works. Thanks for the wonderful library.

**Comment by typicode** [comment]
Great :) You're welcome
