### ISSUE TITLE
Json-server v0.17.0 is not available to download from https://www.npmjs.com/package/json-server

### ISSUE THREAD

**Issue by constantinirimia** [typicode/json-server#1271]
Hi Everyone,

I am trying to use json-server v0.17.0 but it is not available to download from https://www.npmjs.com/package/json-server

Is it still marked as v0.16.3 as being the latest version available!

Can we please take a look at this?

Thank you!

**Comment by typicode** [comment]
Good catch, thanks for the heads up. It's fixed.
