### ISSUE TITLE
404 Not found on created resources

### ISSUE THREAD

**Issue by BerkeSoysal** [typicode/json-server#1279]
```
 Loading server.json
  Oops, server.json doesn't seem to exist
  Creating server.json with some default data

  Done

  Resources
  http://localhost:3333/posts
  http://localhost:3333/comments
  http://localhost:3333/profile

  Home
  http://localhost:3333
```
So default JSON is created and It should be valid.
But I get HTTP 404  error in all of those resources.
It was working fine in my first project, I don't know what's wrong :(

**Comment by GFraire** [comment]
I'm also having this problem, I would like to know how to solve it...

**Comment by GFraire** [comment]
@BerkeSoysal If you can look closely, you'll see that on the second and third line it says it couldn't find your server.json file.
