### ISSUE TITLE
How to host it in Vercel?

### ISSUE THREAD

**Issue by Jonak-Adipta-Kalita** [typicode/json-server#1306]
Hello everyone, I just want to know, how we can host it in Vercel :pray:

**Comment by Jonak-Adipta-Kalita** [comment]
> How can we host in "(random software package nobody's heard of)"? Kinda answers itself right?

What do you mean?

**Comment by whoafridi** [comment]
@Jonak-Adipta-Kalita already a version out here which providedvercel deployment, . check that out https://github.com/kitloong/json-server-vercel

**Comment by Jonak-Adipta-Kalita** [comment]
Alright buddy, I will check it out
