### ISSUE TITLE
Is there has feature that can customize query parameter name?

### ISSUE THREAD

**Issue by abbish** [typicode/json-server#131]
I want to use json-server being mock server, but the common query parameter name is different for my real api , is there has some feature to customize it ?

**Comment by typicode** [comment]
You'll have to use the module.
For example, if you want to use `begin` instead of `_start`:

```javascript
// Add this before server.use(router)
server.get('/:resource/:id', function (req, res, next) {
  if (req.params['begin']) req.params['_start'] = req.params['begin']
  next()
})
```

**Comment by abbish** [comment]
@typicode I see , thanks
