### ISSUE TITLE
I'm trying for post request but getting internal server error.

### ISSUE THREAD

**Issue by zeeshan-naseem** [typicode/json-server#1319]
TypeError: Cannot read properties of undefined (reading 'id')

![image](https://user-images.githubusercontent.com/80678082/165045636-ef11bfa4-15a8-4705-9311-bd3243ffee63.png)

**Comment by ericnewton76** [comment]
without seeing the http method and url you are using, its hard to ascertain what exactly you're doing.

**Comment by bu3alwa** [comment]
My guess is you don't have an `id` field. If you could provide better context I'm sure someone can help.

**Comment by zeeshan-naseem** [comment]
actually I've got the issue, I was using "Id" instead of "id" so it was giving this error.

**Comment by ericnewton76** [comment]
@zeeshan-naseem so you opened two issues for the same problem?  Please close both of them.
