### ISSUE TITLE
harmony support : feature request

### ISSUE THREAD

**Issue by syzer** [typicode/json-server#132]
Node can use `--harmony`
so the `generate.js` file can use es6.

**Comment by typicode** [comment]
Closing it, since Node 0.4.x comes now with a lot of es6(2015) features.

**Comment by kartamyshev** [comment]
Actually node has no support of all features even with --harmony flag.
Using es6 with node (for example in json-server) could be like this:
`babel-node node_modules/.bin/json-server --watch src/server/index.js`.
Check this out http://www.2ality.com/2015/03/babel-on-node.html
Maybe I do not completely understand the problem. But this script stops --watch mode and the terminal is not updated whenever you make changes within the server.
