### ISSUE TITLE
[feature request] --watch with generate.js

### ISSUE THREAD

**Issue by syzer** [typicode/json-server#135]
would be nice if --watch option would play nicely with 
javascript file `generate.js` to generate mocks.

watch currently only works with static `json.db` files

**Comment by typicode** [comment]
You're right about that, thanks :)
I'll add it as soon as I can.

**Comment by syzer** [comment]
do you accept pull requests?

**Comment by typicode** [comment]
Yes if you want to make a PR for this feature, I'll happily merge it.

**Comment by syzer** [comment]
https://github.com/typicode/json-server/pull/140
