### ISSUE TITLE
Filter does not work for specific endpoint

### ISSUE THREAD

**Issue by DavidWz0403** [typicode/json-server#1360]
I have an issue right now to filter to get only one entity.
If I make a get request of "https:localhost:3000/providers" my data looks like this : {
[
    {
        "pid": "00000",
        "name": "ALL",
        "type": "ALL"
    },
    {
        "pid": "82720d06-2d4d-41e7-a50e-0c1d15cd10aa9",
        "name": "SOME NAME",
        "type": "BONUS"
    },
    {
        "pid": "3eca1dcb-a072-4cbb-bd67-ea389455999d",
        "name": "Provider",
        "type": "BONUS"
    },
    {
        "pid": "ca0c285a-7529-4627-b517-e34398f8cffe",
        "name": "SHOP",
        "type": "SHOP"
    }
]

If I make a get request with a query "https:localhost:3000/providers?pid=82720d06-2d4d-41e7-a50e-0c1d15cd10aa9", it returns again all values. I have checked it also for name and type and it still returns all entities.

However every other endpoint works fine with a query and the filtering is right. 
Has anyone an idea why this happens ?

**Comment by whoafridi** [comment]
your filtering things isn't appropriate I guess that's why you can't get the data
