### ISSUE TITLE
ReferenceError: primordials is not defined

### ISSUE THREAD

**Issue by ruskyvisky** [typicode/json-server#1370]
hello everyone!

I'm using a local JSON file. I'm using this command from cmd
 npx json-server --watch src/api/movie.json --port 3002 
but it throws an exception for me 
it's my cmd screenshot
![image](https://user-images.githubusercontent.com/46764372/196919270-380f680d-0968-4bf8-aba7-eb806b6f5abc.png)
I installed only the react-router package.  I tried to delete the node-modules folder and create "npm-shrinkwrap.json" but this way doesn't work for me.
What can I do? Please help me.
Thanks for your help.

**Comment by razaahmad333** [comment]
how your json file looks like?
