### ISSUE TITLE
Can you add the content returned to a normal type, such as a number, string

### ISSUE THREAD

**Issue by xjl456852** [typicode/json-server#1389]
Not all requests need to return json data types.
Some requests return a normal type, not an array or object type. This will prompt an error.

Some error occurred Error: Type of "detail" (number)  is not supported. Use objects or arrays of objects.
The corresponding file contents are as follows:
db.json 
```text
"detail":0,
```
Look forward to adding this feature, thank you

**Comment by MadhuSaini22** [comment]
In JSON Server, the structure of the data in db.json is expected to be in collections of entities, represented as arrays or objects. When encountering standalone primitive values like "detail": 0, it's recommended to wrap them within an object or include them as properties of an object. For instance:

{
  "details": {
    "detail": 0
  }
}

This format aligns with the expected structure for JSON Server, which mimics RESTful APIs.

**Comment by xjl456852** [comment]
thank you!
