### ISSUE TITLE
Relocate the db.json within direcory

### ISSUE THREAD

**Issue by troshan** [typicode/json-server#139]
I'm having issue with uploading following into heroku host as db.json located outside of the 'json-server' directory
How and where should I modify this script to move the db.json into 'json-server' dirctory

**Comment by typicode** [comment]
Hi @troshan

You may want to check https://github.com/typicode/jsonplaceholder as a working example. It's deployed on Heroku.

But I'm not sure to understand why you can't have `db.json` in the same directory?

```
project
  /db.json
  /index.js
  /Procfile
```

```javascript
// project/index.js
var jsonServer = require('json-server')

var server = jsonServer.create()
var router = jsonServer.router('./db.json')

server.use(jsonServer.defaults)
server.use(router)

server.listen(3000)
```
