### ISSUE TITLE
can i host it on github pages?

### ISSUE THREAD

**Issue by mnsn123** [typicode/json-server#1392]
I need get request only, can i host json-server on github pages?

Or how to use `<script src="https://cdn.jsdelivr.net/npm/json-server@0.17.1/lib/server/index.min.js"></script>` on static site?

**Comment by nielsbom** [comment]
Short answer: no.

Long answer: Github pages is for static sites only, json-server uses Node (through the Express framework) which you can't run on Github.

You could run `json-server` on something like Render or Fly.io.

**Comment by devnullsans** [comment]
**Check out [My JSON Server - no installation required, use your own data](https://my-json-server.typicode.com/).**

### Note: It's in Beta

Which means things may change or break:

- URLs may change
- Service may be down
- Authentication may be added later
- etc...

***Use it at your own risk.***

**Comment by rsuardi** [comment]
👀 I think this one could be closed
