### ISSUE TITLE
Get min and max value

### ISSUE THREAD

**Issue by Alfa86** [typicode/json-server#1399]
I have an array of objects that have eg.
{.....
"hcp": 13.1
.....}. 
If i can filter objects with _gte and _lte, is there a way to get that 'min' and 'max'.
Basically, i want to get max hcp value and min hcp value from all objects.

**Comment by MutennRoshii** [comment]
You can play around with the operators as you please.
Getting the min & max values should be as simple as:
- /objects?_sort=hcp&_order=desc&_limit=1  => Max
- /objects?_sort=hcp&_order=asc&_limit=1  => Min
