### ISSUE TITLE
About HomePage

### ISSUE THREAD

**Issue by zhulinghaizhoqiaodaima** [typicode/json-server#1407]
If the static file directory is set to public, the Homepage page will search for the index.html file under public and report 404 if it does not exist. Can it also be configured to return the default index file?

**Comment by ericnewton76** [comment]
Its using express so look there.

**Comment by zhulinghaizhoqiaodaima** [comment]
OK, thanks

**Comment by rsuardi** [comment]
👀 I think this one could be closed right?
