### ISSUE TITLE
Reloading JSON

### ISSUE THREAD

**Issue by samfullstack80** [typicode/json-server#1429]
Hello,
I am using json-server and also I manipulate data by time. It means that the JSON file content changes overtime. How could I reload the JSON file without restarting json-server?

**Comment by Sam-Moradi** [comment]
Also please consider that I am not using CLI and my server is embedded as code like : 
```
jsonServer.create();
const dbRouter = jsonServer.router("./my.json");
```

**Comment by kuncevic** [comment]
you can use nodemon, see this https://github.com/typicode/json-server/issues/537#issuecomment-689531662
