### ISSUE TITLE
Error: Type of "Success" (boolean)  is not supported. Use objects or arrays of objects.

### ISSUE THREAD

**Issue by nttaivn** [typicode/json-server#1435]
How can i solve the problem? Here is the json file with some fields with boolean value
![image](https://github.com/typicode/json-server/assets/19246448/a5bf58f7-9295-40f5-b87a-e680af87cf5c)

**Comment by nttaivn** [comment]
now i see the reason why not supported
![image](https://github.com/typicode/json-server/assets/19246448/81446724-ae33-4f7a-9e26-e90f5a5b70e7)
boolean value outside the object is not permitted, inside the object is okay!

**Comment by AlexeyKhrenov** [comment]
I also faced this issue, here's a good explanation : https://stackoverflow.com/questions/46195599/type-of-id-number-in-user-json-is-not-supported-use-objects-or-arrays-of-ob
