### ISSUE TITLE
Non-RESTful routes?

### ISSUE THREAD

**Issue by moneypenny** [typicode/json-server#144]
I want a path like /oauth/token/info, like what's used with OAuth. I can't figure out how to construct a db.json to get this route, and I can't find any good examples of a db.json that's more complicated than /posts, /posts/1, etc.

**Comment by typicode** [comment]
Hi,

You can add [rewrite rules](https://github.com/typicode/json-server#add-routes) when starting json-server CLI.

For example, in `routes.json` you can have:

```json
{
  "/oauth/token/info": "/infos/1"
}
```

But it's a little limited, if you need to add your own logic, I would suggest using the project as a module:

```javascript
var jsonServer = require('json-server')

var server = jsonServer.create()
var router = jsonServer.router('db.json')

server.use(jsonServer.defaults)

// Add your routes/middlewares here.
// For example:
server.get('/oauth/token/info', function (req, res) {
  // ...
})

// REST router
server.use(router)

server.listen(3000)
```

You can also use OAuth Express middlewares to avoid writing too much code.

**Comment by moneypenny** [comment]
Thanks!
