### ISSUE TITLE
Is it possible to make a POST to a file saved on github?

### ISSUE THREAD

**Issue by PriscilaSilvaAlves** [typicode/json-server#1440]
I created a repository and put a db.json file in its root. I used a json server to host this file at https://my-json-server.typicode.com/priscilasilvaalves/jsoncaixaentrada.github.io/db . In my code, I fetch that address and try to use the POST method to save a message to that file. But I get 404 Not Found error with Referrer Policy: strict-origin-when-cross-origin. How could I do a POST to a file hosted on github? It's possible?
My function is:
```
async function handleSubmit(e){
        e.preventDefault();
        try{
            const conexao = await fetch("https://my-json-server.typicode.com/priscilasilvaalves/jsoncaixaentrada.github.io/db", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json"
                },
                body: JSON.stringify({
                    nome: nome,
                    mensagem: mensagem
                }),
            })
        }catch(error){
            console.log(error);
        }
    }
```

**Comment by gaus07** [comment]
my-json-server.typicode.com is a read only service it does not support POST, PUT, DELETE.
If you want to do it then set a Node.js Server using express and create a endpoint like ` /api/messages ` instead of the ` my-json-server ` URL...
