### ISSUE TITLE
The connection was rejected. Either the requested service isn’t running on the requested server/port, the proxy settings in vscode are misconfigured, or a firewall is blocking requests. Details: RequestError: connect ECONNREFUSED 127.0.0.1:3000

### ISSUE THREAD

**Issue by leandrodemirandamauricio** [typicode/json-server#1458]
Hi,

I am facing this issue when making request using Rest Client plugin on VS Code. When made using Postman or directly in browser, it works fine.

Anybody can help?

This issue is opened in Rest Client repo as well.

https://github.com/Huachao/vscode-restclient/issues/523#issuecomment-1757319624

![print](https://github.com/typicode/json-server/assets/80897845/b93fd128-e759-4a79-921e-e64c0e422264)

When runing json-server --watch db.json --host 127.0.0.1, it works fine.

![print2](https://github.com/typicode/json-server/assets/80897845/d690d8cc-1a14-4709-8cbf-d802f64c5267)

Thanks!

**Comment by learner-mohit** [comment]
I am getting the same issue in Thunder Client extension of VS Code. After adding "--host 127.0.0.1", it got resolved.
