### ISSUE TITLE
What Body should I POST to a string array in db.json?

### ISSUE THREAD

**Issue by BobMing** [typicode/json-server#1461]
In db.json:
```
{
  "items": [
    "A",
    "B",
    "C"
  ]
}
```
If I wanna add an element "D" into the array "items", what body should I POST to url: "http://localhost:3000/items"?
I tried "D" but get 500 Error: TypeError: Cannot read properties of undefined (reading 'id').

**Comment by typicode** [comment]
Only objects are supported.

```
{
  "items": [
    { "id": 1, "value": "A" },
    { "id": 2, "value": "B" },
  ]
}
```

Then POST `{ "value": "D" }`
