### ISSUE TITLE
POST request doesn't work

### ISSUE THREAD

**Issue by liuboLucas** [typicode/json-server#1462]
I wanna mock a POST request. In routes.json file
`{
	"/token": {
		"method": "POST",
		"response": { 
			"token":XXXX
		}
	}
}`

But when calling this API in postname like post: http://localhost:3000/token. 
it response 500
`<body>
	<pre>TypeError: (dst || src).replace is not a function<br> &nbsp; &nbsp;at D:\Work\simulater\node_modules\express-urlrewrite\index.js:45:46<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\Work\simulater\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at trim_prefix (D:\Work\simulater\node_modules\express\lib\router\index.js:328:13)<br> &nbsp; &nbsp;at D:\Work\simulater\node_modules\express\lib\router\index.js:286:9<br> &nbsp; &nbsp;at Function.process_params (D:\Work\simulater\node_modules\express\lib\router\index.js:346:12)<br> &nbsp; &nbsp;at next (D:\Work\simulater\node_modules\express\lib\router\index.js:280:10)<br> &nbsp; &nbsp;at D:\Work\simulater\node_modules\express-urlrewrite\index.js:42:16<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\Work\simulater\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at trim_prefix (D:\Work\simulater\node_modules\express\lib\router\index.js:328:13)<br> &nbsp; &nbsp;at D:\Work\simulater\node_modules\express\lib\router\index.js:286:9</pre>
</body>`

**Comment by notadevps** [comment]
Remove /  .. worked for me! 
 "token": { "method": "POST", "response": {  "token":XXXX } }
 try this

**Comment by codespearhead** [comment]
@liuboLucas Has the suggested solution worked? If so, can you close this issue?
