### ISSUE TITLE
"The term 'json-server' is not recognized as the name of a cmdlet..." even after installed

### ISSUE THREAD

**Issue by fernandodamaso** [typicode/json-server#1472]
i'm getting a message of the error below,  even tough i've installed and test it both locally and globally.

"The term 'json-server' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, see if the path is correct and try again."

in the print screen you can see in details my node -v and npm -v, i'm running on windows 11, in a powershell.

anyone know how can i fix tis? 

thanks

![Captura de tela 2024-01-07 113922](https://github.com/typicode/json-server/assets/4246135/9a84b85f-9279-4bf2-99e7-9e6789f9b483)

**Comment by fernandodamaso** [comment]
that works, thanks! Can you explain to me what the problem was? :}

**Comment by Sathish107** [comment]
Thanks for solving my issue, i have been searching how to resolve this issue in chatgpt,google,stackoverflow,youtube etc.. etc .since from morning i keep on searching and got fuc**d up.

**Comment by golamrabbiazad** [comment]
This issue happening because of the alpha version of `json-server`  installed when we run `npm i json-server`. So, I have checked that the alpha version doesn't have a `json-server` executable. That's why `json-server` is not recognized.

**Comment by typicode** [comment]
Fixed, thanks for the heads up

**Comment by MMDREZA7** [comment]
Thanks 
that fixed

**Comment by Haroun-Azoulay** [comment]
Fixed, Thanks a lot !
