### ISSUE TITLE
error 496

### ISSUE THREAD

**Issue by Lalaok** [typicode/json-server#1474]
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_PARSE_ARGS_UNKNOWN_OPTION]: Unknown option '--watch'. To specify a positional argument starting with a '-', place it at the end of the command after '--', as in '-- "--watch"
    at new NodeError (node:internal/errors:405:5)
    at checkOptionUsage (node:internal/util/parse_args/parse_args:98:11)
    at node:internal/util/parse_args/parse_args:360:9
    at Array.forEach (<anonymous>)
    at parseArgs (node:internal/util/parse_args/parse_args:357:3)
    at file:///C:/Users/Maruis/AppData/Roaming/npm/node_modules/json-server/lib/bin.js:13:33
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
  code: 'ERR_PARSE_ARGS_UNKNOWN_OPTION'
}

Node.js v18.18.0
i have this error when i run the json server like : json-server -- watch db.json or json-server db.json --watch .
i have like nothing in the database yet i only create the file , what should i do?

**Comment by typicode** [comment]
You can remove --watch. File is watched by default now.

I'll update the code to handle it more gracefully.

**Comment by typicode** [comment]
Fixed, thanks for the report :+1:

**Comment by MMDREZA7** [comment]
> Fixed, thanks for the report 👍



> You can remove --watch. File is watched by default now.
> 
> I'll update the code to handle it more gracefully.

**Comment by MMDREZA7** [comment]
Fixed
Thanks
