### ISSUE TITLE
Unknown option '--delay'

### ISSUE THREAD

**Issue by joeymoso** [typicode/json-server#1476]
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_PARSE_ARGS_UNKNOWN_OPTION]: Unknown option '--delay'. To specify a positional argument starting with a '-', place it at the end of the command after '--', as in '-- "--delay"
    at new NodeError (node:internal/errors:399:5)
    at checkOptionUsage (node:internal/util/parse_args/parse_args:100:11)
    at node:internal/util/parse_args/parse_args:365:9
    at Array.forEach (<anonymous>)
    at parseArgs (node:internal/util/parse_args/parse_args:362:3)
    at file:///Users/joeymoso/Desktop/Projects/React/11-worldwise/node_modules/json-server/lib/bin.js:13:33
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25) {
  code: 'ERR_PARSE_ARGS_UNKNOWN_OPTION'
}

Node.js v19.8.1

**Comment by textbook** [comment]
That's **not** a valid option on the `latest` tag of `json-server`, which is an alpha version. You can see what _is_ available with `json-server --help`, or install the stable version as `json-server@0`. Related: https://stackoverflow.com/q/77787616/3001761

**Comment by joeymoso** [comment]
> That's **not** a valid option on the `latest` tag of `json-server`, which is an alpha version. You can see what _is_ available with `json-server --help`, or install the stable version as `json-server@0`. Related: https://stackoverflow.com/q/77787616/3001761

Thank you!
