### ISSUE TITLE
Random id values.

### ISSUE THREAD

**Issue by InsipidLake** [typicode/json-server#1477]
```json
{
  "users": [
    {
      "id": 1,
      "name": "John Doe",
      "username": "john.doe",
      "email": "john.doe@example.com",
      "phone": "123-456-7890"
    },
    {
      "id": 2,
      "name": "Jane Doe",
      "username": "jane.doe",
      "email": "jane.doe@example.com",
      "phone": "987-654-3210"
    }
  ]
}
```
Now if i insert into the API using postman or any other way. The next id comes out randomly "de302" or "7621" or something along those lines. 
![image](https://github.com/typicode/json-server/assets/155420059/733d5b2e-7fa6-4528-a2ee-d1224206bbaf)

**Comment by textbook** [comment]
As oposed to what? That's what's _supposed_ to happen, a random (four character hex) ID gets generated on insertion:

https://github.com/typicode/json-server/blob/e3ce04a04a2777b133a8efa27c59e29121bf24a4/src/service.ts#L108-L110

**Comment by typicode** [comment]
It's normal behavior. JSON Server v1 expects IDs to be strings, and it returns random ones upon the creation of a new resource.

**Comment by kalebberry** [comment]
It use to not do that? Normally this only happens when the id is a string, but now for some reason even if the id is a number it is not incrementing, its treating it as as a string.
