### ISSUE TITLE
ERR_PARSE_ARGS_UNKOWN_OPTION: Unknown option ''--id"

### ISSUE THREAD

**Issue by kvnloughead** [typicode/json-server#1483]
Hello, I'm seeing this recently, starting just this week. It's not actually happening for me, but it is for some colleagues and students of mine. I'm using v0.17.4 with npm v10.2.3 and node v20.10.  I'll request the version info from my effected colleagues. The full error is below.

The error occurs when running `json-server --watch db.json --id _id --port 3001`. This command worked fine until this week, and still works fine for me. The issue is specifically with the `--id _id`. I've tried it like this

```
json-server --watch db.json --port 3001 -- --id _id
```

And that runs, but it fails to apply the `--id _id` option. 

TypeError [ERR_PARSE_ARGS_UNKNOWN_OPTION]: Unknown option '--id'. To specify a positional argument starting with a '-', place it at the end of the command after '--', as in '-- "--id"
    at new NodeError (node:internal/errors:399:5)
    at checkOptionUsage (node:internal/util/parse_args/parse_args💯11)
    at node:internal/util/parse_args/parse_args:365:9
    at Array.forEach (<anonymous>)
    at parseArgs (node:internal/util/parse_args/parse_args:362:3)
    at file:///usr/local/lib/node_modules/json-server/lib/bin.js:13:33
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
  code: 'ERR_PARSE_ARGS_UNKNOWN_OPTION'
}

**Comment by kvnloughead** [comment]
The issue is with v1. If we install the previous version with `npm i -g json-server@^0` it works as expected. Is v1 intended for release yet? It is marked with alpha.

**Comment by typicode** [comment]
Hello @kvnloughead,

It's intended, not all features will be ported to v1.
v0 did a lot but grew quite complex in terms of code.

As for v1 state, it's "usable but expect breaking changes". I would suggest staying on v0 if there are features that you need right now.

**Comment by kvnloughead** [comment]
Right, thank you. We'll stick with v0 for now.
