### ISSUE TITLE
Manual modification of JSON file is a problem.

### ISSUE THREAD

**Issue by githubpeti85** [typicode/json-server#1486]
How can I prevent the server from detecting it as an error if I manually enter it in the JSON file? If I write in the json data, I can no longer POST. I have to delete all the data from addresses where I didn't even post.
But I don't have to delete the first data address, it allows it to remain. I don't understand how it all works.
Thus, if something happens to the json file, we cannot replace the json file containing the backup because it will not work because it is not the same file.

**Comment by typicode** [comment]
Manually modifying the JSON file shouldn't result in a error. What would be the steps for me to reproduce the error?

**Comment by githubpeti85** [comment]
> Manually modifying the JSON file shouldn't result in a error. What would be the steps for me to reproduce the error?

There are only arrays in the json file.
{"object1":[["data1","data2","data3"], ["data11","data22","data33"], ],
 "object2":[["data1","data2","data3"],["data11","data22","data33"], ],
 "object3":[["data1","data2","data3"],["data11","data22","data33"], ]
}
If I change even one letter of the data in any array, it is not possible to send POST requests. GET request is not blocked.That means adding new data to the json file is no longer possible. And writes something like this to the console: 

POST /cust6 500 26.369 ms - 965
TypeError: Cannot read properties of undefined (reading 'id')
 Error reading A:\prog\databaselesolvd\db1.json
No data, empty input at 1:1
^
   Read error has been fixed :)
GET /customers 304 22.338 ms - -   

But you can't send POST requests even after that.

It only improves if I delete all the data and leave only the empty blocks.
object1":[ ],
 "object2":[ ],
 "object3":[]

This also happens if I modify the json file offline. And even if the modification does not include data modification. I do it in VS Code.

**Comment by githubpeti85** [comment]
In fact. I noticed that even if I restart the server, it does not allow me to POST to arrays that already contain data. You can only post in empty blocks until I stop snooping on the server. But if I restart it, it is no longer possible to post data in these blocks either.

**Comment by typicode** [comment]
Format should be an array of objects (just like the `posts` example). Array of arrays is unsupported actually (I'll document it)

```json
{"object1":[  { "id": "1", "value": [ "data1","data2","data3"] }, ... ]}
```

**Comment by githubpeti85** [comment]
I understand. But then I don't have to enter the "id": "1", ? Does the program generate it by itself?
