### ISSUE TITLE
File db.json not found

### ISSUE THREAD

**Issue by kemikal** [typicode/json-server#1494]
Hey!
In version 0.17 you could run the server-json command with a database name:
"json-server db.json" 
And it would create the database for you if it did not exist. 
Now with the alpha I am getting 

error:
File db.json not found

**Comment by typicode** [comment]
Hey,
It was too much magic. So now if db.json is not found, you just get an error.

**Comment by kemikal** [comment]
Ok, I accept that! Magic is cool though :)

**Comment by typicode** [comment]
:mage: :)

**Comment by AnilMule1008** [comment]
whats the solution??
