### ISSUE TITLE
Descending order not working

### ISSUE THREAD

**Issue by alirezaloveimi** [typicode/json-server#1499]
http://localhost:4000/posts?_sort=id,-views 
this is not sorting the post items

**Comment by typicode** [comment]
What's your db.json?

**Comment by alirezaloveimi** [comment]
{
  "posts": [
    { "id": "1", "title": "a title" },
    { "id": "2", "title": "another title" }
  ],
  "comments": [
    { "id": "1", "text": "a comment about post 1", "postId": "1" },
    { "id": "2", "text": "another comment about post 1", "postId": "1" }
  ],
  "profile": {
    "name": "typicode"
  }
}

**Comment by typicode** [comment]
I understand the confusion, there's no `view` field in each post.

**Comment by alirezaloveimi** [comment]
so how can i fix this ?

**Comment by typicode** [comment]
I've updated the README. Use the new db.json.

**Comment by alirezaloveimi** [comment]
thank you

**Comment by typicode** [comment]
You're welcome
