### ISSUE TITLE
Cannot create an endpoint as a function

### ISSUE THREAD

**Issue by goodpixels** [typicode/json-server#150]
i wrote this simple test:

```
var mockApi = function() {

    var api = {

        test: { success: true },

        users: [

            { id: 1, name: 'name1' },
            { id: 2, name: 'name2' },
            { id: 3, name: 'name3' },

        ],

        me: function() {

            var userObj = {

                name: 'John Doe',
                id: 3

            };

            return userObj;

        }

    };

    return api;

};

module.exports = mockApi;
```

but the `user` route is empty, even though it's listed by the server as available. is there a fix to this?

**Comment by typicode** [comment]
Not sure to understand.

When running your JS file, I get this:

````
json-server api.js 

  \{^_^}/ hi!

  Loading api.js
  Done

  Resources
  http://localhost:3000/test
  http://localhost:3000/users
  http://localhost:3000/me

  Home
  http://localhost:3000
```

And the `users` route is working.

If it's the `me` route, functions aren't supported. You can modify `me` like this:

```javascript
me: {
  name: 'John Doe',
   id: 3
}
```

It'll work for GET requests but singular resources aren't supported, so POST, PUT, ... won't work.

Although, you can add rewrite rules:

`routes.json`

```json
{
  "/user": "/user/1"
}
```

```
json-server mock-api.js -r routes.json
```

**Comment by goodpixels** [comment]
i'm afraid that won't work either. basically, what i'm trying to do is to have two routes, one `GET /user` and the other one `PUT /user/id`. i can't get it work. i tried re-structuring my `.json` file, also tried returning the object from a JavaScript function, finally resorted to routes - none of the approaches worked. in addition, whenever i create a new route, the original endpoints are unavailable to access. so, assuming i've created my `db.json` like this:

```
{
  "users": [
    {
      "id": 1,
      "name": "John"
    },
    {
      "id": 2,
      "name": "Jessica"
    }
  ]
}
```

and here's my `routes.json`:

```
{
	"/user": "/users/1",
	"/user/:id": "/users/:id"
}
```

only the `/user` route works. i cannot access `/user/id` and i cannot access the original endpoint `/users`.

**Comment by goodpixels** [comment]
one more thing i noticed is than when i create new routes, they will be actually *created* in the `db.json` file. i don't think it's a good behaviour, because it destroys the integrity of that file, and makes it a nightmare to maintain - you can't easily tell what is a route and what is a real entry.

**Comment by typicode** [comment]
Hi @goodpixels,

Thanks for reporting these issues. I'll fix them.
By the way, you can now (`v0.7.23`) directly use objects instead of arrays for singular resources:

```
{
  "user": {
     "name": "foo"
  },
  "users": [
    {
      "id": 1,
      "name": "John"
    },
    {
      "id": 2,
      "name": "Jessica"
    }
  ]
}
```

You'll have `/user` and `/users` routes without having to use rewrite rules.

How can I reproduce the "routes creates in `db.json`" bug?

**Comment by syzer** [comment]
I believe you looking for sth like that:

```/node_modules/.bin/json-server -w --routes=routes.json --port=3002 generate.js```
generate.js -> might do functions and also export arrays

**Comment by syzer** [comment]
also 
https://egghead.io/lessons/nodejs-creating-demo-apis-with-json-server
