### ISSUE TITLE
Pagination is not working as expected

### ISSUE THREAD

**Issue by pray3m** [typicode/json-server#1502]
Pagination is not working

Tried with below URL.

[http://localhost:8080/products?_page=2&_per_page=10](http://localhost:8080/products?_page=2&_per_page=10)

I have set _per_page as 10 
By doing this,
_page=1 is working as expected as it returns 10 data from index  1 to 1
likewise, _page=2 should have also returned 10 data but instead returns 90 data from index 11 to 100
_page=3 returns 80 data from index 21 to 100.
_page=4 returns 70 data from index 31 to 100.

Expected Outcome: Every _page=value should return 10 data as _per_page is set to 10.

Thanks
Prem

**Comment by typicode** [comment]
Are you using the latest version? There was a fix related to pagination

**Comment by pray3m** [comment]
Yeah, the issue has been fixed. Thanks

**Comment by Bandhan564** [comment]
I'm facing same issue. Can anyone suggest the way to resolve it?

**Comment by pray3m** [comment]
@Bandhan564 update to the latest version!
