### ISSUE TITLE
problem in pagination

### ISSUE THREAD

**Issue by mehrdad-kj** [typicode/json-server#1508]
"colors": [
      {
        "id": 1,
        "label": "red"
      },
      {
        "id": 2,
        "label": "blue"
      },
      {
        "id": 3,
        "label": "green"
      },
      {
        "id": 4,
        "label": "yellow"
      },
      {
        "id": 5,
        "label": "black"
      },
      {
        "id": 6,
        "label": "white"
      },
      {
        "id": 7,
        "label": "orange"
      },
      {
        "id": 8,
        "label": "purple"
      }
    ]
    this is part of my json file and when i go to this route http://localhost:4000/colors?_limit=2&_page=1 and this one http://localhost:4000/colors?_limit=2&_page=2 gets the same data.

**Comment by typicode** [comment]
Please use _per_page instead (see README)
