### ISSUE TITLE
error/bug in the json server showing INT value as a STRING

### ISSUE THREAD

**Issue by vazand** [typicode/json-server#1510]
Hi Json-server Team,
I have used the json-server@1.0.0-alpha.23 and there is a bug when accessing an INT value, 
the actual bug is 
it shows int as a string 
(I have used `npx json-server -p 3500 -w LuffyCrew.json`)
 My actual json data :
`{
    "luffyCrew": [
        {
            "id": 1,
            "title": "Luffy's Dream",
            "dateTime": "2024-01-27T12:00:00",
            "body": "Luffy dreams of becoming the Pirate King and finding the legendary One Piece. His crew supports him in this grand adventure."
        }]
}`

Here,
 It needs to show the `{"id":1}` Instead it shows as `{"id":"1"}`
this bug is not in the json-server@0.17.3

**Comment by typicode** [comment]
Hi,

It's actually not a bug. In v1 `id` is always a string.

I'll update the README to avoid any confusion.

**Comment by vazand** [comment]
Thanks Team,
I removed the OBJECT "id" from the json and ran it, looks like the json-server automatically created an OBJECT id and gave a string value for it. NICE

**Comment by BachiMjavanadze** [comment]
> 
> It's actually not a bug. In v1 `id` is always a string.
> 

really not good decision :(
