### ISSUE TITLE
Issues with installing to non alpha version

### ISSUE THREAD

**Issue by Timofey-Makhankov** [typicode/json-server#1514]
I have been working on a json-server project. I have used a docker image to create the json-server and deploy it. recently, i had issues with my image. after some time, i figured out the problem. since using npm install / yarn add will always install the latest version, that i was using the alpha version of Json-server. I was able to resolve the issue by setting the stable verion of json-server "0.7.4". 

The reason why i have opened the issue is that, i wanted to ask, if you can set the stable version to be "0.7.4" in the npm registry. you could still be able use alpha verions by setting it yourself. example: "yarn add json-server@*version*". In the future of course, you can set it to the stable verion of "1.x"

**Comment by textbook** [comment]
Completed? https://www.npmjs.com/package/json-server?activeTab=versions says `latest` is still `alpha.23`.

**Comment by Timofey-Makhankov** [comment]
I just closed the Issue, since it is not a problem anymore. Thanks for the help
