### ISSUE TITLE
Heroku: This request has been blocked; the content must be served over HTTPS

### ISSUE THREAD

**Issue by sharpmachine** [typicode/json-server#152]
I'm having trouble trying to get my app to connect to the json-server on heroku.

Errors:

```
Mixed Content: The page at 'https://casemanger.herokuapp.com/#/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://localhost:3000/subjects'. This request has been blocked; the content must be served over HTTPS
Mixed Content: The page at 'https://casemanger.herokuapp.com/#/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://localhost:3000/subjectDomainRank'. This request has been blocked; the content must be served over HTTPS
Mixed Content: The page at 'https://casemanger.herokuapp.com/#/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://localhost:3000/domains'. This request has been blocked; the content must be served over HTTPS.
```
my web.js:
```javascript
var gzippo = require('gzippo');
var express = require('express');
var morgan = require('morgan');
var jsonServer = require('json-server');
var app = express();

app.use(morgan('dev'));
app.use(gzippo.staticGzip("" + __dirname + "/dist"));
app.listen(process.env.PORT || 5000);

// Returns an Express server
var server = jsonServer.create();

// Set default middlewares (logger, static, cors and no-cache)
server.use(jsonServer.defaults);

// Returns an Express router
var router = jsonServer.router('db/db.json');
server.use(router);

server.listen(3000);
```

I'm using restangular as well:

```javascript
  'use strict';

angular.module('casemanagerApp')
.config(function($stateProvider, $urlRouterProvider, RestangularProvider) {

  $urlRouterProvider.otherwise('fourzerofour');
  RestangularProvider.setBaseUrl('http://localhost:3000/');

  $stateProvider

  //404
  .state('four_zero_four', {
    url: '/fourzerofour',
    templateUrl: '404.html'
  })

  // GET /components
  .state('components', {
    url: '/components',
    templateUrl: 'components/html_components/index.html',
    controller: 'ComponentDemosCtrl'
  });
});
```

Any help would be awesome.

**Comment by typicode** [comment]
You can't make requests from https to http.
I would suggest, if it's possible, that you run casemanager locally.

For example, casemanager would be running on http://localhost:4000 and JSON Server on http://localhost:3000

The other solution that may work would be to run JSON Server on https, but I think the setup would be more complicated.

**Comment by sharpmachine** [comment]
Hey @typicode 

I've been developing it locally but I want to post my progress weekly to Heroku so I can just send out a link to the app and other people in my company can see my progress.  

So you're saying that it's not possible to do this?  Can't I run JSON server on Heroku.  Like if my URL was `https://myapp.heroku.com` and app was on port 4000 but then I had the JSON server on port 3000 (`https://myapp.heroku.com:3000`).

**Comment by typicode** [comment]
Thanks for the explanations, I understand better :)

Refactor your `web.js` to serve your static files and API on the same port:

```javascript
var gzippo = require('gzippo');
var express = require('express');
var morgan = require('morgan');
var jsonServer = require('json-server');
var app = express();

app.use(morgan('dev'));
app.use(gzippo.staticGzip(__dirname + '/dist'));
app.use(jsonServer.router('db/db.json'));
app.listen(process.env.PORT || 3000);
```

And remove this `RestangularProvider.setBaseUrl('http://localhost:3000/');`.

This way you won't have https or port problems, it'll be served from the same place.

You can have a look at https://github.com/typicode/jsonplaceholder, it's running on Heroku. In `/public` there are some AJAX requests and the API is served on the same URL.

**Comment by sharpmachine** [comment]
That was it.  I know you're super busy but if you have time could you explain why that works? I just wanna understand it.  If you don't have time I understand.

Thanks for your help!

**Comment by typicode** [comment]
Sure, this was the situation before (let's say you have a `posts` array in `db.json`):
https://casemanager.herokuapp.com was making requests to [http://localhost:3000/posts]()

And you had errors because of [mixed content](https://developer.mozilla.org/en/docs/Security/MixedContent). Basically, you can't make requests from an https website to retrieve data over http.
It would have worked if you had an URL like http://casemanager.herokuapp.com

With the refactoring, you're in the following situation:
https://casemanager.herokuapp.com makes request to https://casemanager.herokuapp.com/posts

The server is serving both JSON and static files using the same protocol.

You're always using https from end to end, so the browser is happy because everything is encrypted.

Hope it answers your question.

**Comment by sharpmachine** [comment]
Thanks @typicode!  Really appreciate all your help.  JSON Server is awesome.
