### ISSUE TITLE
quit the json-server

### ISSUE THREAD

**Issue by dashengSun** [typicode/json-server#153]
I am new bee in json-server. How can i stop the json-server on my terminal.

**Comment by typicode** [comment]
`ctrl + c` ;)

**Comment by BenRKarl** [comment]
How does one kill the server if not using the CLI, for example if I'm requiring the module in a test file. My assumption is there should be a .stop() or .kill() method, similar to how .listen() starts the server.

**Comment by typicode** [comment]
@BenRKarl There is :) json-server is built on Express so you get access to all the usual methods of https://nodejs.org/api/http.html#http_class_http_server

```js
var jsonServer = require('json-server')
var app = jsonServer.create()

// ...

var server = app.listen(3000)

// ...

server.close(function () {
  console.log('closed')
})
```

Don't know what your tests look like, but I would recommend checking [supertest](https://github.com/visionmedia/supertest), it makes testing Express servers very easy (it's used in the project).

**Comment by sboudouk** [comment]
You should add this to README.md @typicode.

Or I'll do a PR when I'm back at home.

**Comment by YahyaElharony** [comment]
@typicode I am a new in NodeJS and I saw in the tutorial that he stopped the server and start it again without saying how he typed "^C". Thanks!

**Comment by sboudouk** [comment]
"^C" stand for `ctrl + c` :)

**Comment by baka-gaijin-hakka** [comment]
Running ^C returns me a message that says to update `json-server` and doesn't quit the server.

**Comment by titulus** [comment]
@baka-gaijin-hakka same for me.
but updating solves it :smile:

**Comment by rohan-deshpande** [comment]
I can't call the `close` method on the server instance, it says it's undefined (which from looking at the source, makes sense). Am I missing something? I am wanting to run multiple tests against the server with different middlewares, so I'd like to stop the server and start it for each test... is it possible?

**Comment by PLQin** [comment]
// close service (sometimes there are some delays)
server.close(function(err) {
  // do something
});
 
// exit node process
process.exit()
 
// use module
www.npmjs.com/package/kill-port

**Comment by TechMarinar** [comment]
thanx man
