### ISSUE TITLE
Has the --delay option been removed?

### ISSUE THREAD

**Issue by iiShahad** [typicode/json-server#1534]
I'm attempting to simulate a delayed response from my server for development purposes using json-server. I used the following command to start the server, intending to introduce a 5000ms delay to responses:
 `json-server --delay 5000 --watch data/cities.json --port 8000` 

However, when I run this command, I encounter the following error:
`Unknown option '--delay'`

so, has the `--delay` option been deprecated in the latest versions of json-server?

**Comment by DiggidyDev** [comment]
It looks like it has been removed, as per the [README](https://github.com/typicode/json-server?tab=readme-ov-file#notable-differences-with-v017):

> - use Chrome's `Network tab > throtling` to delay requests instead of `--delay` CLI option

And it's no longer listed in the [CLI args](https://github.com/typicode/json-server/blob/main/src/bin.ts#L31).

**Comment by Bhupender2** [comment]
why it got removed  --delay 500 is so useful

**Comment by ZakariaBouzouf** [comment]
Could you bring this option it was really usefull

**Comment by hamzazubair2713** [comment]
working on version 0.17.4

**Comment by ArthurWillameBr** [comment]
This is very necessary

**Comment by nileshparwan** [comment]
With the new version, i think, if I understood correctly. You must use the network tab throttling.
<img width="878" alt="image" src="https://github.com/typicode/json-server/assets/25635312/9ad057db-c197-43b7-908e-c35d61167882">

Or you can also switch to a previous version  "json-server": "^0.17.4",
and add this script to your package.json file: 
    "db": "json-server --watch db.json --port 3100",
    "db:delay": "json-server --delay 3000 --watch db.json --port 3100"

**Comment by Vector-Green** [comment]
we need delay on server side in some cases, like to simulate queues etc(

**Comment by Tasfin660** [comment]
I think you can use an older version like 
`npm i json-server@0.17.3`

**Comment by tobi-or-not-tobi** [comment]
Network throttling on the browser affects all resources, which is pretty annoying dx, while a delay on the API gives a more realistic experience.

**Comment by hansas01** [comment]
**npm install -g json-server@0.17.0**

it has been deprecated but with the above install you are good to go

**Comment by thardy** [comment]
I won't be using any version of json-server without a delay option. The removal of this option was a very bad decision. "Just do these extra steps" is never a good answer when we used to be able to bundle the behavior into the api and never think about it again.

**Comment by vinaciotm** [comment]
please rollback delay option.

**Comment by Gustavo-Cauzzi** [comment]
+1 for doing a rollback of the delay option. It was one of the main features. I don't know how it seemed reasonable to remove such a helpful feature like this one.

**Comment by fandredev** [comment]
+1

**Comment by tobiaszciesielski** [comment]
Rollback this option please

**Comment by ggteixeira** [comment]
Yeah, it would be nice to have that delay feature. It was optional; why not keep it?

**Comment by hugodemelo** [comment]
using chrome's throttling option is NOT the same as using json-server delay option, sometimes we just need the delay to come from the server and not for all resources requested by the browser.

why not leave it optional?

**Comment by stackanthony** [comment]
Damn can't believe they did this lol. Was very helpful :(

**Comment by sysmat** [comment]
+1

**Comment by rbpolim** [comment]
+1

**Comment by raybagas7** [comment]
+1

**Comment by Mig-uel** [comment]
+1000

**Comment by iamdigitalminimalist** [comment]
+1

**Comment by dawidof** [comment]
bring back +1

**Comment by Vitor-Franco** [comment]
bring back +1

**Comment by kkdy21** [comment]
bring back +1

**Comment by Elielson77** [comment]
bring back +1

**Comment by Scottsdaaale** [comment]
bring back the delay.

**Comment by a-irizi** [comment]
the delay option was cool to have

**Comment by kale-Dev1** [comment]
Wow I was just wondering my it wasn't working for me.  Bring bring it back😤

**Comment by pbarone** [comment]
+1 this was really useful!

**Comment by m-shum** [comment]
I literally downloaded this package solely for the delay option. The people need this!

**Comment by Alex-Paris** [comment]
I've made a copy of the project on it's version [1.0.0-beta.3](https://github.com/typicode/json-server/commit/6aa56d9581488d9bcd1baf42c4c97b293cd9ee99) just to include this option.

Fell free to use it on your projects or copy (or whatever):
`npm i @paristech/json-server -D`

**Comment by arafatah** [comment]
+1 rollback delay option.

**Comment by lucasltavares** [comment]
Bring back delay option!!!

**Comment by poc7667** [comment]
delay is so useful, not all developer use chrome as only use case. why remove this. had to roll back the earlier version.

**Comment by sidneydurant** [comment]
Network throttling is frustrating to use compared to --delay. My whole page now takes longer. I just need to test throttling for my api calls (ex to check loading screens). I don't want to wait a few extra seconds for my App to load when using chrome's network throttling.

**Comment by XasanMussa** [comment]
still its missing bring it back

**Comment by EkramH** [comment]
The delay was really helpful, network throttling is giving me a headache.

**Comment by aa-ghazzy** [comment]
Why just why???

**Comment by Praise7165** [comment]
+1 please bring it back.

**Comment by Omar-Tnt04** [comment]
I think this is a good example of where a migration note could help users moving from older json-server examples to v1.

From a user perspective, `--delay` was useful for simulating slow APIs during frontend development. If the option is intentionally removed or no longer supported, it would be helpful to document the recommended replacement approach, such as using middleware or another supported configuration pattern.

So I think the main discussion point is whether json-server v1 should keep a simple built-in delay option for prototyping, or keep the CLI smaller and document how users can simulate delay outside the core CLI.
