### ISSUE TITLE
Single post location for _embed update?

### ISSUE THREAD

**Issue by wguldin** [typicode/json-server#154]
Hi everyone!

json-server is a great tool so far. I'm just having trouble updating some information. I'm pulling in data using the _embed feature, which works great. 

The url I'm using for these requests is http://localhost:3000/contacts/:id/?_embed=tags

Which returns data like this: 

```json
{
  "id": "13ca5c4e-e129-4ce1-afbf-d6e0cfb6fc5d",
  "firstname": "James",
  "lastname": "Testerson Smith",
  "tags": [
    {
      "id": "70672388-7864-452a-ba7f-da319fe67913",
      "contactId": "13ca5c4e-e129-4ce1-afbf-d6e0cfb6fc5d",
      "tagLabel": "Tag 1"
    }
  ],
```
But, I then edit some of this information, including the first name and a tag associated with this person. Is there a single URL I can post to that will process the information? 

Right now I'm doing separate ajax calls to update the data, but that feels wrong.

**Comment by wguldin** [comment]
By the way, what I tried doing was a 'POST' to '/contacts', but it tries to add the embedded objects to that section of the database, instead of updating them in their respective places, hence the multiple ajax requests to update a single record. 

Thanks!

**Comment by typicode** [comment]
Hi @wguldin,

`_embed` is mostly a simple way to avoid making multiple calls when doing a `GET`.

But, on the other side, there's no route for making an update in a single call.

**Comment by wguldin** [comment]
Ok, that's fine, I just wanted to double check. Thanks!
