### ISSUE TITLE
Nested Collection Single Record Issue Noticed w/ 0.7.21

### ISSUE THREAD

**Issue by edm00se** [typicode/json-server#155]
### Situation
I noticed (recently, since upgrading to 0.7.21) that I'm getting a 404 for all individual records in nested resources. Knowing this was working previously, I uninstalled 0.7.21 and **installed @ version 0.7.20 and found everything working as expected**.

To reproduce, you can check out my environment if there are any specifics, with [this repo of mine](https://github.com/edm00se/AnAppOfIceAndFire).

### Steps to Reproduce
1. Install (I did globally) latest (0.7.21) version of json-server
2. git clone my repo (or just copy my [`housesDB.json`](https://github.com/edm00se/AnAppOfIceAndFire/blob/master/housesDB.json) and [`routes.json`](https://github.com/edm00se/AnAppOfIceAndFire/blob/master/routes.json) files)
3. run `json-server` (I'm using a custom ID property and a custom routing structure), sample invocation: `json-server --id unid housesDB.json --watch --routes routes.json`
4. attempt to GET a single record by its ID property (e.g.- `/houses/EF827514E00D43CA88257E000016915D`)

The resource collection GET works as expected, GET-ing a single record returns a 404 (per both browser and `json-server` output).

**Comment by edm00se** [comment]
I should mention I confirmed this was the case for me on both a Mac OS X machine (Yosemite) and a Windows 7 machine.

**Comment by typicode** [comment]
Thanks for raising the issue, sorry for that.

After refactoring the CLI, there was some regression. For example, `--id` is not working. But it has been fixed, I'll publish soon and let you know here.

**Comment by edm00se** [comment]
Good to know, thanks. 😀

**Comment by typicode** [comment]
Just published `v0.7.23` should be good now. Let me know if you spot other things :)

**Comment by edm00se** [comment]
I'm happy to confirm it's working for me at the latest (0.7.23) level. I'll keep an eye out :-P .

**Comment by typicode** [comment]
Great! :)
