### ISSUE TITLE
configurable static file direcotry request

### ISSUE THREAD

**Issue by kuitos** [typicode/json-server#158]
can u add a feature that we can configure the static file directory but not default 'public' by argv?  
like this  
```bash
json-server --watch db.json --static /src
```

**Comment by syzer** [comment]
:-1:

**Comment by syzer** [comment]
u mean ```json-server src/server/mocks/db.json```
its already implemented

**Comment by typicode** [comment]
Hi @kuitos 

No plan to add one to the CLI right now. But you have some workarounds that you may already know.

You can symlink `public` to `src` if you're on OS X/Linux.
Or you can use the project as a module and add this:

```javascript
// ...
server = jsonServer.create()
server.static('src')
// ...
```

By the way, if you have the time, I would be interested to understand your use-case and why you use `src` or can't use another directory? As far as I know, it's pretty common to have a `public` folder.

**Comment by kuitos** [comment]
Hi @typicode 
yes,I know what u mean,and I agree your opinion that the `public` folder is pretty common.  
I am so lazy to write a few line js to config static dir so I want a cli support😄  
now I am looking for a powerful mock server for my company and It have to compatible with all project,that why I have such a request.
now I had forked your repo and modify a few lines to support my request😜
by the way,you are the most patient author of open source that I had met,and thanks for your great project!👍

**Comment by typicode** [comment]
@kuitos thank you for closing the issue and the nice comment :)

**Comment by typicode** [comment]
@kuitos just as an update, a `--static` option has been added. It's now possible to use something else than `public` ;)

**Comment by kuitos** [comment]
awesome👍

**Comment by syzer** [comment]
:+1:

On Thu, Sep 24, 2015 at 4:02 AM, Kuitos <notifications@github.com> wrote:

> awesome👍
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/typicode/json-server/issues/158#issuecomment-142782180>
> .
>



-- 
--Lukas 'SyZer' Gintowt

**Comment by PLQin** [comment]
There's a better solution. Look at this https://github.com/typicode/json-server/issues/124
