### ISSUE TITLE
provide watch data file change option

### ISSUE THREAD

**Issue by tjwudi** [typicode/json-server#16]
When using `json-server db.json`, if **db.json** is changed, the server will still return old data. It can be better if it is able to watch file change and refresh server data automatically.

**Comment by CatPoker** [comment]
Change search option to past 24 hours in google

**Comment by typicode** [comment]
Closing this issue. The idea is nice, but maybe too complicated to implement.

The hard part would be to know when the file has been modified by the user or the server.

For example, if db is watched and there is a POST, the server would be restarted because the db has changed.

**Comment by typicode** [comment]
Just for the update, it was actually a lot less complicated than I thought.
So, it's now available in `v0.7.7` (tested on Linux) :)
