### ISSUE TITLE
add suffix in url

### ISSUE THREAD

**Issue by Jayin** [typicode/json-server#161]
json server work friendly to REST API.

But our team consider to  add a suffix in url to declare what's it need to return 

for example:

add `json` Suffix to return json
```
GET    /posts.json
GET    /posts/1.json
GET    /posts/1/comments.json
POST   /posts.json
PUT    /posts/1.json
PATCH  /posts/1.json
DELETE /posts/1.json
```

add `json` Suffix to tell backend it should return `html`
```
GET    /posts.html
GET    /posts/1.html
```

on this way , it may be more friendly to SEO

**Comment by typicode** [comment]
Hi @Jayin, you can use rewrite rules for this.

Create a `router.json`:

```json
{
  "/:resource.json": "/:resource",
  "/:resource/:id.json": "/:resource/:id",
  "/:parent/:resource/:id.json": "/:parent/:resource/:id"
}
```

In `./public` add your html files:

```
./public/posts.html
./public/posts/1.html
```

Then start JSON Server:

```
json-server db.json -r router.json
```

**Comment by Jayin** [comment]
:+1: Cool, thanks you!
