### ISSUE TITLE
Unsupported type

### ISSUE THREAD

**Issue by napstercake** [typicode/json-server#162]
What did I do:

    1. $ npm install -g json-server
    2. Prepare a simple json file: {"id": "1", "name": "Ricardo", "lastname": "Gonzales" }
    3. $ json-server --watch logincorrect.json

What did I get from CMD:

    \{^_^}/ hi!

    Loading C:\Users\xxx\Desktop\logincorrect.json
    Done
    C:\Users\xxx\AppData\Roaming\npm\node_modules\json-server\src\server\router\index.js:70
    throw new Error('Unsupported type')
          ^
    Error: Unsupported type
    at Object.module.exports [as router] (C:\Users\xxx\AppData\Roaming\npm\node_modules\json-server\src\server\router\index.js:70:11)
    at createApp (C:\Users\xxx\AppData\Roaming\npm\node_modules\json-server\src\cli\run.js:37:27)

Any help?

**Comment by typicode** [comment]
It means that you're using an unsupported type in your JSON file.
You need to use either arrays of objects or plain objects. For example, this will work:

```json
{
  "users": [
    {"id": "1", "name": "Ricardo", "lastname": "Gonzales" }
  ],
  "array": [{}, {}, {}]
  "object": {}
}
```

**Comment by napstercake** [comment]
Thanks for your responding. Now is working! Can I set headers responses like my backend does using this tool?

**Comment by typicode** [comment]
You're welcome. What kind of headers do you need?

**Comment by napstercake** [comment]
What my backend is return now is a simple json and a token. This token is encripted and its placed on the header response.

**Comment by typicode** [comment]
Ok I see.
You need to use the project as a module. Actually, JSON Server is built on of Express so you can use any middleware with it.

If you need to access the response before it's sent you can do so this way:

```javascript
var jsonServer = require('json-server')

// Returns an Express server
var server = jsonServer.create()

// Set default middlewares (logger, static, cors and no-cache)
server.use(jsonServer.defaults)

// Returns an Express router
var router = jsonServer.router('db.json')
server.use(router)

// render is called just before returning the response
// so you can do some customization here
router.render = function (req, res) {
  res.setHeader('X-SOME-HEADER', '...') 
  res.jsonp(res.locals.data)
}

server.listen(3000)
```

You can also add or overwrite routes.

**Comment by napstercake** [comment]
Thank you so much and thanks for your time! I'm very new in node, so I guess I should write that code in a file and run it as a script using node right?

**Comment by typicode** [comment]
Yes, absolutely.

```bash
npm install json-server # install it locally
# create an index.js
nodemon index.js
```
