### ISSUE TITLE
Option to generate db.json file

### ISSUE THREAD

**Issue by dfsq** [typicode/json-server#164]
Would it make sense to augment json-server with simple DB scheme generator to create and scaffold db.json file? I can see it as pretty convenient addition to functionality. In fact, I wrote the generator that works with `json-server --scaffold` option by asking user several questions to add collections and fields. E.g.:

```bash
$ json-server --scaffold db.json
$ > Enter collection name db.json should have (ex: posts): users
$ >> What fields should "users" have?
     Comma-separated pairs fieldname:fieldtype (ex: id:number, username:username) 
  id:index, username:username, fname:firstName, lname:lastName, address:address, age:number
$ > Add another collection? (y/n): n
$ db.json was created
```

I used online filltext.com service to generate JSON.

So I find this functionality quite useful for simple tables generation. But my question, is it too much for json-server to do this too?

**Comment by typicode** [comment]
Hi @dfsq 

Nice idea :)

But as you suggested, I think that it would be too much to include info the project.
However if you create a third-party tool that does this, I would be happy to link to it :)

**Comment by dfsq** [comment]
Yes, it's better is json-server to remain slim and focused on one thing.
I'll publish this generator package myself, let me just write some tests.

**Comment by dfsq** [comment]
I create [JSON server init](https://www.npmjs.com/package/json-server-init) package. Hope it can be useful for faster JSON db files generation.

```
$ json-server-init -s dev.json
# series of prompt
```

Then use json-server as usual:

```bash
$ json-server dev.json
```

**Comment by typicode** [comment]
Awesome :) will give it a try next week (not in front of a computer right now)
