### ISSUE TITLE
"Unsupported type" update 0.7.20 to 0.7.23 

### ISSUE THREAD

**Issue by yeahoffline** [typicode/json-server#165]
```javascript
    throw new Error('Unsupported type')
          ^
Error: Unsupported type
```

@Line:
```javascript
var router = jsonServer.router('db.json');
```

db.json is valid....

**Comment by typicode** [comment]
Can you check that you don't have anything else than an array or object?

```json
{
  "array_ok": [{}, {}],
  "object_ok": {},
  "integer_ko": 1,
  "string_ko": ""
}
```

**Comment by yeahoffline** [comment]
i validated the db.json various times... its valid but large (8247 lines)

**Comment by benjaminapetersen** [comment]
I'll offer a suggestion, maybe will help track down.  If your data file looks something like this, it should work fine: 

```javascript
var // broke the file up into smaller pieces
    users = require('./payloads/users.js'),
    posts = require('./payloads/posts.js'),
    roles = require('./payloads/roles.js'),
    comments = require('./payloads/comments.js');

module.exports = function() {
  return {
    "posts": posts(),
    "users": users(),
    "roles": roles(),
    "comments" : comments()
  };
};

```

Make sure module.exports is there, and you call functions appropriately.  It will complain if items are not structured properly.

**Comment by typicode** [comment]
@benjaminapetersen thanks, good suggestion :)

@yeahoffline I've also updated the error message to be more explicit in `v0.7.25`. So for example, with:

```json
{
  "foo": 1
}
```

You should get:

```
Error: Type of "foo" (number) in db.json is not supported. Use objects or arrays of objects.
...
```
Hope it'll help.

**Comment by yeahoffline** [comment]
got it, was a number. sorry for the noise and thanks for alle the solutions !

**Comment by typicode** [comment]
You're welcome, it helped improve the error message :)

**Comment by elgalu** [comment]
Thanks for the error message :) what I'm missing is

Why number is not supported?

**Comment by elgalu** [comment]
Ah never mind, I just needed to wrap the whole thing in a parent arbitrary named object e.g. `{ "all": { ...`
