### ISSUE TITLE
Option to configure complex routes?

### ISSUE THREAD

**Issue by shershen08** [typicode/json-server#167]
According to API - making use of ```routes.json``` file settings can help to create aliaces for additional routes like - ```/blog/posts/1/show``` or ```/posts/1/comments```.

But is there a way to mock more sophisticated urls, say like - ```Data/Items/42/Document/346.json``` etc. ? Reason: besides modern clean APIs that are designed from scratch in some case there can be legacy APIs that your client side code has to be compatible with.

**Comment by typicode** [comment]
Hi @shershen08 

Sorry for the delay, wasn't in front of a computer during the past week.
If `Document` ids are unique, you can create the following route:

```json
{
  "/Data/Items/:itemId/Document/:id.json": "/Document/:id"
}
```

`:itemId` will be ignored.

**Comment by shershen08** [comment]
Thanks, it worked with the following structure in db.json :
```
"document": [
    {
      "id": 346,
      "itemId": 42,
      "foo": "bar",
      "body": "some data"
    }
  ]
```
