### ISSUE TITLE
Embed on lists

### ISSUE THREAD

**Issue by matheusazzi** [typicode/json-server#170]
How can I embed on lists, for example `/posts/1?_embed=comments` works fine.

But `/posts?_embed=comments` doesn't work.

There's a way to embed on lists?

**Comment by typicode** [comment]
Not yet, but it's a planned feature.

**Comment by typicode** [comment]
Just released `v0.7.26`, lists should now support `_embed` and `_expand` query parameters :)

**Comment by matheusazzi** [comment]
:clap: :heart_eyes: :clap:
