### ISSUE TITLE
customize response code

### ISSUE THREAD

**Issue by peacepassion** [typicode/json-server#171]
It seems json-server can only returns 201. I want to return 500 with error message. So I can test error handling for my app.

**Comment by typicode** [comment]
Hi @peacepassion,

You can "tweak" the response this way:

```javascript
// index.js
var jsonServer = require('json-server')

var server = jsonServer.create()
var router = jsonServer.router('db.json')

router.render = function (req, res) {
  if (someCondition) {
    res.status(500).jsonp({
     error: "some error"
    })
  }
}

server.use(router)
server.listen(3000)
```

Use then `req` and `res` properties to return an error for certain conditions only.

**Comment by peacepassion** [comment]
Thanks, @typicode

**Comment by Noyabronok** [comment]
this example should be in the readme.md

**Comment by juanbrujo** [comment]
This was my solution: https://gist.github.com/juanbrujo/efdcf6ab9eacbd5b5d69884233d0a3ce
