### ISSUE TITLE
Change static public directory name

### ISSUE THREAD

**Issue by felippenardi** [typicode/json-server#173]
I think it should be nice to have the option to change the name of the target directory used for static files.

I imagine a flag `--public` on the CLI with the directory name as argument.

**Comment by boris-marinov** [comment]
+1

**Comment by typicode** [comment]
Just released `v0.8.0`, you can use the new `--static` flag to set a custom static files directory :+1:

**Comment by felippenardi** [comment]
Beautiful :+1:

**Comment by PLQin** [comment]
There's a better solution. Look at this [static](https://github.com/typicode/json-server/issues/124)
