### ISSUE TITLE
Command failed: wmic os get locale. Description = 1% is not a valid Win32 application

### ISSUE THREAD

**Issue by ghost** [typicode/json-server#175]
When I try to use json-server, I am getting an error
Error: Command failed: wmic os get locale
ERROR:
Description = 1% is not a valid Win32 application.

PFB the screen shot.

Some details:
Ember-cli and ember-cli-windows are installed.

![json-server](https://cloud.githubusercontent.com/assets/8611508/9540176/075e9a52-4d79-11e5-932a-3d3801479739.png)

**Comment by anonymousch** [comment]
you can use command "node  json-server/bin/index.js db.js"

**Comment by typicode** [comment]
It may be related to https://github.com/bcoe/yargs/issues/241

@ghost Can you try reinstalling json-server so that you get the latest yargs version?
