### ISSUE TITLE
how to run it just use source

### ISSUE THREAD

**Issue by ikidou** [typicode/json-server#178]
when I use `node bin/index.js --watch db.json` ,it doesn't work, the nodejs tell me `Cannot find module 'update-notifier'`.I should install other module befor I use this server? I can't use the ` nmp install -g json-server` command line to install this server,the network is limited.

**Comment by typicode** [comment]
Hi @ikidou,

Yes, `update-notifier` needs to be installed as well as other `dependencies` listed in https://github.com/typicode/json-server/blob/master/package.json

You can do so by running `npm install` from source directory. Can you use it?

**Comment by ikidou** [comment]
Hi，Thanks for your answer，I re-tried again after setting the proxy and with admin privileges, the installation was successful。And The server is working now，Thinks

**Comment by typicode** [comment]
Great :)
