### ISSUE TITLE
Can't add payload to db.json

### ISSUE THREAD

**Issue by rubystar** [typicode/json-server#180]
Hi, when i post through postman, only id is getting created the payload is getting ignored:
following is my db.json
```
{"contacts": [
    {
      "id": 1,
      "name": "venkat",
      "mobile": "9959345033"
    },
    {
      "id": 2,
      "name": "sai",
      "mobile": "9959345034"
    }
  ]
}
```

when i made a post request to ```http://localhost:3000/contacts```

with name "xyz", mobile "9999999999"

this is how my db.json looks like:

```
[
    {
        "id": 1,
        "name": "venkat",
        "mobile": "9959345033"
    },
    {
        "id": 2,
        "name": "sai",
        "mobile": "9959345034"
    },
    {
        "id": 3
    }
]
```
Looks like I am missing something basic.Can you help...

**Comment by rubystar** [comment]
Actually from the backbone app, it's working fine. Looks like an issue with postman.

**Comment by typicode** [comment]
From what I remember, there's many options when sending data with postman. I would check how JSON is sent. But I've used postman + JSON Server in the past, so they're not incompatible :)

Hope this will help.

**Comment by catchOneW** [comment]
i also meet this problem ,when i use  dva/request,
`request('/api/data', {
    method: 'POST',
    body: [values],
  });`
my db.json
 `{
  "dataaaa": [
    {
      "id": 1,
      "name": "1",
      "email": "2",
      "website": "3"
    },
    {
      "id": 2,
      "name": "2",
      "email": "2",
      "website": "3"
    },
    {
      "id": 3,
      "name": "3",
      "email": "2",
      "website": "3"
    },
    {
      "id": 4,
      "name": "4",
      "email": "2",
      "website": "3"
    },
    {
      "id": 5
    },
    {
      "id": 6
    }
  ]
}`
