### ISSUE TITLE
user json-server with lowdb

### ISSUE THREAD

**Issue by likun7981** [typicode/json-server#181]
you say : " if you make POST, PUT, PATCH or DELETE requests, changes will be automatically and safely saved to db.json using lowdb.",how to use json-server with lowdb ,can you write a demo ? thank you ,I can not use lowdb for automatically save to db.json

**Comment by typicode** [comment]
Actually, you have nothing to do.

```json
{
  "posts": []
}
```

```
json-server db.json
```

Make a POST request to `http://localhost:3000/posts` with `{"body": "test"}` and if you check `db.json`, you'll see that it's been updated.

```json
{
  "posts": [
    {
      "id": 1,
      "body": "test"
    }
  ]
}
```

You can check this video tutorial too:

https://egghead.io/lessons/nodejs-creating-demo-apis-with-json-server

**Comment by likun7981** [comment]
Thank you ！I succeeded！

**Comment by typicode** [comment]
Great :)
