### ISSUE TITLE
Changing the port json-server runs on?

### ISSUE THREAD

**Issue by claym** [typicode/json-server#186]
Is it possible to run the app on a different port than the default 3000?

**Comment by kartamyshev** [comment]
+ 1
Would be great to have kind of Settings file to configure.
https://github.com/typicode/json-server/issues/185 could be an option in this file as well. Just as an example.

**Comment by typicode** [comment]
Sure `json-server -p 4000 db.json`

**Comment by phamngoctuong** [comment]
file package.json (Windows)
"scripts": {
    "start": "set PORT=4000 && react-scripts start"
  }
file package.json (Ubuntu)
"scripts": {
    "start": "export PORT=4000 && react-scripts start"
  }

**Comment by GerdyRiban** [comment]
package.json     "start" : "Port = ####  react-scripts start"
