### ISSUE TITLE
Delete a non-existing resource still returns 200

### ISSUE THREAD

**Issue by ingro** [typicode/json-server#187]
Hello, I found this strange behaviour when trying to delete a resource with a wrong id. 
I'm not sure about what the REST standards says, but it shouldn't be clearer if the server return some kind of error, like a 404, when this happens?

**Comment by typicode** [comment]
I agree. I've fixed it on master and will release a new version soon :)

**Comment by ingro** [comment]
Thank you @typicode , your library has saved me a lot of time lately and keeps getting better :)

**Comment by typicode** [comment]
Just released `0.8.2`.
Glad it's helpful, user feedback plays an important role in improvements too :)
