### ISSUE TITLE
Simulating authentication with json-server

### ISSUE THREAD

**Issue by webia1** [typicode/json-server#190]
Is there a proven approach to do that with json-server?

thank you
rgds ebia

**Comment by Isanderthul** [comment]
yes it is possible, I want to use this module in an example [node-oauth2-server](https://www.npmjs.com/package/node-oauth2-server). At the moment I am stuck with this error #264 , once that is done perhaps you would like to help me with the example.

**Comment by louizeks** [comment]
I found this sample, https://www.techiediaries.com/fake-api-jwt-json-server/

**Comment by webia1** [comment]
Thank you very much, 5-year waiting period was worth it :)
