### ISSUE TITLE
PUT rewrite whole data, but might only rewrite what was changed

### ISSUE THREAD

**Issue by adelura** [typicode/json-server#192]
Assuming we have following structure:

``` json
{
  "posts": [
    {
      "id": 1,
      "authorId": 2,
      "title": "bar"
    },
    {
      "id": 2,
      "authorId": 2,
      "title": "foo"
    }
  ],
  "comments": [
    {
      "id": 1,
      "postId": 1,
      "content": "bar"
    }
  ],
  "authors": [
    {
      "id": 1,
      "name": "Artur Delura"
    },
    {
      "id": 2,
      "name": "Beata Delura"
    }
  ]
}
```

And there is a request sent to update `post` title with id `1`:

``` js
$.ajax({
    url: "http://localhost:2121/posts/1",
    method: "PUT",
    data: {
         title: "baz"
    }
})
```

Then `authorId` field in `post` resource is lost.

I found this issue when I used such request: `http://localhost:2121/posts?authorId=1&_embed=comments` to get data. After updating I had no posts at all which was very strange :D

----

I think it's a good idea to change only properties which was intend to be changed. In this case it's only title.

**Comment by JuoCode** [comment]
@adelura Use `PATCH` method

**Comment by adelura** [comment]
@JuoCode That make sense... I didn't even know that `PATCH`exists. Thanks :+1:
