### ISSUE TITLE
any chance you would support comments in the db.json file?

### ISSUE THREAD

**Issue by tirams** [typicode/json-server#201]
For readonly static dbs it would be awesome to be able to add comments to the json data file. Maybe with use of the [strip-json-comment](https://github.com/sindresorhus/strip-json-comments) module?

**Comment by typicode** [comment]
Thank you for the link, didn't know about it :)

If you want to comment a read-only db, you can already do it by using a simple JS file: 

```js
// db.js
module.exports = function () {
  var db = {}

  // Some comments here
  db.posts = [
    // ...
  ]

  return db
}
```

```
json-server db.js
```

About `stip-json-comment`, I don't like the idea that all the comments could be deleted by a bad `POST`. So I'd rather not include it in the project.
