### ISSUE TITLE
mounting router at diff point (e.g. '/api') breaks home-screen

### ISSUE THREAD

**Issue by tony-kerz** [typicode/json-server#208]
```
server.use('/api', router)
```
yields the following in browser console:
```
GET http://localhost:3000/db 404 (Not Found)
```
and the home page fails like so:

<img width="404" alt="screen shot 2015-12-03 at 10 20 07 pm" src="https://cloud.githubusercontent.com/assets/1223231/11581078/18a4a696-9a0c-11e5-934b-28705019cf74.png">

any suggested work arounds or fixes? i would be happy to work on a p/r if someone could recommend an acceptable solution.

cheers,
tony.

**Comment by tony-kerz** [comment]
here is one solution:
use this:
```
app.use(jsonServer.rewriter({
  '/api/': '/'
}))
```
instead of:
```
server.use('/api', router)
```

**Comment by typicode** [comment]
Thank you for the tip :+1:

**Comment by Grsmto** [comment]
To be exact it's:

````
app.use(jsonServer.rewriter({
  '/api/': '/'
}), router)
```
