### ISSUE TITLE
Any routing support t integrate with koa?

### ISSUE THREAD

**Issue by Shuliyey** [typicode/json-server#210]
I've noticed that json-server uses express (default) style routing.

I want to make an application using koa (generator function style) and json-server.

I tried the below technique to route the /api to use the json-server

```node
var koa = require('koa');
var app = koa();
var route = require('json-server').router('db.json');

app.use("/api", route)
```

The above won't work , because the koa style app expects a generator function when calling the method .use

Is there any support, so that a routing method of require('json-server'), returns a generator style routing to be used in koa

**Comment by typicode** [comment]
Interesting case.

I tried with https://github.com/vkurchatkin/koa-connect

```js
var koa = require('koa');
var c2k = require('koa-connect');
var jsonServer = require('json-server');
var app = koa();

var server = jsonServer.create();
server.use(jsonServer.defaults());

var router = jsonServer.router({posts: []});
server.use(router);

app.use(c2k(server));
app.listen(3000);
```

And it almost works, except static assets can't be found (404).

**Comment by Shuliyey** [comment]
thank you so much @typicode , The below code worked :smile: 

```node
var koa = require("koa");
var route = require("koa-route");
var express = require("express");
var server = express();
var c2k = require("koa-connect");
var jsonServer = require("json-server");
var jsonServerRoute = jsonServer.router('db.json');

server.use("/api", jsonServerRoute);

app = koa();
app.use(c2k(server));
app.use(route.get("/", function * () {
  this.body = "Hello World";
}))
app.listen(3000);
```

http://localhost:3000/api is json-Server
http://localhost/ is "Hello World"

I didn't quite get the part when you say the "static assets can't be found (404)" :smile:

**Comment by typicode** [comment]
Glad it works :)

Well I noticed that when accessing localhost:3000, stylesheets and javascript files return 404 (for example: localhost:3000/stylesheets/style.css) but it's not a big deal.

**Comment by Shuliyey** [comment]
@typicode 

I see :smile: ,  adding the below would work  :) (as long as the stylesheets is under the **public** folder, it should work :smile: )

```node
var serve = require('koa-static');

// App configuration
app.use(serve(__dirname + '/public'));
```

Thank you so much :+1:
