### ISSUE TITLE
Not able to create a new collection

### ISSUE THREAD

**Issue by aman-c** [typicode/json-server#211]
Hi,

I am trying to do a simple post of a new collection which is not currently existing in db.json file, I get a 404 for that instead of the new collection created and record returned. But If I try to add an item to an existing collection(which is already there in db.json file), it is working fine. 

Can someone please check as it is a very basic thing which is not working?

Thanks.

Regards,
Aman C

**Comment by typicode** [comment]
Hi @aman-c,

Actually, it's the expected behaviour. In real APIs, it should not be possible for a user to create random collections simply by sending a `POST` to `/api/some-random-string` that's why in `json-server` it's the same even though it's a fake server.

Out of curiosity, what's your use case?

**Comment by aman-c** [comment]
hi,
My usecase is to create a dynamic component whose associated data I save in json-server. So for every new component to be created, I create a new collection in json-server. It was working in the earlier release but the new release is not supporting this. Would it possible for you to provide a switch which user can specify during launch if json-server will support new collections at runtime or not?

Thanks.

**Comment by aman-c** [comment]
Hi  @typicode ,
Any update on above?
Thanks.

Regards,
Aman C

**Comment by typicode** [comment]
Hi @aman-c,

Thank you for the explanation and sorry for the delay. Not sure if I'll add it back to json-server since it's not RESTful.

However, here's how you can add it:

```js
var jsonServer = require('json-server')
var server = jsonServer.create()
var router = jsonServer.router('db.json')
var db = router.db

server.use(jsonServer.defaults())
server.post('/:collection', function (req, res) {
  db.object[req.params.collection] = []
  db.write()
  res.end()
})
server.use(router)

server.listen(3000)

**Comment by aman-c** [comment]
Thanks for the reply!!

**Comment by chuanY** [comment]
hi type ,
thank for you  show how to add collection, but it not work on next request this collection,  should add some code like this:
router.stack.pop();
    router.stack.pop();
    var key1 = req.params.collection;
    router.use('/' + key1, plural(db, key1));

    router.use(function (req, res) {
        if (!res.locals.data) {
            res.status(404);
            res.locals.data = {}
        }

        router.render(req, res)
    });

    router.use(function (err, req, res, next) {
        console.error(err.stack);
        res.status(500).send(err.stack)
    });
