### ISSUE TITLE
POST only inserts "id"

### ISSUE THREAD

**Issue by crystalbyte** [typicode/json-server#218]
Hey,

I am using a simple route, such as /budgets.
Unfortunately when I post to that route it only inserts an "id" field. Is there some special header I need to add ?

**Comment by crystalbyte** [comment]
Not a json-server error. Thanks anyway.

**Comment by Shuunen** [comment]
How did you resolve this ?

**Comment by golestanirad** [comment]
i had the same problem, found the solution here https://www.youtube.com/watch?v=FyZBTbv7UM0
