### ISSUE TITLE
Can json-server running at background?

### ISSUE THREAD

**Issue by vanney9** [typicode/json-server#221]
I install json-server on Linux. And it works well when i type "json-server --watch db.json". But when I try to put json-server at background using commend "nohup json-server --watch db.json", error happened.
And here is the log file(nohup.out):
<img width="434" alt="2016-01-12 5 05 20" src="https://cloud.githubusercontent.com/assets/8433575/12259158/b9de14d2-b94e-11e5-9664-8825985b79a5.png">

**Comment by typicode** [comment]
Hmm can't seem to reproduce on OS X
I guess it's after you edit db.json that you have this error?

**Comment by typicode** [comment]
Reproducing on Linux...

**Comment by vanney9** [comment]
yeah, I run this commend "nohup json-server --watch db.json" on Linux, not OS X. Have you found out the problem?

**Comment by typicode** [comment]
No sorry, didn't have the time to check that. So if anyone has an idea about it or want to help with this.

BTW I'm working on a tool for managing background servers, if you want to give a try https://github.com/typicode/hotel (it's not as simple as a `nohup` though).

**Comment by adamlsmith** [comment]
I had experienced a similar problem, with a different version and hence line number:

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect EACCES
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19)


I am running:

Linux ip-172-30-2-68 3.13.0-83-generic #127-Ubuntu SMP Fri Mar 11 00:25:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

nodejs v0.10.25
json-server 0.8.10

**Comment by Gruck** [comment]
`Bad file descriptor` feels like json-server isn't really pleased nohup leads to no `stdin`.

found workarround, give it something to read :
`echo "\n" | nohup json-server db.json > logs.log &`

**Comment by a-sane** [comment]
I had same problem and i found workaround: 
`nohup json-server db.json </dev/null &`

**Comment by typicode** [comment]
Hi,

In the next version of JSON Server (`v0.9.2`), the error will be caught:
https://github.com/typicode/json-server/commit/c527e1ef87ec79818c7c1376e8451676782e4f6e#diff-9676bb4e4701737e2a8e762cd177b0f6R165

It will be possible then to use `nohup` without workarounds :)

**Comment by typicode** [comment]
`v0.9.2` with fix for `nohup` has just been published
