### ISSUE TITLE
OPTIONS requests ?

### ISSUE THREAD

**Issue by sboudouk** [typicode/json-server#223]
Hi,

Does your package support OPTIONS type requests ? I didn't read anything about it. How can we use them ?

**Comment by typicode** [comment]
Hi @sboudouk,

It's supported. If you have a front-end server on a different address than json-server (for example `localhost:8000` and `localhost:3000`), your browser will automatically make an `OPTIONS` request before making a `GET`, `POST`, ... request.

Usually, you almost never have to make an explicit `OPTIONS` request.

But if you want to try, you can do:

```
curl -X OPTIONS http://localhost:3000 -I
...
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET,HEAD,PUT,PATCH,POST,DELETE
...
```
