### ISSUE TITLE
request to http://localhost:3000/posts return empty object

### ISSUE THREAD

**Issue by cesarin3134** [typicode/json-server#228]
Hi,
I installed json-server following the instructions,
created a file db.json then put the code example into it
and finally run json-server --watch db.json but when i navigate to http://localhost:3000/posts
it only show me a empty object. 
it's seems as the server doesn't load the resource 
do you have any idea of how can i resolve it?
Thanks.

**Comment by cesarin3134** [comment]
![image](https://cloud.githubusercontent.com/assets/1257506/12642208/93331d38-c5b4-11e5-9cc1-e8947f20cf61.png)

**Comment by momo-aux** [comment]
In the screenshot above I see that it's loading the new.json.

**Comment by typicode** [comment]
Hi @cesarin3134,

As noticed, it seems it's just the wrong file (`new.json` instead of `db.json`).

@momo-aux Thank you for your help :)

**Comment by cesarin3134** [comment]
i was mistaken, i put the the wrong screenshot but the new file has the same code of db.json
![image](https://cloud.githubusercontent.com/assets/1257506/12645353/cfbfa7fc-c5c9-11e5-9944-904f82f88740.png)

**Comment by cesarin3134** [comment]
Sorry, i put the wrong screenshot, the new.json file has the same content of db.json and it return a empty object too.    

![image](https://cloud.githubusercontent.com/assets/1257506/12645497/c0e7f972-c5ca-11e5-9ab4-3f947c014a89.png)

**Comment by momo-aux** [comment]
If I get your screenshot right, you are starting out of the ~/Desktop/angularjs folder.
But your new.json is in the directive_example subfolder.
Try
json-server --watch directive_example/new.json
or start it from inside the directive_example/ folder.

**Comment by cesarin3134** [comment]
@momo-aux you were right, it was a problem path, 
i ran it from the right directory and it worked for me!
thanks a lot.  ;)

**Comment by zdravkoTsvetkov** [comment]
hi :) I have too this problem to React , I`m trying change directory , but I haven`t effect. Please to give me little bit help
