### ISSUE TITLE
how to host this in my domain ex: www.example.com

### ISSUE THREAD

**Issue by raviji** [typicode/json-server#231]
I want this server http://localhost:3000/ to http://example.com/api/endpoint/
please help me how to host in my server after creating api here

**Comment by momo-aux** [comment]
You know that this is a framework for prototyping and not a production server? :-)

If you have a server, that is capable of serving node.js just install it on the server, like on your machine.
If not, you can redirect the requests to your machine using dyndns or other services that provide forwarding to a changing ip adress.

**Comment by momo-aux** [comment]
Perhaps you just want your local system to act like www.example.com for your dev environment.
Then just replace your local host entry.

On Windows:
c:\WINDOWS\system32\drivers\etc\hosts
On Linux:
/etc/hosts

**Comment by typicode** [comment]
@momo-aux alternatively, you can now also use [hotel](https://github.com/typicode/hotel) if you want a local tld ;) or just manage your local servers.

You can also deploy to heroku or any other "platform as a service" (see [jsonplaceholder](https://github.com/typicode/jsonplaceholder)) but it will be only read-only.

**Comment by yuens1002** [comment]
hi, i'm trying to host an endpoint for demos. i have a digitalocean vps with linux 14.04 and apache2 configured.  my plan is to do the same thing you're doing with placeholder, but with my data and custom domain name for demo web apps i'm building. the question is, do you have more detail instructions on how do this? i read thru the current docs and did json-server db.json --static /my-domain-public-folder but that didn't do anything. i have verified that my custom domain public html folder is served and accessible from the web.
