### ISSUE TITLE
Can json-server run two xx.json files in one PC?

### ISSUE THREAD

**Issue by tancolo** [typicode/json-server#239]
Hi,

At Present, I exploring the ionic and json-server. Both of them are amazing.
 I Use json-server for my server side.
And I have one question, 
I have two json files in two different projects. When I run json-server like this:
**json-server --watch a_db.json ==> It's OK!**
But, when I run the same json-server cmd in an other project
**json-server --watch b_db.json**

### It show error~
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:3000
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1238:14)
    at listen (net.js:1274:10)
    at net.js:1383:9
    at doNTCallback3 (node.js:452:9)
    at process._tickCallback (node.js:358:17)
    at Function.Module.runMain (module.js:469:11)
    at startup (node.js:136:18)
    at node.js:963:3

### How could I run more one json-server files in different project?
like: one terminal run
**json-server --watch a_db.json**

an other terminal run
**json-server --watch b_db.json**

I know the json-server use the  http://localhost:3000 by default. So, If I open 2 xx.json files with two terminal, it will throw error.

**Comment by typicode** [comment]
Yes, simply start json-server on another port (`json-server --port 4000 b_db.json`).
I've merged @siawyoung's PR, it's now in the README too.

**Comment by tancolo** [comment]
@typicode  thank you for your feedback.
Woo, It's wonderful.
Thank you so much!

**Comment by typicode** [comment]
you're welcome
