### ISSUE TITLE
ids as string codes

### ISSUE THREAD

**Issue by davidemoro** [typicode/json-server#24]
This (awesome) projects don't let you use integer ids.

In other words, you can provide something like:

``` json
{
  "posts": [
    { "id": "1", "body": "foo" },
    { "id": "2", "body": "bar" }
  ],
  "comments": [
    { "id": "1", "body": "baz", "postId": "1" },
    { "id": "2", "body": "qux", "postId": "2" }
  ]
}
```

If you visit /posts it works, but if you try to get /posts/1 you get no results.
Sometimes it is useful having string identifiers or when you have to simulate an existing environment.

Does it make sense for you? Is there a workaround for this?

**Comment by alansutherland** [comment]
I seem to be having the reverse problem, when I POST comments to the db the api generates postId as a string. The id generated is an integer. The comment doesn't show on the post since it's a string

```
{
    "user": "Albert",
    "content": "I agree entirely",
    "date": "2016-03-18",
    "postId": "3",
    "id": 9
}
```
