### ISSUE TITLE
Multi-level resources with static JSON file

### ISSUE THREAD

**Issue by cuongluu8** [typicode/json-server#242]
I want to create the following endpoints

/items/:userId/ -> returns all items for a given user
/items/:userId/item/:itemId -> returns a single item for the user if it exists

How would the static data in the JSON file look like if it is possible?  I couldn't figure out if something like this is possible from the README.

I want to avoid using a module - as it would mean refactoring a lot of existing code.

**Comment by SanjeetSodhi** [comment]
You can access items for the user by id through a [filter](https://github.com/typicode/json-server#filter).

```json
{
  "users": [
    {
      "id": 1,
      "name": "Sir John Franklin"
    }
  ],
  "items": [
    {
      "id": 1,
      "userId": 1,
      "ship": "HMS Erebus"
    },
    {
      "id": 2,
      "userId": 1,
      "ship": "HMS Terror"
    }
  ]
}
```

`/users/1/items/1` yields a 404 error but `/users/1/items/?id=2` yields:
```json
[
  {
    "id": 2,
    "userId": 1,
    "ship": "HMS Terror"
  }
]
```

So you can apply the advice in https://github.com/typicode/json-server/issues/72 and use a filter to achieve the same result as you might expect from `/items/:userId/item/:itemId` (albeit enclosed in an array)

**Comment by Isanderthul** [comment]
Hi @cuongluu8 are you happy with this answer? Can you close the ticket?

**Comment by mytharcher** [comment]
And how about this? I want to visit `/user/1/data`, but only got empty object `{}`.

~~~
{
  user: [
    {
      id: 1,
      data: [/*...lots of data item...*/]
  ]
}
~~~

**Comment by mytharcher** [comment]
Ok, I found the right way for `/user/1/data` like this:

~~~
{
  user: [
    {id: 1}
  ],
  data: [/*...lots of data item...*/]
}
~~~
