### ISSUE TITLE
Support for HTTPS

### ISSUE THREAD

**Issue by juergenzimmermann** [typicode/json-server#244]
It would be nice, if json-server could support HTTPS. Then prototyping via json-server would even more realistic.

**Comment by Karankang007** [comment]
+1

**Comment by managedkaos** [comment]
-1 Can't you put your json-server behind an Apache or Nginx with a cert installed and proxy to it?  That's also a realistic scenario.  I think adding traffic encryption/decryption and SSL cert handling would be nice but would also be well past the scope of the original project.

**Comment by Karankang007** [comment]
Thanks @managedkaos, I created an IIS reverse proxy rule to do this.

**Comment by managedkaos** [comment]
Awesome! :D

**Comment by typicode** [comment]
As a simpler alternative to setting up an Apache or Nginx server, you can give a try to [hotel](https://github.com/typicode/hotel):

```sh
my-project $ hotel add 'json-server db.json'
# https://my-project.dev
```

**Comment by nilocoelhojunior** [comment]
@Karankang007 How can I do this? any article?

**Comment by nishantshreshth** [comment]
**This works:**

```
var fs = require('fs'),
  https = require('https'),
  jsonServer = require('json-server'),
  server = jsonServer.create(),
  router = jsonServer.router('db.json'),
  middlewares = jsonServer.defaults();

var options = {
  key: fs.readFileSync('./ssl/key.pem'),
  cert: fs.readFileSync('./ssl/cert.pem')
};

server.use(middlewares);
server.use(router);

https.createServer(options, server).listen(3002, function() {
  console.log("json-server started on port " + 3002);
});
```

You can use `openssl req -x509 -newkey rsa:2048 -keyout key.pem -out cert.pem -days 120 -nodes` to generate self-signed certificate and private key.

**Comment by Gribbs** [comment]
@nishantshreshth thank you indeed!

**Comment by typicode** [comment]
Thanks @nishantshreshth for sharing this solution :) 
Thanks @abhatia1176 for the nice comment, glad you like it :)

**Comment by idgserpro** [comment]
@abhatia1176 somehow your link is _mangled_ in https://github.com/typicode/json-server/issues/244#issuecomment-396508227, you have to copy it and paste it instead of clicking on it.

**Comment by xeoshow** [comment]
Hello,
I am new to json-server, anyone could please kindly tell how to use below? Great thanks!
 
> **This works:**
> 
> ```
> var fs = require('fs'),
>   https = require('https'),
>   jsonServer = require('json-server'),
>   server = jsonServer.create(),
>   router = jsonServer.router('db.json'),
>   middlewares = jsonServer.defaults();
> 
> var options = {
>   key: fs.readFileSync('./ssl/key.pem'),
>   cert: fs.readFileSync('./ssl/cert.pem')
> };
> 
> server.use(middlewares);
> server.use(router);
> 
> https.createServer(options, server).listen(3002, function() {
>   console.log("json-server started on port " + 3002);
> });
> ```
> You can use `openssl req -x509 -newkey rsa:2048 -keyout key.pem -out cert.pem -days 120 -nodes` to generate self-signed certificate and private key.

**Comment by balaji-b-v** [comment]
@nishantshreshth thank you very much

**Comment by nroutledge** [comment]
> **This works:**
> 
> ```
> var fs = require('fs'),
>   https = require('https'),
>   jsonServer = require('json-server'),
>   server = jsonServer.create(),
>   router = jsonServer.router('db.json'),
>   middlewares = jsonServer.defaults();
> 
> var options = {
>   key: fs.readFileSync('./ssl/key.pem'),
>   cert: fs.readFileSync('./ssl/cert.pem')
> };
> 
> server.use(middlewares);
> server.use(router);
> 
> https.createServer(options, server).listen(3002, function() {
>   console.log("json-server started on port " + 3002);
> });
> ```
> 
> You can use `openssl req -x509 -newkey rsa:2048 -keyout key.pem -out cert.pem -days 120 -nodes` to generate self-signed certificate and private key.

Kudos to you. This is a great little solution.
