### ISSUE TITLE
Service is not offering access to db file

### ISSUE THREAD

**Issue by GeneArnold** [typicode/json-server#250]
Running this on a Mac 10.10.5
With server running I can see the service via a web page. Page only offers a link to db and not any nodes inside the document. I can not query the document. Not getting any errors. Running as sudo but could there still be security issues?

**Comment by GeneArnold** [comment]
I very sorry, please excuse this issue. I was not correctly assigning the path the to JSON file in terminal when launching the server. Completely user error.

**Comment by typicode** [comment]
No worries :) glad it works now :+1:
