### ISSUE TITLE
Listen server with node [Problem]

### ISSUE THREAD

**Issue by radames-sa** [typicode/json-server#251]
I can not start my script using "node".
Ex.: $ node index.js

//index.js
var jsonServer = require('json-server');

var server = jsonServer.create(); // Returns an Express server
var router = jsonServer.router('db.json'); // Returns an Express router

server.use(jsonServer.defaults); // logger, static and cors middlewares
server.use(router); // Mount router on '/'
server.listen(3000);

Is carrying endlessly without any response. I tested on OSX and Ubuntu system. What might be happening? Thank you

**Comment by typicode** [comment]
Simply change this line and you should be good:

```js
server.use(jsonServer.defaults()); // Add () to .defaults
```

`defaults()` is a function that returns middlewares.
