### ISSUE TITLE
Noob question : Is post working properly?

### ISSUE THREAD

**Issue by asantaga** [typicode/json-server#252]
Hi there,

Im trying to post data to Json-Server but when I query the data Im finding no data is being persisted and I only get a collection of IDs... thinking its something simple, what did I miss?

db.json
{
  "transactions": [ ]
}

POST /transactions
{
  "item": "Coffee",
  "amount": 2.1,
  "points": 210
}
response 201 and
{
  "id": 1
}

GET /transactions/1 gives 
{
  "id": 1
}

**Comment by typicode** [comment]
Yes, this error usually means that the `Content-Type` is not set to `application/json`.

**Comment by asantaga** [comment]
Damm too obvious when u think of it.. Is this a minor bug ?(ie it should only accept application/json) but not worried. its documented here for other newbies like me :-)

Thanks!! and awesome

**Comment by typicode** [comment]
You're welcome :)
BTW I'm curious, what was the content-type sent? What were you using for the POST?

**Comment by asantaga** [comment]
I was  using postman. I simply modified a previous request and the content type  got accidentally accidentally copied.   Content-type application/vnd.oracle.adf.resourceitem+json was being sent, as soon as I changed it to application/json it worked fab

**Comment by typicode** [comment]
Thanks for the feedback.
