### ISSUE TITLE
Problems with chunked transfer-encoding and compression

### ISSUE THREAD

**Issue by ciscoheat** [typicode/json-server#254]
I suddenly got `net::ERR_INCOMPLETE_CHUNKED_ENCODING` in Chrome on a fairly long request, probably long enough to be chunked. But the response was cut off in the middle. (Same in Firefox, but it didn't report any problem, just served incomplete json.) 

Eventually I figured out that by commenting out the compression middleware in `defaults.js`, it started to work again. Is this a known problem?

**Comment by typicode** [comment]
Hi @ciscoheat,

Thanks for reporting. Not that I'm aware of but there seem to be an old issue related here https://github.com/expressjs/compression/issues/14

How can it be reproduced?

**Comment by ciscoheat** [comment]
No problem, glad to help this nice project! Unfortunately the data is sensitive, but the structure is like this:

```json
{
  "namespace.otherData": [
    { ... }
  ],
  "namespace.name": [
    { ... }
  ]
}
```

otherData is about 1,8 MB, name is about 1,8 MB. When I GET `/namespace.name` from json-server, I get the error.

**Comment by typicode** [comment]
@ciscoheat Thank you for the data :) it will help reproducing the issue.

Thanks to @netzzwerg's PR, it's now possible to toggle `gzip` compression from the CLI, simply add `--no-gzip`.

**Comment by ciscoheat** [comment]
No problem, let me know if you need anything else. :) The gzip switch works for me for now, so thanks!

**Comment by Paveltarno** [comment]
+1 Happens to me too

**Comment by rammygit** [comment]
Looks like this Gzip switch works, so why is this issue open still ?

**Comment by ciscoheat** [comment]
Closing time!
