### ISSUE TITLE
Add option to disable cache

### ISSUE THREAD

**Issue by gearlles** [typicode/json-server#258]
I'm using the following js file:

```javascript
// index.js
module.exports = function() {
  var data = { users: [] }
  // Create 1000 users
  for (var i = 0; i < 1000; i++) {
    data.users.push({ id: i, name: 'user' + Math.random()  })
  }
  return data
}
```
I expect from `Math.random()` to generate different user names beteween requests. However, `json- server` seems to cache requests and always returns the same data:

```
GET /users 200 45.730 ms - -
GET /users 304 39.357 ms - -
GET /users 304 41.578 ms - -
GET /users 304 13.639 ms - -
GET /users 304 17.930 ms - -
```

Note the `HTTP 304 Not modified` after the first request.

**Comment by typicode** [comment]
Actually, it's the expected behavior.
`index.js` should only be run once by `json-server`, or else `POST`, `PUT` and `PATCH` won't change data if it's regenerated between requests.

What about disabling `cache` from the browser's DevTools? Let me know if it helps or if your use-case is more complex than that.

**Comment by gearlles** [comment]
My use-case is: I'm mocking a server api that returns the number of users online. To be to automatically update the chart in my client application, json-server needs to return different number of users online between different requests. For example:

```
// first request
GET /online 200
{
  "users": 1219
}
```
```
// second request
GET /online 200
{
  "users": 1381
}
```
Initially I thought it was a cache problem, but you clarified that it's a json-server limitation. There's noting we can do in the current version, right?

**Comment by typicode** [comment]
If you use the project as a module, you can extend/modify its behavior.

For example, a simple version could be:

```js
var jsonServer = require('json-server')

var server = jsonServer.create()
var router = jsonServer.router('db.json')

server.use(jsonServer.defaults())

server.get('/online', (req, res) => {
  res.jsonp({ users: Math.floor(Math.random() * 1000) })
})

server.use(router)

server.listen(3000)
```

If you want something more dynamic:

```js
var jsonServer = require('json-server')

var server = jsonServer.create()
var router = jsonServer.router('db.json')
var db = router.db

server.use(jsonServer.defaults())

// Reset users between requests
server.use((req, res, next) => {
  db.object.users = []
  for (var i = 0; i < 1000; i++) {
    db.object.users.push({ id: i, name: 'user' + Math.random() })
  }
})

// Count users in the database
server.get('/online', (req, res) => {
  res.jsonp({ users: db.object.users.length })
})

server.use(router)

server.listen(3000)
```

Basically, what's important to remember is that `json-server` is built on Express. So whenever you feel limited, you can extend it using Express middlewares.

**Comment by gearlles** [comment]
Works as expected. Thank you!

**Comment by typicode** [comment]
Great :)
You're welcome

**Comment by vivekKodira** [comment]
A note for anyone visiting this issue today. 

The workaround mentioned above will not work anymore since json-server now doesn't seem to expose the `db` object directly. Instead, I had to do the following:

```
  const db = router.db.getState();
 //update db
  router.db.setState(db);
```

**Comment by MickL** [comment]
My data is also generated randomly, so I reset the database regularly:

```
setInterval(() => {
  // Reset every 10min
  router.db.setState(db);
}, 10 * 60 * 1000);
```
