### ISSUE TITLE
Add option to remove array

### ISSUE THREAD

**Issue by Isanderthul** [typicode/json-server#259]
I have my db.json
`{
  "getUsers": [
    {
      "Users": [
        {
          "Name": "Admin",
          "UserId": "1"
        },
        {
          "Name": "sandy",
          "UserId": "2"
        }
      ]
    }
  ]
}`

when accessing http://localhost:3000/getUsers returns the array 
`[
  {
    "Users": [
      {
        "Name": "Admin",
        "UserId": "1"
      },
      {
        "Name": "sandy",
        "UserId": "2"
      }
    ]
  }
]`

it would be very useful if the initial array could be removed, and the response was just 
`
{
    "Users": [
      {
        "Name": "Admin",
        "UserId": "1"
      },
      {
        "Name": "sandy",
        "UserId": "2"
      }
    ]
  }
`

I am in this situation trying to emulate a customers API.

**Comment by typicode** [comment]
You can modify the output using the project as a module and `router.render`.

https://github.com/typicode/json-server#module

```js
// ...

router.render = function (req, res) {
  if (req.url === '/getUsers') {
    res.locals.data = res.locals.data[0] // "extracts" first item
  }
  res.jsonp({
    body: res.locals.data
  })
}
```

**Comment by Isanderthul** [comment]
thank you!
