### ISSUE TITLE
No response when trying to use as a module

### ISSUE THREAD

**Issue by ericj17** [typicode/json-server#261]
Hi there, I am trying to use json-server as a module with a server.js with the following content
```
var jsonServer = require('json-server')
var data = require("./generate.js");

var server = jsonServer.create();
var router = jsonServer.router(data());


server.use(jsonServer.defaults);
server.use(router);

router.render = function (req, res) {
  res.jsonp({
    data: res.locals.data
  })
};

server.listen(3000);
```

with the command line **node server.js** (json-server is installed globally)

It seems json-server is running, but when I try to access localhost:3000 it seems to be "waiting" indefinitely. Do you have any recommendations on how to troubleshoot?

it works when calling json-server directly from command line

Thanks,
Eric

**Comment by typicode** [comment]
Hi Eric,

SImply change `jsonServer.defaults` to `jsonServer.defaults()` and you should be good :)

**Comment by ericj17** [comment]
Oh dear, thanks for catching that :D
