### ISSUE TITLE
json-server restarting for every possible get request

### ISSUE THREAD

**Issue by gopalakrishnan-subramani** [typicode/json-server#263]
Found strange behavior with latest json-server, express js module, the server was restarting, failed to serve client requests, possibly due to frequent change in db.json file during get requests.

Confirmed the same behavior with json-server installed globally with npm install json-server & running "json-server --watch db.json"

Looks like get requests json-server router changing the time-stamp of the file, making an appearance like file modified or it may be due to watch process error.

**Comment by sant123** [comment]
@gopalakrishnan-subramani, in previous versions of json-server was happening that. I had the same issue with v0.8.13. The v0.8.14 solves the problem.

**Comment by typicode** [comment]
I've updated the way `--watch` work in `v0.8.15`. It should be better, let me know if you still encounter this issue.
