### ISSUE TITLE
installation warning

### ISSUE THREAD

**Issue by johndeighan** [typicode/json-server#268]
Installing version 3.4.1 gives the following warning:

npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.

**Comment by typicode** [comment]
Thank you for the heads up :) I hope to fix it by the end of the week.
That said, it's just a warning and doesn't prevent json-server from working.

**Comment by typicode** [comment]
Fixed in `v0.8.12`
