### ISSUE TITLE
Hangs at exit, holds port open

### ISSUE THREAD

**Issue by sgbeal** [typicode/json-server#269]
Hiho,

Platform: Windows10 (not my decision!) with Git Bash running as Administrator due to limitations of npm (it creates symlinks, which only the admin user can do on this godforsaken excuse for as OS):

    $ npm run-script json-server
    > nms-gui@0.0.0 json-server D:\src\<elided>\x-gui
    > json-server -c json-server/json-server.json json-server/db.json
    Loading json-server/db.json
    ...
    Resources
    http://localhost:4300/posts
    http://localhost:4300/comments
    http://localhost:4300/profile
    ...
    Home
    http://localhost:4300
    ....
    Type s + enter at any time to create a snapshot of the database
    Watching...

serving works great.

json-server.json:

    {
    "port": 4300,
    "static": "dist",
    "snapshots": "json-server",
    "no-cors": true,
    "watch": true
    }

ctrl-c causes it to hang forever, requiring closing of the terminal. This unfortunately leaves the port open, though, so it cannot be started on the same port again. It _eventually_ lets go of the port, but i can't say how long that takes.

i.e. it seems impossible to close it properly.

**Comment by sgbeal** [comment]
**Nevermind:** this appears to be a node and/or npm problem, as 'ng' (angular-cli) is now doing the same thing. (Hmmm... it wasn't 2 days ago... but that's my problem, not yours.)

**Comment by sgbeal** [comment]
follow-up: reboot fixed it. Surprise, surprise.

**Comment by celineWong7** [comment]
I also meet it! i should restart my computer, then it can run  on the port  pre-set.
