### ISSUE TITLE
Post is not updating but adding the data in json

### ISSUE THREAD

**Issue by Sujeet1604** [typicode/json-server#270]
Json-server is what I was looking for. Perfect companion of a Front-End developer.

Issue :
I am using POST to update a particular json in db.json . After a while it stop updating and start adding the contents in json array. Donno the reason. Please help.

**Comment by typicode** [comment]
Hi @Sujeet1604,

Thank you :)

If you want to update a resource, you should use `PUT`.
`POST` is used to create resources.

You can find an example here:
https://github.com/typicode/jsonplaceholder#updating-a-resource (JSONPlaceholder is a live running JSON Server)
