### ISSUE TITLE
How can I use JSON API links, meta, or data in db.json with EmberJS front-end

### ISSUE THREAD

**Issue by lrsnider** [typicode/json-server#275]
How would I incorporate these aspects of the JSON api spec to get them to return from this mock back-end with an Ember JS front-end?

http://jsonapi.org/format/#document-resource-object-relationships

**Comment by typicode** [comment]
Hi @lrsnider,

Unfortunately, JSON Server doesn't support JSON API. You can make the responses look like JSON API up to some extent though. But for anything complex or specific to JSON API, I don't think it will be easy to make it work.

Here's an example how to tweak JSON Server, but it's limited. You could hard-code some of the missing attributes maybe.

```js
var jsonServer = require('json-server')
var server = jsonServer.create()
var router = jsonServer.router('db.json')
var middlewares = jsonServer.defaults()

server.use(middlewares)
server.use(router)

function convert(item) {
  var id = item.id
  delete item
  return {
    id: id
    attributes: { item }
  }
}

// Will transform
// { id: ..., title: ... } to { id: ..., attributes: { title: ... } }
// [ { id: ..., title: ... } ] to { data: [ ... ] }
router.render = function (req, res) {
  var data = res.locals.data
  
  if (Array.isArray(data)) {
    res.jsonp({
      data: data.map(convert))
    })
  } else {
    res.jsonp(convert(data))
  }
}

server.listen(3000, function () {
  console.log('JSON Server is running')
})
```

Alternatively, I would suggest having a look at http://www.ember-cli-mirage.com/ or http://fortunejs.com/

**Comment by mblackritter** [comment]
In case others also still finding this on a search.

For *the* [JSON:API](http://jsonapi.org), I found [Thomas-X/jsonapi-mock](https://github.com/Thomas-X/jsonapi-mock) (which is inspired by json-server) and [holidayextras/jsonapi-server](https://github.com/holidayextras/jsonapi-server) useful, where the latter can be a whole server, but if you look at the [example](https://github.com/holidayextras/jsonapi-server/tree/master/example), you'll find that it can also serve static data, where you can also quite easily implement Faker.
