### ISSUE TITLE
how to allow many people using one db json?

### ISSUE THREAD

**Issue by lzyy** [typicode/json-server#280]
background:

there are more than 10 persons in our team, in case we want to use `json-server` to mock server response in one db json, how to do?

my attempt:

1. create server `json-server --watch db.json`
2. update db.json with `username` prefix like this

```javascript
{  
    jack:{  
        posts:[  
            {  
                id:1,
                title:"json-server",
                author:"typicode"
            }
        ],
        comments:[  
            {  
                id:1,
                body:"some comment",
                postId:1
            }
        ],
        profile:{  
            name:"typicode"
        }
    }
}
```

but when I visit `http://ip:port/jack/posts/1` it returns empty object `{}`

is there a workable way to handle this?

**Comment by typicode** [comment]
Hi,

If you want to add a prefix, you need to use `routes` for that. By default, json-server doesn't support routes like `GET /prefix/resources`.

https://github.com/typicode/json-server#add-routes

`routes.json` (will rewrite `/jack/*` to `/*`)

```json
{
  "/jack/": "/"
}
```

`db.json`

```json
{  
        "posts":[  
            {  
                "id":1,
                "title":"json-server",
                "author":"typicode"
            }
        ],
        "comments":[  
            {  
                "id":1,
                "body":"some comment",
                "postId":1
            }
        ],
        "profile":{  
            "name":"typicode"
        }
    }
```

```sh
$ json-server --watch db.json --routes routes.json
```

This will make `/posts` resources __also__ available under `/jack/`.

Not sure if you're asking for this as well, but just in case, if you're working with a team and want to share `db.json`, you have several options for this.

__Use Dropbox__

Create `db.json` in a Dropbox folder and add your team members to it. Then each one can run:

```sh
$ json-server --watch ~/Dropbox/shared_folder/db.json
```

You may want to set `--read-only` to avoid problems with people modifying the same file at the same time.

__Use GitHub__

Publish `db.json` to a repository and load it:

```sh
$ json-server https://raw.githubusercontent.com/team/project/master/db.json
```

Or simply load the local file after cloning the repo.

__Have a server dedicated for this somewhere__

And access it using, as you suggested, `http://ip:port/...`

I think the GitHub approach is the best for a team.

**Comment by lzyy** [comment]
@typicode Thanks for your detail reply! modify one db.json using VCS seems the solution.
