### ISSUE TITLE
Additional info related to routes.json

### ISSUE THREAD

**Issue by lioralt** [typicode/json-server#283]
Hi,
I'm new to the json-server project and I'm trying to set up the routes.json file but finding it hard, is it possible to get some help with it ? (hope it's the right place to ask)

this is the data i'm using:

```
{
  "posts": [
    { "id": 1, "title": "json-server1", "author": "typicode" },
	{ "id": 2, "title": "json-server2", "author": "typicode" },
	{ "id": 3, "title": "json-server3", "author": "typicode" }
  ],
  "comments": [
    { "id": 1, "body": "some comment1", "postId": 1 },
	{ "id": 2, "body": "some comment2", "postId": 1 },
	{ "id": 3, "body": "some comment3", "postId": 2 },
	{ "id": 4, "body": "some comment4", "postId": 3 }
  ],
  "morecomments": [
    { "id": 1, "body": "some more comment1", "commentId": 1 },
	{ "id": 2, "body": "some more comment2", "commentId": 1 },
	{ "id": 3, "body": "some more comment3", "commentId": 3 },
	{ "id": 4, "body": "some more comment4", "commentId": 4 }
  ],
  "profile": { "name": "typicode" }
}
```

how should the routes.json file be set up in this case ?

Thanks a lot.

**Comment by typicode** [comment]
Hi @lioralt ,

Yes, it's the right place :) everything seems fine in your `db.json`.

Actually, you need to pass `routes.json` only if you need to add custom routes.
For example, if you're not satisfied with the default route `GET /posts`, you can add a `routes.json`:

`routes.json`

```json
{
  "/api/": "/"
}
```

That will make `/posts` available also under `/api/posts`, as well as `/api/comments`, `/api/profile`, ...

Or you can say, I want `/my/awesome/post` to redirect to a specific post, for example `/posts/1`:

`routes.json`

```json
{
  "/my/awesome/post": "/posts/1"
}
```

But once again, if you're fine with the default routes (which are described [here](https://github.com/typicode/json-server#routes)), you don't need to worry about `routes.json`.

**Comment by lioralt** [comment]
Thanks for the super fast reply.

The thing is that i want to use nested resources and i saw that the default routes support only one level...
for exampl, something like:
`/posts/1/comments/1/morecomments`

How should my routes.json file should be in the case mantioned above ?

**Comment by typicode** [comment]
You can have named params `:param`:

```json
{
  "/posts/:postId/comments/:commentId/moreComments": "/comments/:commentId/moreComments"
}
```

**Comment by lioralt** [comment]
Thanks @typicode , i appreciate the help.

**Comment by typicode** [comment]
You're welcome.
