### ISSUE TITLE
Run json-server as teamcity build step

### ISSUE THREAD

**Issue by bondarewicz** [typicode/json-server#284]
More of a question rather than issue... have anyone tried to use json-server as part of their CI process?

I'm trying to run it locally within CI agent but cannot see how can I inform teamcity to continue to next build step (throw exit code 0 and do not show below welcome message) as currently it just sits there ...

```
  \{^_^}/ hi!

  Loading db.json
  Done

  Resources
  http://localhost:3004/posts

  Home
  http://localhost:3004

  Type s + enter at any time to create a snapshot of the database
```

**Comment by typicode** [comment]
It depends on what you want to do, what you need json-server for.

You may want to include the project as a module in your tests, so that when they end, json-server is stopped as well.

```js
var jsonServer = require('json-server')
var server = jsonServer.create()
var router = jsonServer.router('db.json')
var middlewares = jsonServer.defaults()

server.use(middlewares)
server.use(router)
server.listen(3000, function () {
  console.log('JSON Server is running')
  // start tests
  // process.exit(0)
})
```

You could also spawn `./node_modules/.bin/json-server` using `child_process` API and kill it when you don't need it anymore.

You can add `--quiet` to suppress output (but it you spawn it, you can simply set no output).

**Comment by bondarewicz** [comment]
thanks @typicode, I found that my approach was perhaps wrong as I've tried to run json-server on separate build step and invoke the tests on the other... now both are merged and issue is gone

**Comment by redaxmedia** [comment]
There might be another approach using the middleware using a `exit` endpoint that will call `process.exit` ... I think this should be a core feature of json-server.

**Comment by alphaofficial** [comment]
> thanks @typicode, I found that my approach was perhaps wrong as I've tried to run json-server on separate build step and invoke the tests on the other... now both are merged and issue is gone

how did you manage to solve this @bondarewicz ?

**Comment by sethburtonhall** [comment]
I am trying to figure this out as well ... start and run the json-server in parallel to the build step, then shut it down after build.
