### ISSUE TITLE
Cant get PATCH to work

### ISSUE THREAD

**Issue by farzd** [typicode/json-server#285]
I cant get PATCH to work, used fetch and POSTMAN/CURL
i get 404 when i try PATCH with a request http://localhost:3000/users?id=2345
with body of data that needs to change?

this seems to work  http://localhost:3000/users/1 with same payload, i get a 200 but file doesnt change?

**Comment by typicode** [comment]
Hi,

There was an issue with `v0.8.11-13` preventing changes to be saved to file. `v0.8.14` fixes this.
`PATCH` works only with routes like `/:resources/:id`.

**Comment by jessycormier** [comment]
I'm having the same issue happen on v0.9.5
