### ISSUE TITLE
Record not saved in the db json file

### ISSUE THREAD

**Issue by pameck** [typicode/json-server#290]
I'm making a POST (Content-Type set to application/json) 
Everything seems to work fine: 
- I get a 201 back
- a GET request gets me all the data including the record recently created.
- If a create a snapshot of the db, it includes the new record
- if I go to /db I get the DB up to date. 

The problem is the new record is not saved in the main db.json file.

Version:
"json-server": "^0.8.13"

This is how I start the server: 
json-server app/some-db.json --watch --static ./public

**Comment by pameck** [comment]
Changed to the last stable version to 0.8.10 (12 and 11 were failing to start), and that fixed the issue. 
I suppose there is something odd with version 0.8.13.

**Comment by typicode** [comment]
@pameck thanks for the report :+1:  I've deprecated them and released a fix in `v0.8.14`.
I've also added a test for this specific case.

Let me know if you have other issues with this release.
