### ISSUE TITLE
How to set defaults options as module?

### ISSUE THREAD

**Issue by PhoonLee** [typicode/json-server#291]
```
var jsonServer = require('json-server')
var server = jsonServer.create()
var router = jsonServer.router('db.json')
var middlewares = jsonServer.defaults()
server.use(middlewares)
```
I try to set static directory,it did not work. :(
```
var middlewares = jsonServer.defaults({static:'./app'})
```

**Comment by pratikgala** [comment]
@PhoonLee were you able to figure out to log the static files?.

**Comment by piku0709** [comment]
I wanted to use something like this 
var jsonServer = require('json-server')
var server = jsonServer.create()
var router = jsonServer.router('db.json')
var middlewares = jsonServer.defaults({quiet: true});
server.use(middlewares)

it is also not working, I want to stop logs on the output window

**Comment by andriy101** [comment]
Based on the [documentation](https://www.npmjs.com/package/json-server#simple-example):

_The path you provide to the jsonServer.router function is relative to the directory from where you launch your node process. If you run the above code from another directory, it’s better to use an absolute path:_

```
const path = require('path')
const router = jsonServer.router(path.join(__dirname, 'db.json'))
```

so try:

```
const path = require('path');
const router = jsonServer.defaults({
  static: path.join(__dirname, './app')
});
```
