### ISSUE TITLE
application/x-www-form-urlencoded query bodies

### ISSUE THREAD

**Issue by michaeljpeake** [typicode/json-server#307]
I could not work out why json-server could not read the data on my post requests. Whenever I logged `req.body`, it returned `undefined`.

It took me a while but I discovered that there is no native support for `application/x-www-form-urlencoded` in express anymore.

The fix was easy:

    var bodyParser = require('body-parser');
    server.use(bodyParser.urlencoded({ extended: false }));

I feel that this could/should be noted on README.md.

**Comment by typicode** [comment]
@michaeljpeake should be good in `v0.8.16`, thank you :)

**Comment by michaeljpeake** [comment]
@typicode Great. Thanks.

**Comment by asoneji** [comment]
I am using `"json-server": "^0.10.1"` and I still see `req.body`, it returned `undefined`.
```
const jsonServer = require('json-server');
const path = require('path');
const fs = require('fs');
const program = require("commander-plus");

const PORT = 3004;
const DB = "db.json";

const fileServerRoot = path.join(__dirname, './public');
const server = jsonServer.create()
const dbPath = path.join(__dirname, DB);
fs.writeFileSync(dbPath, '{"posts": []}');

const router = jsonServer.router(dbPath)
const middlewares = jsonServer.defaults({static: fileServerRoot})

server.use((req, res, next) => {
    console.log(req.body);
    next()
})

server.use(middlewares)
server.use(router)
server.listen(PORT, () => {
  console.log('JSON Server is running')
})
```
Output is:
```
JSON Server is running
undefined
```

**Comment by asoneji** [comment]
I had to add 

`server.use(jsonServer.bodyParser)`

and now it works.
