### ISSUE TITLE
Custom query string for list is always removed.

### ISSUE THREAD

**Issue by turboza** [typicode/json-server#311]
I am trying to do custom pagination according to the real server spec, so I need to get query string from request to transform the response in router.render like this.

GET `/posts?limit=10&offset=20`

```
router.render = function (req, res) {
  console.log(req.query); // got empty object {} ???
  res.json({
     data: res.locals.data.slice(req.query.offset, req.query.offset + req.query.limit),
  });
}
```

Unfortunately, json-server removes all query that is not in the scope. So I cannot use query `limit` and `offset`. How can I make it work?

**Comment by ahmadalfy** [comment]
I was able to access query strings using `req._parsedOriginalUrl.query`

**Comment by ahmadalfy** [comment]
Just an additional note, you will need to convert the query string to a number.

**Comment by turboza** [comment]
@ahmadalfy Oh nice, I can finally access the custom query although they are just a raw string not an object. Thanks a lot. 😄
