### ISSUE TITLE
the json-server can't reload the json file automatic

### ISSUE THREAD

**Issue by Pines-Cheng** [typicode/json-server#315]
just like the title upon,I run the json-server with the command of `json-server --watch db.json`,after that ,I modify the file of db.json and add some new data,
but unfortunately I find the I can't load the new data unless I shut down the json-server and restart ,It's really not convenient .Does someone has the solution?

**Comment by typicode** [comment]
Hi @Pines-Cheng,
Thank you for the report :) working on it.

**Comment by typicode** [comment]
Should be good now in `v0.8.15`

**Comment by Pines-Cheng** [comment]
Thanks，you are so awesome.
