### ISSUE TITLE
3 parameters request

### ISSUE THREAD

**Issue by jaroslawziolkowski** [typicode/json-server#318]
When I try use 3 url parameters it doesn't work.

```
"project/3/invoices": [
        {"id": 344, "invoice_number": 424, "User": {"id": 43, "first_name": "Chris", "last_name": "Gallop"},
            "Client": {"User": {"id": 44, "first_name": "Foo", "last_name": "Bar"}},
            "Project": {"full_code": "ddsds-98"},
            "Company": {"name": "Umb"},
            "SalesManager": {"id": 41, "first_name": "Foo2", "last_name": "Bar2"},
            "invoice_date": "2016-05-12 00:00:00",
            "subtotal_amount": 1000.00,
            "total_gst": 220.00,
            "total_discounts": 0.00,
            "due_amount": "2016-05-22 00:00:00",
            "payment_terms": "NET10",
            "status": "DRAFT",
            "statuses": {"DRAFT": "Invoice draft"},
            "terms": {"NET10": "Net 10"}
        }
    ]
```

or 

"project//invoices/get": [
        {"id": 344, "invoice_number": 424, "User": {"id": 43, "first_name": "Chris", "last_name": "Gallop"},
            "Client": {"User": {"id": 44, "first_name": "Foo", "last_name": "Bar"}},
            "Project": {"full_code": "ddsds-98"},
            "Company": {"name": "Umb"},
            "SalesManager": {"id": 41, "first_name": "Foo2", "last_name": "Bar2"},
            "invoice_date": "2016-05-12 00:00:00",
            "subtotal_amount": 1000.00,
            "total_gst": 220.00,
            "total_discounts": 0.00,
            "due_amount": "2016-05-22 00:00:00",
            "payment_terms": "NET10",
            "status": "DRAFT",
            "statuses": {"DRAFT": "Invoice draft"},
            "terms": {"NET10": "Net 10"}
        }
    ]

```
is visible in index but after click on link I receive 404 error in terminal and empty result.

```

**Comment by ocjojo** [comment]
@jaroslawziolkowski I believe this is a restriction due to how json-server handles nested routes.
They are remapped internally so `/project/3/invoices` is remapped to `/invoices` with a queryParam of projectId = 3
