### ISSUE TITLE
Is there a way to simulate errors

### ISSUE THREAD

**Issue by naartjie** [typicode/json-server#331]
I am looking for a way to simulate errors - it would be nice to be able to also return `400` and `500` status codes.

Is there a way to currently do this?

**Comment by felippenardi** [comment]
@naartjie You could look to intercept the requests that match certain criteria and return a customized response. There are examples on the README on intercepting and creating custom request handling.

**Comment by naartjie** [comment]
Thanks @felippenardi

**Comment by juanbrujo** [comment]
This was my solution: https://gist.github.com/juanbrujo/efdcf6ab9eacbd5b5d69884233d0a3ce

**Comment by gretchencasey** [comment]
Yes, you can simulate errors and return specific status codes (like 400 and 500) using various methods depending on the technology stack you are using. Here are a few common approaches for different environments:
In a Web Application (e.g., using Express.js in Node.js)

If you are using Express.js, you can simulate errors and return different status codes
These examples should help you simulate different error responses and return specific status codes in your application.
Also thank you @[srdsassastatuscheck](https://srdsassastatuscheck350.co.za/) for the help.
