### ISSUE TITLE
Is it possible to upload file (post request)?

### ISSUE THREAD

**Issue by rustanacexd** [typicode/json-server#336]
Is it possible to upload file (post request)?

**Comment by typicode** [comment]
Hi,

Sorry, it's not included in the project, but you can use JSON Server as a module and add some other express middlewares to handle file upload.

**Comment by zakuro9715** [comment]
Hi @rustanacexd.

It's maybe possible. Create middlewares to upload file and use it with -m option.

NOTE: -m option is not released yet.

**Comment by rustanacexd** [comment]
@typicode @zakuro9715 thank you for the response!
