### ISSUE TITLE
Is it possible to set default values on insert?

### ISSUE THREAD

**Issue by tsm91** [typicode/json-server#339]
Hello @typicode,

lets says i have a `Todo` entity, which looks like this:

```
interface Todo = {
  id: number;
  title: string;
  completed: boolean = false;
}
```

By default all newly inserted `Todo` would be un-completed. This is a typical atomic operation that needs to be done on the server. Which means i won't send this `completed` value over the wire with a `POST` request.

I found the [create](https://github.com/typicode/json-server/blob/master/src/server/router/plural.js#L210-L222) method which is responsible for pushing the contents of `req.body` to the end of the given collection.

Somehow you need to specify a default value, but for that you need a schema.

I wonder how would you solve something like this?

Right now i solve this with a middleware, but it would be awesome to specify default values by design.

```js
export function todosMiddleware(db) {
  return (req, res, next) => {
    const isTodosRoute = req.path.indexOf('todos');

    if (req.method === 'POST' && isTodosRoute) {
      // add default values
      Object.assign(req.body, {
        completed: false,
        userId: _.random(0, 9)
      });
    }

    next();
  };
}
```

cc @jpbochi

**Comment by jpbochi** [comment]
since you copied me here, I assume you looked at https://github.com/typicode/json-server/pull/322

One way is by adding a middleware that rewrites the request adding `completed = false`. Something like this.

```
server.use('/todo', function (req, res, next) {
   if (req.method === 'POST') {
     req.body.completed = false;
   }
   next();
})
```

Now, to be honest, I'd simply accept whatever comes in the request, and default `completed` to `false` when reading it. `undefined` is a "falsy" value.

**Comment by tsm91** [comment]
@jpbochi 

> Now, to be honest, I'd simply accept whatever comes in the request, and default completed to false when reading it. undefined is a "falsy" value.

That would be the easiest way to go. In case the backend team want to do it 'atomic' i can still just have to remember to remove `completed` from the http body.

I think its impossible to create schemas because this is a `JSON` database so i will close this. Thanks for the ansver.

**Comment by jpbochi** [comment]
it's actually possible to add middlewares all sorts of crazy validation, but I don't think that's the purpose of this library. It's a fake REST API server.

I used for some integration tests I'm writing. The code being tested sends requests to the fake API, and the test code will read what was created.

**Comment by tsm91** [comment]
@jpbochi My usecase is for develpoment, so i dont have to wait for the backend guys to finish the api.

You are right, i overthinked the purpose of the library. I will just send whatever information is needed in the http request. If something needed to be modified later on when i migrate to the real backend api, so be it.
