### ISSUE TITLE
Routes display incorrect when custom wrap response

### ISSUE THREAD

**Issue by tao12345666333** [typicode/json-server#341]
When I custom wrap response, the server index routes display incorrect.

My server.js code

```javascript

var jsonServer = require('json-server')
var server = jsonServer.create()
var router = jsonServer.router('db.json')
var middlewares = jsonServer.defaults()

server.use(middlewares)
server.use(router)

server.listen(3000, function () {
  console.log('JSON Server is running')
})

router.render = function (req, res) {
  res.jsonp({
    body: res.locals.data,
    code: 0,
    msg: '',
  })
}

```

The response is correct.
<img width="497" alt="84181101-ad0a-463a-8e55-37d21bf9d179" src="https://cloud.githubusercontent.com/assets/3264292/17550522/e7e5663a-5f27-11e6-9527-f9ea70c9ae7f.png">

But when I open http://127.0.0.1:3000 the page display:
<img width="555" alt="f3477d5c-9206-4acd-9a76-c3d875e13b3f" src="https://cloud.githubusercontent.com/assets/3264292/17550262/bcb7e90c-5f26-11e6-8eb1-59ba736fa952.png">

My env is:

```bash
(Tao) ➜  api git:(master) ✗ json-server --version
0.8.17
(Tao) ➜  api git:(master) ✗ node --version
v6.2.1
```

Thanks for your json-server.

**Comment by typicode** [comment]
Hi @tao12345666333,

Good catch, it's a bug here:
https://github.com/typicode/json-server/blob/master/src/server/router/index.js#L48

`next()` shouldn't be called, instead db state should be returned immediately (`res.jsonp(state)`) to avoid going through the custom wrapper.

Do you want to make a PR?

**Comment by tao12345666333** [comment]
Yes, I will do it.
