### ISSUE TITLE
Help need to POST to added alternate route

### ISSUE THREAD

**Issue by atgrid** [typicode/json-server#347]
I am able to POST to existing route /cars, add alternate route /clients/cars, and GET from both /cars or /clients/cars.  However, when POST to /clients/cars I got

ReferenceError: Promise is not defined

and also get server error code 500

POST /clients/cars 500 10.171 ms - 1037

Is posting to added alternate route supported yet?

**Comment by typicode** [comment]
Hi @atgrid,

It should but there's no automated test validating that (and it would be better if there was one).
Promise error is not related to JSON Server as there's no Promise in the code.

If I have time (or let me know if you want to do it) a test here would validate that:
https://github.com/typicode/json-server/blob/master/test/server/plural.js#L636

Using the same code for testing POST but with a different URL (`/api/posts`):
https://github.com/typicode/json-server/blob/master/test/server/plural.js#L467

**Comment by atgrid** [comment]
Thank you. I forgot to update the status of my request for help.  By doing

|npm install es6-promise@3.1.2|

and then add the following line of code to lowdb/lib/file-async.js:

|var Promise = require('es6-promise').Promise;

then, I could POST to /api/posts. It turned out without adding 
this line of code, I got the Promise error message while POST
still worked but not with the added alternate route. 

I installed json-server on CentOS 6.8.

|


typicode wrote:

**Comment by typicode** [comment]
Great thanks for the update!
I assume this can be closed then :)
