### ISSUE TITLE
Watching doesn't work on Windows 10 with Cygwin

### ISSUE THREAD

**Issue by halfzebra** [typicode/json-server#355]
Cygwin allows using Unix paths under Windows.

```bash
$ json-server --watch api-mock/data.json --port 3000
```
- `json-server` will attempt to watch `api-mock/data.json`
- `chokidar` in `change` event will refer to a change in `api-mock\data.json`, preventing `json-server` from restarting the server

Possible solution will require a change in [src/cli/run.js](https://github.com/typicode/json-server/blob/master/src/cli/run.js#L171)
```js
      chokidar
        .watch(path.dirname(source))
        .on('change', function (file) {
          if (path.resolve(file) === path.resolve(source)) { // resolve paths
```

**Comment by jampow** [comment]
Did you try with backslash?

`json-server --watch api-mock\\data.json --port 3000`

I had some problems with paths on Cygwin, I temporarily fixed running node apps on different terminals like [cmdr](http://cmder.net/) or cmd :-/

**Comment by typicode** [comment]
Closing since the fix has been merged. Thank you again.
