### ISSUE TITLE
POST Resulting in Response Code 500

### ISSUE THREAD

**Issue by xseano** [typicode/json-server#358]
Hi Typicode,

I have used json-server to build many web applications, so thanks. I have been encountering an issue where when I try to POST a JSON array within an object to my database, it results in a 500 response code. 

Here is how I am forming my data: 

`var testArray = {
						
			title: todoTitle, 
			descrp: todoDesc
			
			};
		var testJ = JSON.stringify(testArray);
		console.log(testJ);
		var jointest = JSON.parse(testJ);
                 xhttp.send({
			
				"yo": [jointest]
			
		
		});`

With "id" acting as the Unique Key, I am trying to post to localhost:3000/users/hhhhadjklsajkdlaskjd which currently has: 

`{
  "id": "hhhhadjklsajkdlaskjd",
  "unm": "sean",
  "email": "sean.o@mac.com",
  "pwd": "black",
  "todos_list1": [
    {
      "id": 1,
      "title": "Boodask",
      "descrp": "Read Ouasdtliers"
    },
    {
      "id": 2,
      "title": "s",
      "descrp": "Reassssliers"
    }
  ],
  "todos_list2": [
    {
      "id": 1,
      "title": "Book",
      "descrp": "Read Outliers"
    },
    {
      "id": 2,
      "title": "sadasd",
      "descrp": "Reassasdasdasdssliers"
    }
  ]
}`

This is where the error pops up on the client side:
![screen shot 2016-09-13 at 3 42 45 pm](https://cloud.githubusercontent.com/assets/16991015/18494081/fda40d62-79c8-11e6-9828-5aa285ce2cff.png)

And server side error: 
![screen shot 2016-09-13 at 3 45 10 pm](https://cloud.githubusercontent.com/assets/16991015/18494105/15de1dd2-79c9-11e6-98b7-207ec9e8dc38.png)

Thanks.

**Comment by typicode** [comment]
Hi @xseano,

Happy that it has been helpful :)

Have you tried using `PUT localhost:3000/users/hhhhadjklsajkdlaskjd` instead? Because `POST` only works for creating a resource (i.e. `POST localhost:3000/users`).

**Comment by typicode** [comment]
And also, posting array isn't supported except if it's inside an object, for example:

```
{
  "name": "foo",
  "values": [ 1, 2, 3 ]
}
```

Based on the JSON I see, you want to have users with a list of todos for each one?

**Comment by xseano** [comment]
Hi @typicode,

I am not using PUT because I am not trying to replace the data, but trying to create a new array within localhost:3000/users/hhhhadjklsajkdlaskjd. A new array of data just like "todos_list1" and "todos_list2". This is because I am building a todo web application and need to keep all todos within their respective lists inside a single object for each user. And the data I am POSTing is {"yo":[{"title":"asd","descrp":"asd"}]} so it is within an object. :/

**Comment by xseano** [comment]
@typicode 

I have a feeling it may be the payload format because of the server message, but I am not sure how else to format the data so it will be accepted by the server?

**Comment by xseano** [comment]
Fixed by rewriting payload format and changing request method from POST to PATCH.

**Comment by typicode** [comment]
:+1:
