### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by Pradeepkn** [typicode/json-server#369]
I tried to run command _**json-server db.json**_ in my iMac.
But getting _**json-server command not found**_. It works in some other machine.
Please help me out on how to resolve it.

**Comment by typicode** [comment]
May be related to https://github.com/typicode/json-server/issues/370

**Comment by Gruck** [comment]
@Pradeepkn Did you try `sudo npm install -g json-server`. 
executing this as `sudo` solved issue for me (ubuntu 14.04, node installed without nvm)

**Comment by michael-mahoney** [comment]
This fixed my problem, thanks!

**Comment by munimathur** [comment]
I tried to install json server  in window 10 But I am getting this message.
 Installation command which i am using   $ npm install -g json-server

Error Message :  '$' is not recognized as an internal or external command,
operable program or batch file.

**Comment by RaquelPlaza** [comment]
@munimathur, you don't need to type the $. ;)

**Comment by krolovolk** [comment]
Helps for me (may be problem with global path on iMac)
`export PATH=$PATH:$HOME/.npm-global/bin`

**Comment by VikMelanchenko** [comment]
> Helps for me (may be problem with global path on iMac)
> `export PATH=$PATH:$HOME/.npm-global/bin`

This fixed my problem, thanks!
