### ISSUE TITLE
Command to start json-server is not working.

### ISSUE THREAD

**Issue by KavyaKn** [typicode/json-server#370]
I am trying to start JSON server with following command
$ json-server --watch db.json 

I am not able to start the server. I am getting command not found error

“json-server: command not found”

I referred 
https://github.com/typicode/json-server
http://www.betterpixels.co.uk/projects/2015/05/09/mock-up-your-rest-api-with-json-server/

I am using iMac (Mid 2010) with latest OS (macOS Sierra) version 10.12

Please help me to resolve the issue. Thanks

**Comment by typicode** [comment]
Hi @KavyaKn 

I would suggest double checking if the flag `-g` was set when running `npm install -g json-server`. It's usually a common mistake that results in `command not found`.

If it doesn't work, can you tell me what's your version of `node` and `npm`? What did you use to install Node?

**Comment by KavyaKn** [comment]
Hi..
I had used the same command “npm install -g json-server”
The node and npm version which i am using is 
node -> v6.6.0
npm - > 3.10.3

and i had downloaded the node from this URL
https://nodejs.org/en/

**Comment by kuzkuz93** [comment]
I'm having the exact same issue as well

node v6.7.0
npm v3.10.7

**Comment by typicode** [comment]
If you try to install another CLI tool, do you have the issue too? For example:

```sh
$ npm install --global gulp-cli
$ gulp
```

**Comment by KavyaKn** [comment]
Yes i am getting the issue  "-bash: gulp: command not found". 
For the command
$ npm install --global gulp-cli
$ gulp

**Comment by typicode** [comment]
Thank you for the test.

I think it might be related to your Node installation actually. `PATH` may be missing some Node paths and so your terminal fails to find installed CLIs.

I've not tried Node installer on Sierra so I can't say much, but you can try reinstalling it or you can check if there's not something that is modifying `PATH`.

Personally, I like to use [nvm](https://github.com/creationix/nvm) and it works on Sierra.

**Comment by kuzkuz93** [comment]
Thank you very much. Reinstalling node with nvm worked for me

**Comment by typicode** [comment]
Glad it worked :+1:
Is it ok for you too @KavyaKn?

**Comment by Gruck** [comment]
Did you try `sudo npm install -g json-server`. 
executing this as `sudo` solved issue for me (ubuntu 14.04, node installed without nvm)

**Comment by yescay** [comment]
[POSSIBLE SOLUTION]I had the same problem. Did the following steps.

- installed JSON-Server with 
sudo npm install -g json-server

Tried to start the server in the same terminal
 json-server db.json

Got the same error. 


- Started a fresh terminal and started the server and it worked fine.

**Comment by daniel-kunha** [comment]
I had this problem because my $HOME/.npm-global/bin was not in the $PATH.
Works for me.

export PATH=$PATH:$HOME/.npm-global/bin

tip: Is possible get json-server install in return message of npm install -g json-server  command.

**Comment by jay-developer** [comment]
use "json-server db.json" db.json is my json file name replace it with your file name

**Comment by RadwaSK** [comment]
I know this is rather old, but I had the same issue and got solved by installing json-server package globally, that's all.
Meaning, I run this command
`npm install -g json-server`
 before running
`json-server --watch db.json`

I didn't have to re-install node or npm, or use nvm or anything else.

**Comment by vijayuxd** [comment]
I have a problem that json server not working. 
Error Showing: ERR! code ELIFECYCLE 
Error Showing: ERR! errno 1
`json-server --watch db.json` not woking and showing error
**i got the answer**
while start json-server it compiling the db.json file and if any type mistake in db.json file it show the error

**Comment by iamgodswill** [comment]
bash: json-server: command not found 
am using windows 10 trying to use it on reactjs...Please help

**Comment by paschalidi** [comment]
fixed this by following the steps are being described here https://stackoverflow.com/questions/43465086/env-node-no-such-file-or-directory-in-mac

**Comment by manasdwd07** [comment]
@iamgodswill 
I am using Mac mini and was stuck in the same issue some days ago.
Try using _

> sudo npm install -g json-server

👍 
_

**Comment by lucasm-git** [comment]
Hello, I'm building something that I wish someone could use without having to install json-server globally themselves.
Is there a way to make it so json-server would be ready to use as soon as the other person would download + npm install my app?

**Comment by abdelalimah** [comment]
`npx json-server --watch db.json`

**Comment by melnicenkovadik** [comment]
да, с npx оно типо его запустило, но ничего он не подгружает, файл с базой видит отлично, а достучаться к нему нельзя
...оставил пока так как есть)...хоть запустился...

**Comment by mimahcode** [comment]
> `npx json-server --watch db.json` solved the problem for me

This also helped me resolve the issue. 
PS: I use Windows

**Comment by agkpup** [comment]
npm install -g  json-server --save has worked for me...... its good option

**Comment by Rainspistols** [comment]
> `npx json-server --watch db.json` solved the problem for me

Very helpful

**Comment by YaswanthKota** [comment]
> `npx json-server --watch db.json` solved the problem for me

thanks for this!

**Comment by ahmadabdelmaksoud** [comment]
> Did you try `sudo npm install -g json-server`.
> executing this as `sudo` solved issue for me (ubuntu 14.04, node installed without nvm)

this works for me, thank you!

**Comment by Reda75** [comment]
Try `sudo npm install -g json-server `, it's work for me

**Comment by caprica-Six** [comment]
This works `npx json-server --watch db.json` - thanks @abdelalimah

**Comment by NageshRu** [comment]
> `npx json-server --watch db.json` solved the problem for me

Thank you  @caprica-Six it is working for me.

**Comment by ermanergul** [comment]
> `npx json-server --watch db.json` benim için problemi çözdü

Thank you @caprica-Six it's working

**Comment by SergeyBykov1996** [comment]
Мне помогла не локальная установка , а глобальная .

**Comment by kubrailkul** [comment]
> `npx json-server --watch db.json` solved the problem for me

Thank you so much. This works

**Comment by ShahriyarR** [comment]
I was trying to use it with Vue JS in Linux and came across the same issue:
* `npm install json-server`
It will install the package locally and inside the Vue project there is a `node_modules` folder and the executable is in `.bin`.
So running the following command will work.
```
./node_modules/.bin/json-server --watch data/db.json

  \{^_^}/ hi!
```

**Comment by n0l0g0** [comment]
> Did you try `sudo npm install -g json-server`.
> executing this as `sudo` solved issue for me (ubuntu 14.04, node installed without nvm)

it work!

**Comment by chaker-ayachi** [comment]
npx json-server --watch db.json worked for me

**Comment by bhojkamal** [comment]
For me too. npx json-server --watch db.json worked. I didn't install globally, I installed locally.

**Comment by Rimpi246** [comment]
> For me too. npx json-server --watch db.json worked. I didn't install globally, I installed locally.

It didn't work for me.. I am getting command not found: json-server. 
Can anyone please help me? I am using Windows 10

**Comment by born69confused** [comment]
The common mistake  is **not installing the package globally**
Use : _npm install -g json-sever_

**Comment by yogeshpawar1958** [comment]
For me too. npx json-server --watch db.json worked. I didn't install globally, I installed locally.

**Comment by yogeshpawar1958** [comment]
and its working well.

**Comment by HiemIT** [comment]
I fixed the error by running this command again.
sudo npm install -g json-server

**Comment by BVRXNDVRK** [comment]
> I was trying to use it with Vue JS in Linux and came across the same issue:
> 
> * `npm install json-server`
>   It will install the package locally and inside the Vue project there is a `node_modules` folder and the executable is in `.bin`.
>   So running the following command will work.
> 
> ```
> ./node_modules/.bin/json-server --watch data/db.json
> 
>   \{^_^}/ hi!
> ```

Thanks ! So no need to install this global)

**Comment by becasualle** [comment]
> `npx json-server --watch db.json` solved the problem for me

God bless you, sir, and thank you from my heart! @abdelalimah

**Comment by iammadhu489** [comment]
> > `npx json-server --watch db.json` solved the problem for me
> 
> thanks for this!

Thanks this works for me also
