### ISSUE TITLE
Format all GET response

### ISSUE THREAD

**Issue by Ridermansb** [typicode/json-server#371]
I need to format API GET response from `json-server`

When I make a request GET `/api/v1/cobject/XYZ`

Return a array of XYZ objects.. `[]`

I need to modify this, I tried.. in my server

    server.use(function (req, res, next) {
      if (req.method === 'GET' && req.url.indexOf('cobject') > 0) {
        console.log(res) // How change format of response?? 
      }
      next()
    })

I need to format this way...

    {
        data: [...]
        pagination: {page: 1, per_page: 20, total_pages: 1, total_elements: 1}
    }

[0]: https://github.com/typicode/json-server

**Comment by typicode** [comment]
Hi @Ridermansb,

To change the response format, see https://github.com/typicode/json-server#custom-output-example

```js
router.render = function (req, res) {
  if (req.method === 'GET' && ...) {
    var newData = formatData(res.locals.data, res.get('Link'))
    res.json(newData)
  } else {
    res.json(res.locals.data)
  }
}
```

If you have `req.query._page` param, JSON Server will add `Link` and `X-Total-Count` headers. You can use that to create the `pagination` metadata.

You can also access the [lowdb](https://github.com/typicode/lowdb) instance using `router.db` if you need to go further.

**Comment by Ridermansb** [comment]
Thanks @typicode
