### ISSUE TITLE
Link header is missing from the response

### ISSUE THREAD

**Issue by c10b10** [typicode/json-server#380]
```
❯ curl -I "http://localhost:3001/?_page=1"

HTTP/1.1 200 OK
X-Powered-By: Express
Vary: Origin, Accept-Encoding
Access-Control-Allow-Credentials: true
Accept-Ranges: bytes
Cache-Control: public, max-age=0
Last-Modified: Mon, 19 Sep 2016 08:48:27 GMT
ETag: W/"4c0-15741a1d378"
Content-Type: text/html; charset=UTF-8
Content-Length: 1216
Date: Mon, 03 Oct 2016 14:45:18 GMT
Connection: keep-alive
```

Any idea why this is happening?

**Comment by typicode** [comment]
Hi @c10b10,

Yes, you need to use it on a resource:

```
/posts?_page=1
/comments?_page=1
...
```

**Comment by c10b10** [comment]
That indeed returns all the headers, including the Link header. So does the fetch I see in the browser. The problem is that when I call `response.headers.get('Link')` in the `fetch` `then`, I get null. Listing all the header I receive in the fetch response, I get:

```
x-total-count: 100
VM28639:2 pragma: no-cache
VM28639:2 content-type: application/json; charset=utf-8
VM28639:2 cache-control: no-cache
VM28639:2 expires: -1
```

Is there something I'm missing?

**Comment by c10b10** [comment]
Would you mind adding the label ["Hacktoberfest"](https://hacktoberfest.digitalocean.com/)?
