### ISSUE TITLE
URL containing two slashes returns empty response

### ISSUE THREAD

**Issue by rockwillj** [typicode/json-server#382]
I created the following json file.

```json
{
    "foo": { "name": "xxx" },
    "foo/bar": { "name": "yyy" },
    "foo/bar/baz": { "name": "zzz" }
}
```

I started JSON Server, and got strange behavior like this.

First, `http://localhost:3000/foo` returns

```
{
  "name": "xxx"
}
```

Next, `http://localhost:3000/foo/bar` returns

```
{
  "name": "yyy"
}
```

Then, `http://localhost:3000/foo/bar/baz` returns

```
{}
```

I don't know why I got empty response only when a URL has two slashes. This is a bug or wrong usage?

**Comment by typicode** [comment]
Hi @rockwillj,

`/` in `db.json` are not supported.

Without knowing what foo, bar and baz it's hard to say what would be the good structrue for `db.json`.

Bu you can try this for your`db.json`:

```json
{
  "things": [ { "id": 1, "name": "xxx" }, { "id": 2, "name": "yyy" }, ... ]
}
```

with the following `routes.json`:

```json
{
  "foo": "/things/1",
  "foo/bar": "/things/2",
  "foo/bar/baz": "/things/3"
}
```

Or alternatively you can do:

```
{
  "foo": {},
  "foo-bar": {},
  "foo-bar-baz": {}
}
```

With the following `routes.json`

```json
{
  "/foo": "/foo",
  "/foo/bar": "/foo-bar",
  "/foo/bar/baz": "/foo-bar-baz"
}
```

See https://github.com/typicode/json-server#add-routes

If there's a relationship between foo, bar and baz, you can use the example provided here for inspiration:
https://github.com/typicode/json-server#example

as it shows basic relationships between some posts and comments.

**Comment by rockwillj** [comment]
Hi @typicode, 

Thank you for the quick response.

OK, I have understand `/` does not supported in `db.json`.
Workarounds you show me above are great, they works perfectly.

Thank you from the bottom of my heart!

P.S. I know the URL structure is not good but I have to use it. I'm not a server side engineer...
