### ISSUE TITLE
Field "is_new" is picked up for NotEquals (is_ne)

### ISSUE THREAD

**Issue by ev45ive** [typicode/json-server#383]
I have struct like this:

```
{ id: 123, title: "hello", is_new: true }
```

when i search for it with **?is_new=true** i get everything but this one - like its seeing "is_**ne**" and uses **not equals matcher**. Shouldn't it be matched by end of param name? :-)

Btw. Json-Server is AWSOME. I am prototyping and relationships ?_embed and ?_extend saved me a looot of headache! Thanks!

**Comment by typicode** [comment]
Good catch 👍 will fix it
Thank you and glad that it's helpful :)

**Comment by typicode** [comment]
Hi @ev45ive,

I've published `v0.9.0-beta.2` which should better handle operators. You can give it a try using `npm install -g json-server@next`. Documentation can be found in the `next` branch.

Let me know if you spot anything else.

**Comment by ev45ive** [comment]
Awesome. Thanks a lot! 

I am doing JS/Front-End teaching classes, and JSON-Server is a kickass tool to showcase stuff. :-) 👍

**Comment by typicode** [comment]
Oh great usage and very happy to know it's used to teach people front-end :smiley:

**Comment by typicode** [comment]
Closing it since `v0.9.0` is now published :)
