### ISSUE TITLE
allow rewrites to static routes

### ISSUE THREAD

**Issue by ocjojo** [typicode/json-server#386]
I would like to use static stubs for dynamic resources.
Therefore I thought I might use rewrites:
`{
	"/person/:id": "/person.json",
	"/city/:id": "/city.json"
}`
together with the static file server, which delivers person.json/city.json

The reason I want to use seperate json files being that they are a couple of hundreds lines each, so that a simple db.json is overloaded.

It seems moving `app.use(defaults)` after `app.use(rewriter)` in [cli/run.js](https://github.com/typicode/json-server/blob/master/src/cli/run.js) would solve this. Although I haven't tested it very extensively.

**Comment by typicode** [comment]
Hi @ocjojo,

If you don't need to save changes to your JSON files, you can try this approach:

```js
// db.js
module.exports = () => {
  'posts': require('./posts.json'), // [ { id: 1, title: 'foo' }, ... ]
  'comments': require('./comments.json')
}
```

```sh
json-server db.js
```

https://github.com/typicode/json-server#generate-random-data

And if you need to persist your changes, you can always create snapshots.

**Comment by ocjojo** [comment]
awesome, thank you 👍
