### ISSUE TITLE
Can not use string as object ID ?

### ISSUE THREAD

**Issue by windmaomao** [typicode/json-server#39]
I found this is interesting, if id is 54958d281a995 instead of an integer, it stop working.

**Comment by typicode** [comment]
hi @eduardoinnorway I'll try to come up with something.

Actually using https://github.com/typicode/lowdb for the JSON file database on JSON Server :)

**Comment by typicode** [comment]
Sorry, it took some times but the feature is here now in `v0.5.11`.
In case, it can't generate an integer id, it falls back to using a uuid.
