### ISSUE TITLE
Map route variables

### ISSUE THREAD

**Issue by trevordmiller** [typicode/json-server#391]
I'm trying to map the json-server routes to match the routes of my real environments; so I can mock out new endpoints before they are built but still use the same routes as what already exists in prod. This is what my routes look like so far:

```
{
  "/api/v1/": "/",
  "/users": "/users",
  "/users/:name-slug": "/id/:id"
}
```

So, I'd like to be able to use the `/users/jane-doe` route in the same way I use the `/users/23` route; is this possible?

I've read through the docs and don't see a way to do this currently; am I missing something or would this be a new feature?

p.s. thank for building such an awesome tool!

**Comment by typicode** [comment]
Hi @trevordmiller,

That's an interesting case. I don't think it's possible right now with the router.
You can probably do it using the project as a module though:

https://github.com/typicode/json-server#custom-routes-example

```js
var jsonServer = require('json-server')
var server = jsonServer.create()
var router = jsonServer.router('db.json')
var middlewares = jsonServer.defaults()

// Set default middlewares (logger, static, cors and no-cache)
server.use(middlewares)

// Add custom routes before JSON Server router
server.get('/users/:name', function (req, res) {
  // See https://github.com/typicode/lowdb
  var user = router.db
    .get('users')
    .find({ name: req.params.name })
    .value()
  if (user) {
    res.jsonp(user)
  } else {
    res.sendStatus(404)
  }
})

server.use(function (req, res, next) {
  if (req.method === 'POST') {
    req.body.createdAt = Date.now()
  }
  // Continue to JSON Server router
  next()
})

// Use default router
server.use(router)
server.listen(3000, function () {
  console.log('JSON Server is running')
})
```

PS: thank you for the feedback :)

**Comment by trevordmiller** [comment]
Ok sounds good. Thank you! Closing.
