### ISSUE TITLE
404 when using module?

### ISSUE THREAD

**Issue by littlee** [typicode/json-server#398]
db.json
```json
{
  "/a": {
    "id": 1,
    "username": "goms"
  }
}
```

server.js
```js
var jsonServer = require('json-server')
var server = jsonServer.create()
var router = jsonServer.router('./db.json')
var middlewares = jsonServer.defaults()

server.use(middlewares)
server.use(router)
server.listen(3000, function () {
  console.log('JSON Server is running')
})
```

but I always get 404 when accessing `localhost:3030/a`

![2016-11-07 4 49 05](https://cloud.githubusercontent.com/assets/7534668/20051484/396725ac-a50a-11e6-8be5-e0293a562a74.png)

**Comment by typicode** [comment]
Hi @littlee,

`/` aren't supported in `db.json`, simply remove it and you should be good ;)

```json
{
  "a": {
    "id": 1,
    "username": "goms"
  }
}
```

**Comment by littlee** [comment]
@typicode 
after removing `/`, I still get `404`

![2016-11-07 5 55 02](https://cloud.githubusercontent.com/assets/7534668/20053430/7283f0e6-a513-11e6-89f4-7af50b711330.png)

**Comment by littlee** [comment]
I know the problem,

I put `db.json` and `server.js` in the `/mock/` folder

and I start the server using `node ./mock/server.js`

it will get 404

SOLUTION:
```
cd mock
node server.js
```

so, should we consider it as a bug? 😂

**Comment by typicode** [comment]
Maybe a lack of docs :)
I've updated the README with more details about how to use an absolute path to make the code more reliable: 
https://github.com/typicode/json-server#simple-example
