### ISSUE TITLE
Gets 301 redirect when request path contains "images"

### ISSUE THREAD

**Issue by hyiso** [typicode/json-server#399]
1. First, create a server that contains some resource:
![image](https://cloud.githubusercontent.com/assets/5681324/20053487/bc753bd8-a513-11e6-85d4-db64e105eb36.png)
2. Then, try `/group` and it goes as expected:
![image](https://cloud.githubusercontent.com/assets/5681324/20053523/ee7c89e2-a513-11e6-9921-7361eadf8cf6.png)
3. But when try `/images`, it responses with a `301` redirect (from `/images` to `/images/`), which result in failure in ajax request。
![image](https://cloud.githubusercontent.com/assets/5681324/20053559/1676a3b0-a514-11e6-9b2f-25f202ee7022.png)
I guess it might be the problem that `images` is also the directory of the serve's public assets (remaining to be tested.)

**Comment by Nilegfx** [comment]
@hyiso remove the last `/`, you should request `http://localhost:9999/images` not `http://localhost:9999/images/`

**Comment by Nilegfx** [comment]
Nice catch, I do think this is a bug in `json-server` as it serve `/images`, `stylesheets` statically and causes the static middleware before reaching the actual routes. 

for now,TEMPORARY, you could do one of the following: 
* Use something other than `images` as a key for your resource
* Find your *json-server* installation folder
   * **If you installed it locally**: you will find it in your project root directory `node_modules/json-server`, navigate to `node_modules/json-server/lib/server/public` and remove the images folder, then restart your server, it should work (don't worry, the only flaw of removing this folder is you are going to loose json-server logo-like image 
![image](https://cloud.githubusercontent.com/assets/1198975/20739869/c65ff43c-b6be-11e6-8a20-b578591e9dad.png)

   * **if you installed it globally**: it depends on your OS, node/npm installation, you can google "global npm package root"



@typicode: I do suggest one of the following:
* hash images and stylesheets folder something like  `images_static_756476574` and `stylesheets_static_8288488343`
* further enclosing the static files into unlikely-to-chose-name folder like `public/statically_served_for_json-server_349938`

I could do PR with this or whatever else you suggest
