### ISSUE TITLE
return 404 when a route has two slashes in the url

### ISSUE THREAD

**Issue by zac1st1k** [typicode/json-server#405]
steps to reproduce: 

1. set db.json

```
{
  "employment/v2/references": {
    "test": "test"
  }
}
```

2. visit `employment/v2/references`

expected: { test: "test"}
actual: 404

**Comment by typicode** [comment]
Hi @zac1st1k,

Sorry, `/` aren't supported in `db.json` and will result in an error with the latest version of JSON Server.

That said, you can do this:

`db.json`

```json
{
  "references": {
    "test": "test"
  }
}
```

`routes.json`

```json
{
  "/employment/v2/references": "/references"
}
```

Then run

```sh
json-server db.json --routes routes.json
```

Now when you'll make a request to `/employment/v2/references` it'll serve the result of `/references`.

You can use `:id` or `:resource` tokens, if you want to make it more generic.

For more details, see https://github.com/typicode/json-server#add-custom-routes
