### ISSUE TITLE
GET /:parent/:parentId/:resource when parentId doesn't exist deletes the :resource

### ISSUE THREAD

**Issue by julienbechade** [typicode/json-server#41]
Hi,

Thanks for this module, very, very helpful…
But now I'm pushing it further, I'm stumbling upon some problems.

For example, if you `GET /posts/4/comments` and the post with id 4 does not exist the entire `comments` resource will be deleted. This happens very inconsistently and I have not been able to debug it so far.

Do you have any idea of what could cause this?

Thanks for your time.

**Comment by typicode** [comment]
Hi,

Really happy you find it useful :)

Regarding the issue, it's strange that it's inconsistent. Also in the GET route, there's nothing that should delete things. 

I'll try to write a test or make manual tests as soon as I can.

You're welcome, thanks for letting me know about this issue.

**Comment by julienbechade** [comment]
I'm still debugging so I'll update as soon as I found something if I find something…

**Comment by typicode** [comment]
Cool, thanks :)

**Comment by julienbechade** [comment]
So far I found the test case…
On newly created `posts` when no `comments` is linked via the `postId` key, the entire resource gets deleted.

Steps to reproduce:
- resource `posts` and `comments` exists,
- `comments/{i}` are tied to `posts\{j}` via the `postId` key,
 - create a new post, id of {k} gets attributed,
- `GET /posts/{k}/comments`, returns `[]`,
- `GET /comments`, returns `[]`…

I cannot get to the root of the behavior yet but I have good hopes…

Cheers.

**Comment by julienbechade** [comment]
So far I found the test case…
On newly created `posts` when no `comments` is linked via the `postId` key, the entire resource gets deleted.

Steps to reproduce:
 * resource `posts` and `comments` exists,
 * `comments/{i}` are tied to `posts\{j}` via the `postId` key,
 * create a new post, id of {k} gets attributed,
 * `GET /posts/{k}/comments`, returns `[]`,
 * `GET /comments`, returns `[]`…

I cannot get to the root of the behaviour yet but I have good hopes…

Cheers.

**Comment by julienbechade** [comment]
I found where the problem lies. It's due to the way I'm handling the edit of the data.
When updating, I `DELETE` all `posts` items and `POST` the updated or new items, `json-server` removes dependents `comments` on `DELETE /posts/{k}`, which make kind of sense but not for what I'm trying to achieve…

I'll handle the use case in the client then.

Sorry and thanks for your time.

**Comment by typicode** [comment]
You're welcome, good that you solved your issue :)
