### ISSUE TITLE
When require('json-server') in parent app, Express middleware doesn't get executed

### ISSUE THREAD

**Issue by julienbechade** [typicode/json-server#42]
Hi,

I assume I'm doing something wrong here…
Here is my `app.js`:

```javascript
var server = require('json-server')
var app = server({ schemas: [] }, 'db.json')

app.use(function (req, res, next) {
	console.log('Time:', Date.now());
	next();
})

app.listen(process.env.PORT || 3000)
```

This doesn't print anything to the terminal…

Thanks for your time.

**Comment by typicode** [comment]
Hi Julien,

Even if you make a request? 
The API could get some enhancement, it's not very clear how `server()` work.

**Comment by julienbechade** [comment]
Even when I make a request.

**Comment by typicode** [comment]
Forget about the "even if you make a request", I misunderstood your issue.
I'll have a look into this.

**Comment by julienbechade** [comment]
Just read [this issue](https://github.com/typicode/json-server/issues/30) and figured out how to mount `json-server`…

Sorry for bothering you.

Thanks for your time.
