### ISSUE TITLE
Custom routes for get/post

### ISSUE THREAD

**Issue by fabiojansenbr** [typicode/json-server#423]
Hi, im my app im trying to to:

	var _getCustomers = function(page) {
		return $http.get(config.baseUrl + "/customers/");
	};

	var _saveCustomer = function(customer) {
		return $http.post(config.baseUrl + "/customer/", customer);
	}

How do i configure to match this routes?

**Comment by typicode** [comment]
Hi @fabiojansenbr,

Create a routes.json with:

```json
{
  "/customer": "/customers",
}
```

This way you can do:

```
GET /customers
POST /customer # will be rewritten to /customers
```

https://github.com/typicode/json-server#add-custom-routes
