### ISSUE TITLE
Document that _start is inclusive and _end is exclusive

### ISSUE THREAD

**Issue by fzaninotto** [typicode/json-server#436]
I was bitten by something I didn't expect using slicing arguments:

* `http://jsonplaceholder.typicode.com/posts?_start=0&_end=9` returns 9 results (rank 0 to 8)
* `http://jsonplaceholder.typicode.com/posts?_start=1&_end=9` returns 8 results (rank 1 to 8)
* `http://jsonplaceholder.typicode.com/posts?_start=1&_end=10` returns 9 results (rank 1 to 9)
* `http://jsonplaceholder.typicode.com/posts?_start=0&_end=10` returns 10 results (rank 0 to 9)

It seems that `_start` defines when the slice starts, *including* the rank, and `_end` defines where it ends, *excluding* the rank.

If that's not a bug, this should be better documented, because it doesn't feel natural.

**Comment by typicode** [comment]
Good point, I'll update the README and sorry for the confusion.
The idea of `_start` and `_end` is to mimic [`Array.prototype.slice()`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/slice).

That said, in recent versions of JSON Server, you now have `_page` param that can be used with `_size` and is inspired by the way GitHub API handles pagination:
https://developer.github.com/v3/#pagination

**Comment by typicode** [comment]
Documented ;)
