### ISSUE TITLE
Unable to update with a POST

### ISSUE THREAD

**Issue by CalebKester** [typicode/json-server#437]
I was using 0.8.23 and I would use a POST api call to both create and update the json object. If I sent an id in that it would create a new json object but if I sent an id it would just update that id.

I updated my json server and now i'm getting an "Insert failed: duplicate id." error.  Is this the expected outcome? It was my understanding that I could use posts to update content.

I can supply code examples if need be.

**Comment by typicode** [comment]
Hi @CalebKester,

Usually in REST `POST` should only be used to create a resource and to update `PUT` should be preferred. So in `v0.8.23` it was a bug that `POST` could be used to update a resource.

**Comment by CalebKester** [comment]
Sounds good, I figured it was a bug either way. I'll have to do some research as to what I'd like to mirror in my application. Really dig json-server though and it's been critical to use in early development.
