### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by kentcdodds** [typicode/json-server#44]
This is awesome. Thanks for your work here! Wondering how you/if you would go about setting up some sort of fake authentication system. Specifically, I want to use JWT. Do you think there's room for something like this in this project?

**Comment by typicode** [comment]
Hi Kent,
Thanks for the nice comment :)

I would try this:
https://github.com/typicode/json-server/issues/42

You should be able to add routes or use middlewares since the project is built on Express.

Tell me if that helps?

**Comment by typicode** [comment]
Wrong issue, this is the one I wanted to link :)
https://github.com/typicode/json-server/issues/30

**Comment by kentcdodds** [comment]
I'll give it a look. Thanks!

**Comment by typicode** [comment]
Closing the issue.

Just for the record, now JSON Server can be used as a middleware so it should be easier to add authentication.

**Comment by kentcdodds** [comment]
:+1:
