### ISSUE TITLE
Issue with PUT 404 not found

### ISSUE THREAD

**Issue by AdamCook44** [typicode/json-server#440]
Hello,

I have an issue with the PUT request and I don't understand why. The get request works perfectly and the query too.

Here is the watch screen.

![image](https://cloud.githubusercontent.com/assets/23452159/21181963/cd39685e-c200-11e6-8bd4-45f10b929da6.png)

![image](https://cloud.githubusercontent.com/assets/23452159/21181995/053579d2-c201-11e6-84a3-524dfb33b680.png)

And here is the **service.js** 

![image](https://cloud.githubusercontent.com/assets/23452159/21182017/259bc528-c201-11e6-9382-8e9150c09792.png)

and the **controller.js**

![image](https://cloud.githubusercontent.com/assets/23452159/21182030/37c73e9e-c201-11e6-9bf0-7b56c2c93486.png)

Do you know what is the trouble ?

Thanks in advance !

**Comment by typicode** [comment]
Hi,

I think it's because the id is passed as a query param (`?id=1`), `PUT /dishes/1` should work.
I don't know though how to fix the JS code so that it's not passed as a query param.

**Comment by AdamCook44** [comment]
Hi Typicode,

You're right, I have tried it manualy and it worked. I still don't know how to fix it with JS but it's another trouble.

Thank you very much!

**Comment by riyazmulla51** [comment]
Hi, I am new to use json server.
I am using it for multiple files. In module solution scenario i am facing the same issue, like for PUT and PATCH without any id it is giving 400.
//server.js file
![put](https://user-images.githubusercontent.com/43986917/80310521-c382f480-87f8-11ea-9ddf-32e180525ed4.PNG)

//endpoints not working
![image](https://user-images.githubusercontent.com/43986917/80310548-ee6d4880-87f8-11ea-9638-7179880b3352.png)

//endpoint working
![image](https://user-images.githubusercontent.com/43986917/80310584-21afd780-87f9-11ea-8631-0b7c9a1ec3a0.png)

@typicode  @AdamCook44 is there anything i am missing here?

**Comment by SalahAdDin** [comment]
> Hi,
> 
> I think it's because the id is passed as a query param (`?id=1`), `PUT /dishes/1` should work. I don't know though how to fix the JS code so that it's not passed as a query param.

It is happening to me right now:
![image](https://github.com/user-attachments/assets/73f9b7ab-7807-489e-9a55-fc19d9c5e3b2)

**Comment by percebus** [comment]
+1 w/ `v0.17.4`

![image](https://github.com/user-attachments/assets/78df1e91-043f-4e85-9f60-cda41064c6eb)

**Comment by SalahAdDin** [comment]
> +1 w/ `v0.17.4`
> 
> ![image](https://private-user-images.githubusercontent.com/5483088/402370555-78df1e91-043f-4e85-9f60-cda41064c6eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY3OTAyOTYsIm5iZiI6MTczNjc4OTk5NiwicGF0aCI6Ii81NDgzMDg4LzQwMjM3MDU1NS03OGRmMWU5MS0wNDNmLTRlODUtOWY2MC1jZGE0MTA2NGM2ZWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDExMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMTNUMTczOTU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzMyMTg2ZTNlNzVlZjJjOTU1OTk2YjFkYzYxNzgzZGUxNGY3NTM5NjE1ZDM4NzhmNTkwNmFiNzRkODZmYmZlMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.5mxxZtN7XyoQItpOxfI_OmsqHmFXI4G_94NeMsvVFbU)

wanna open a new issue?
