### ISSUE TITLE
Is it possible to restore data of json file after restart each time

### ISSUE THREAD

**Issue by tailai** [typicode/json-server#450]
I'd like to have a stable data for develpment and UI integration testing. And also share data in team. Seems method like POST will change json file directly.

**Comment by Nilegfx** [comment]
You could write a very simple middleware to disable all but GET requests. 

let me know if you don't know how to do this.

**Comment by tailai** [comment]
@Nilegfx thanks your reply, I know there is a readonly option, but what I want is POST/DELETE requests work as usual, but do not sync the changes to json file, so that I can have the same data each time I start json server.

**Comment by tailai** [comment]
When I sperate data files, I found change do not sync back to json files as I need.

```javascript
let data = {};

const files = fs.readdirSync(dataFolder);
files.forEach(function (file) {
    let pathName = path.join(dataFolder, file);
    if (path.extname(pathName) === '.json') {
        data[path.basename(pathName, '.json')] = require(pathName)
    }
});

module.exports = function () {
    return data;
};
```

**Comment by lazee** [comment]
Why not just solve this with a small bash-script? 

~~~bash
cp orig_db.json tmp_db.json
json-server tmp_db.json
~~~
