### ISSUE TITLE
Possible Error in README

### ISSUE THREAD

**Issue by jmzagorski** [typicode/json-server#459]
Under the [Custom Routes](https://github.com/typicode/json-server#add-custom-routes) section it has `"/blog/:category": "/posts/:id?category=:category"` translating to `/blog/javascript # → /posts?category=javascript`. 

Shouldn't the route be `"/blog/:category": "/posts?category=:category"`? That is how I got it to work. Just want to make sure. Thanks.

**Comment by typicode** [comment]
Hi @jmzagorski,
You're right, good catch thank you 👍

**Comment by jmzagorski** [comment]
yup, i'll do it this weekend.
