### ISSUE TITLE
Possible to write to files?

### ISSUE THREAD

**Issue by zeke** [typicode/json-server#46]
When I saw in the readme that `PUT` and `POST` requests are supported, I expected that to mean the underlying JSON files can be written to via HTTP. Is that the case?

If not, wouldn't that be cool?!

**Comment by typicode** [comment]
Hi Zeke,

It's the case (or else it's a bug).
When you provide a JSON file, changes are persisted to it:

```bash
$ json-server file.json # will write
```

But in other cases, it won't

```
$ json-server file.js # won't write
$ json-server http://somewhere.com/file.json # won't write
```

You can always, type `s` to save current database state.

**Comment by zeke** [comment]
awesome. Can't wait to give this a try.
