### ISSUE TITLE
Routes file is ignored when running json-server in development

### ISSUE THREAD

**Issue by miguelcg** [typicode/json-server#462]
When I run `npm run start --watch example.json --port 3000 --routes routes.json` after cloning this repo and doing `cd json-server`, the file `routes.json` is being ignored.

content of `routes.json`:
```json
{
  "/best": "/posts"
}
```

The content of `example.json`:
```json
{
  "posts": [
    {
      "id": 1,
      "title": "json-server",
      "author": "typicode"
    },
    {
      "id": 2,
      "title": "test",
      "author": "qwerty"
    }
  ],
  "comments": [
    {
      "id": 1,
      "body": "some comment",
      "postId": 1
    }
  ],
  "profile": {
    "name": "typicode"
  }
}
```

**Comment by typicode** [comment]
Hi @miguelcg 

Could you try `npm start -- --watch example.json --port 3000 --routes routes.json`?
`--` is used to tell `npm` to pass what is after to the `start` script.

**Comment by miguelcg** [comment]
Thanks @typicode, it works! I didn't know that, sorry. I was actually trying to reproduce #438 to try to solve it :)
I'll close this as it's not an issue.
Thanks!

**Comment by typicode** [comment]
Glad it worked :+1: :)
