### ISSUE TITLE
Where do I save the index.html block the index page.

### ISSUE THREAD

**Issue by SimonFearby** [typicode/json-server#466]
When I hit the index of the fake API I get a placeholder page that lists the fake API endpoints.  The page says to create a ./public but this seems to be ignored as I have created one in the project folder, node global and global node packages folders.

> To replace this page, create an index.html file in ./public, JSON Server will load it.

Thanks in Advance

**Comment by typicode** [comment]
Hi @SimonFearby,

Could you try this:

```sh
my-project$ mkdir public
my-project$ echo hello > public/index.html
my-project$ json-server db.json
```

You should get `hello` when going to http://localhost:3000.
Let me know if it doesn't work.

**Comment by cfjedimaster** [comment]
I'm testing this out today and nothing in public seems to work.

**Comment by cfjedimaster** [comment]
I should add, specifying `-s public` seems to work. The default seems to not work.

**Comment by typicode** [comment]
Thanks for the report, it's a bug. I'll fix it and update.
