### ISSUE TITLE
Allow the use of nested resource key

### ISSUE THREAD

**Issue by ingro** [typicode/json-server#47]
Hello and thanks for your great work!

I have a little problem. We use a structure like this:
```json
{
  "data": [
    {
      "id": 1,
      "name": "John"
    },
    {
      "id": 2,
      "name": "Jake"
    },
  ],
  "meta": {
    "total": 2,
    "page": 1
  }
}
```

Now I can write the structure in my generate.js with the "data" and "meta" keys and it return correctly when I call **/user**.

Anyway when I try to get a single element of the collection, say **/user/1**, it returns me an empty object with a 404 http code.

I understand that this is a non-conventional request, but do you think that a situation like that could be handled via some config file or options passed to the CLI?

Thank you.

**Comment by typicode** [comment]
Hi Ingro, always happy to know my projects are appreciated, thanks :)

Not really sure to undersdand your example, because I don't see `user` in your code? What does `generate.js` outputs and how do you get `/user`?

**Comment by typicode** [comment]
Oh I think I'm getting it. When you get `/user`, the response is the structure you've shown:

```javascript
{
  "data": [
    {
      "id": 1,
      "name": "John"
    },
// ...
```

And because user list is in `data`, you can't get `/user/1`.

**Comment by ingro** [comment]
Yeah sorry it wasn't clear on the first thought, that was the response I expect from the server. I need the ```meta``` data to manage the pagination on the client application, but as you guessed I can't get a specific user structuring the data generation in this way.

**Comment by typicode** [comment]
Thanks, good choice for Radiohead :)

Unfortunately, I don't see a way to use that kind of structure with this project. It would mean creating some all new routes.
And POST, DELETE would need to update the meta properties too.

The current approach in JSON Server for pagination, is to use `_start`, `_end` query parameters and the `X-TOTAL-COUNT` header.

Sorry about that.

Maybe you can have a look at [dyson](https://github.com/webpro/dyson) or [interfake](https://github.com/basicallydan/interfake).

Also, I think it wouldn't take too long to create a custom fake server using Express. Actually, if you look at `src/router.js` you'll see that the code is quite simple.

Hope it will help.

**Comment by ingro** [comment]
Well thanks for your suggestions, I will look at the resources you linked me, I think you can close this issue, keep up the good work! :D
