### ISSUE TITLE
Get denormalized data (as in, data with relationships) without the server?

### ISSUE THREAD

**Issue by tylercollier** [typicode/json-server#480]
I was hoping I could use some portion of this library (or lowdb?) to get denormalized data, but not via an API call, just in the browser. When I'm prototyping laying out the data in a web app, I want access to the data quickly, without having to write the API calls. I started using lowdb in the browser to do this before I realized it doesn't denormalize for me.

For example, using the example posts and comment data from this project, I'd like to do something like this in React:

> Note my use of a ficticious `expand` method to get the `comments` relationship of `posts`. The "expand" idea exists in json-server but not in lowdb.

```
import myJsonData from './myData.json'
import { inMemoryRestApi } from 'json-server'

const api = inMemoryRestApi(myJsonData)

class MyReactClass extends React.Component {
  render() {
    {api.get('posts').expand('comments').map(post => {
      return (
        <div key={post.id}>
          Post title: {post.title}
          Number of comments: {post.comments.length}
        </div>
       )
    })}
  }
}
```

The benefit here is it's even faster rapid prototyping. I can get the data in the denormalized form that _would_ have come from the json-server API, without actually having to write the code to make the API calls.

Is this possible? Otherwise, this is a feature request :-)

**Comment by tylercollier** [comment]
I updated my original post to include "> Note my use of a ficticious `expand` method to get the `comments` relationship of `posts`. The 'expand' idea exists in json-server but not in lowdb." That's the critical piece. The example you gave doesn't get me the comments relationship.

I understand I can use lodash to denormalize the data myself, which is what I did as a work-around. But then there's no need for json-server or lowdb at all. Here's what I did for now:

```
import jsonData from '../data/db';
const postsWithComments = jsonData.posts.map(post => ({
  ...post,
  comments: filter(jsonData.comments, { postId: post.id })
}))
```

**Comment by Nilegfx** [comment]
Thanks for the emphasising the `expand` need.
If you want to use it as in-application-memory mocks I think your work-around is better than running `json-server` . 
What I understand is: `json-server`'s main job is to simulate restful "network" API calls. therefore I think it is better to discuss it as a relationship feature in lowdb not in json-server

**Comment by tylercollier** [comment]
I agree that using json-server in my browser doesn't make sense. But I was hoping some portion of it could be extracted, specifically the portion that handles the relationships. That portion exists in this library and not lowdb, right? I will have a look at json-server's source code to see if I can find the relevant "relationship" code, but if you have any pointers on where to look, that'd be useful.

**Comment by Nilegfx** [comment]
[HYG] (https://github.com/typicode/json-server/blob/master/src/server/router/plural.js)

**Comment by Nilegfx** [comment]
[HYG](https://github.com/typicode/json-server/blob/master/src/server/router/plural.js)

**Comment by tylercollier** [comment]
Thanks! I won't be able to look for two days, but I glanced and that looks like the right stuff so I'll consider the matter closed.
