### ISSUE TITLE
config option to change "./public" folder?

### ISSUE THREAD

**Issue by jessycormier** [typicode/json-server#485]
Would it be possible to add an option to the config which would allow the public folder to be something else?

for example

`{
    "staticFileServerDir" : "./build"
}`

Or perhaps it could be turned on/off.
`{ "staticFileServer" : false }`

In dev we have a ./public folder which is used by another process. This json-server serve the files in that folder instead of showing the beautiful default landing page :)

**Comment by typicode** [comment]
Hi @jessycormier,

Have you tried `static`?
It should work the same as `--static`

**Comment by jessycormier** [comment]
I read over this section in the documentation, Thank you very much for pointing it out!

**Comment by typicode** [comment]
You're welcome :)

**Comment by PLQin** [comment]
```bash
const path = require('path')
const jsonServer = require('json-server')
const apiServer = jsonServer.create()
const apiRouter = jsonServer.router(router)
const middlewares = jsonServer.defaults(
  {
    static: path.join(__dirname, 'static')
  }
)
```
