### ISSUE TITLE
What's the way to programmaticaly reset (or seed) the database file?

### ISSUE THREAD

**Issue by paulvanbladel** [typicode/json-server#486]
Really very nice project !
I want to expose a reset endpoint which could, for test purposes, reset the database to a particular state.
What's the way to go?
Thanks in advance.

**Comment by typicode** [comment]
Hi @paulvanbladel,

Thank you :) glad it's helpful.

You can do `router.db.setState(newObject)` (see https://github.com/typicode/lowdb#api).
Be careful though, it will write the new state to `db.json`.

**Comment by bahmutov** [comment]
For anyone looking for reset - I have implemented this as a middleware https://github.com/bahmutov/json-server-reset For example if we want to reset our database to have empty list of todos

```json
{
  "todos": []
}
```

Then we can do

```
npm install --save json-server-reset
json-server data.json --middlewares ./node_modules/json-server-reset
http POST <json server url>/reset todos:=[]
```
