### ISSUE TITLE
data not save ?

### ISSUE THREAD

**Issue by Kavan72** [typicode/json-server#494]
i  deploy this project to heroku and after i put some data. but after some time data will not saves that lost from server ?

**Comment by bitstrider** [comment]
hey @Kavan72,

Heroku uses an ephemeral filesystem, meaning changes to any files in your application are temporary will not be saved.  For more info:

[https://devcenter.heroku.com/articles/dynos#ephemeral-filesystem](https://devcenter.heroku.com/articles/dynos#ephemeral-filesystem)

**Comment by Kavan72** [comment]
Then how to save this any example to save file in heroku .like any command
