### ISSUE TITLE
Host in Azure

### ISSUE THREAD

**Issue by nnguyen77** [typicode/json-server#495]
Hi! Can we host deploy this API to Azure? Or it is can be used locally? Thanks

**Comment by fleskesvor** [comment]
If you can run Node.js applications on your server and it has a public facing IP address, there's no reason why you shouldn't be able to deploy a json-server API there.

**Comment by fela98** [comment]
Shouldn't this be closed?

**Comment by typicode** [comment]
You're right, thank you :)
