### ISSUE TITLE
Redirect inexistent routes

### ISSUE THREAD

**Issue by RPallas92** [typicode/json-server#499]
Is it possible to redirect inexistent routes? So we can use json-server as a proxy for some routes in the real API, and redirect the others to that API

Note: currently if I request an inexistent route, JSON-server returns "{}".

Thank you in advance

**Comment by typicode** [comment]
Hi @RPallas92,
Not yet but it's a planned feature.

**Comment by typicode** [comment]
BTW, in case you're using WebPack, you can use it to proxy to JSON Server and redirect inexistent routes.

**Comment by asoneji** [comment]
any update on using json-server as a proxy for some routes?
