### ISSUE TITLE
New Pull Request ! Make this work with also database sqlite and other database 

### ISSUE THREAD

**Issue by Kavan72** [typicode/json-server#500]
can you make this with sqlite and other database ?

**Comment by Kavan72** [comment]
Can you do that or not ?

**Comment by typicode** [comment]
Hi,

It's possible but not out of the box, so it's a little bit hacky.

The best way would be to create a custom [lowdb adapter](https://github.com/typicode/lowdb#how-to-use-a-custom-storage-or-format) for sqlite and then use it with JSON Server.

**Comment by Kavan72** [comment]
Ok thanks you sir , but how to do that
