### ISSUE TITLE
Cconfiguring custom routes.json to support query strings

### ISSUE THREAD

**Issue by shanmohan** [typicode/json-server#503]
i have a resource which has the following default route.

`http://localhost:3000/employees`

i have reconfirugured the route to reflect the intended URL and below routes works fine.
```
{    
    "/api/bo/billing/maintenance/employees": "/employees",
    "/api/bo/billing/maintenance/employees/:id": "/employees/:id",
}
```

However, My resource has to support query string as well. So when i add the below line to the routes.json. i dont see the query string based filtering working.

`   "/api/bo/billing/maintenance/employees?:countryId": "/employees?countryId=:countryId"`

i should be able to call the below URL and filter the records where countrId=3

`/api/bo/billing/maintenance/employees?countryId=3`

i have tried the sample given the documentation, but it doesn't seems to be working.

Any thoughts?

**Comment by BrennerSpear** [comment]
You should be able to call that route regardless, shouldn't you?

Meaning, if you remove ```"/api/bo/billing/maintenance/employees?:countryId": "/employees?countryId=:countryId"```

then ```/api/bo/billing/maintenance/employees?countryId=3``` should work because it's just adding those query params to ```"/api/bo/billing/maintenance/employees": "/employees",``` which should cause it to filter on the ```countryId``` query parameter.

**Comment by typicode** [comment]
Should be fixed by `v0.11.2`
https://github.com/typicode/json-server#add-custom-routes

**Comment by saucey** [comment]
I have a similar issue, please check below:

"/api/v1/schedule\\?id=:id&name=:name": "/getschedule/:id/:name",

How do you use queries with "&" this method doesn't seem to work for me?

**Comment by trkaplan** [comment]
> "/api/v1/schedule\?id=:id&name=:name": "/getschedule/:id/:name",

Have you tried removing escape char(`\`) before question mark? 
`"/api/v1/schedule\?id`
`"/api/v1/schedule?id`
