### ISSUE TITLE
_start is not inclusive as expected

### ISSUE THREAD

**Issue by oleg-smith** [typicode/json-server#505]
`https://jsonplaceholder.typicode.com/posts?_start=1&_end=2` returns record with id=2 whereas it is expected to return one record with id = 1

**Comment by typicode** [comment]
Hi @oleg-smith,

It's actually inclusive, index just starts at 0. It just works as `Array.slice` (but I agree, it's not very intuitive).

```sh
https://jsonplaceholder.typicode.com/posts?_start=0&_end=1 # returns record with id 1
```
