### ISSUE TITLE
How to get rid of [] for single results

### ISSUE THREAD

**Issue by redaxmedia** [typicode/json-server#508]
I'd like to get rid of the wrapped `[]` for results with a single item. At the moment this only works using `/endpoint/1` but even `/endpoint/?id=1` returns a wrapped output.

My custom route looks like this one, it works with an alias:

```
/endpoint/abc => /endpoint/?alias=abc
```

Current output:
```
[
  {
    "id": 1,
    "alias": "abc"
  }
]
```

Wanted output:

```
{
  "id": 1,
  "alias": "abc"
}
```

**Comment by typicode** [comment]
Hi @redaxmedia,

I would suggest using the project as a module and change the output if it's an array with one item:

```js
router.render = (req, res) => {
  const { data } =  res.locals
  if (Array.isArray(data) && data.length === 1) {
    return res.jsonp(data[0])
  }
  res.jsonp(data)
}
```
