### ISSUE TITLE
TypeError: Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by robinvenneman** [typicode/json-server#510]
When trying to add a query parameter with an operator like "?createdAt_like=1491402693000" and the JSON data contains null values, this error is thrown in `node_modules/json-server/lib/server/router/plural.js:122:64`. Any of those `elementValue.toString()` calls could throw if they are tested against `null`.

I also noticed there is probably no way to use _like or _ne with `null` as value because there's no way to distinguish it from the string `"null"`.

**Comment by typicode** [comment]
Hi @robinvenneman,

Thank you for raising this issue. I've added a test and fix.
It should be available in JSON Server next release.

You're right about `"null"`, maybe a new operator would solve that `?title_is_null&body_is_null`.

**Comment by robinvenneman** [comment]
Cool, thanks @typicode. 

A new operator could be useful. I've forked this for a client project to match their API and customised the query params by using JSON with operators, which allows to distinguish strings from other values like `false` or `null`... might be another idea for a future version.

**Comment by sasikumardr** [comment]
Hi @typicode Just wanted to check with you about updates on this changes? I believe this has not yer added to json-server
