### ISSUE TITLE
Is it possible patch a collection

### ISSUE THREAD

**Issue by betorobson** [typicode/json-server#511]
I would like to patch a collection, is it possible? 
For example:
[PATCH] /posts/
[
{"id":1, "title":"new title"},
{"id":2, "title":"new title"},
{"id":3, "title":"new title"}
]

It will patch 3 posts title.

**Comment by betorobson** [comment]
Ok, I managed it by my self changing the JSON DB. This is what I did:

```javascript
		modules.server.patch('/posts/', (req, res) => {

			var response = [];

			if(req.body.constructor === Array){
				req.body.map(function(item){
					if(postDB[item.id]){
					response.push(Object.assign(
						postDB[item.id],
						item
					));
				});
			}

			res.json(response);

		});
```

**Comment by rbjs** [comment]
Are there any updates on patching collection?

I got error 404 requesting i.e. [PATCH] /posts/.
