### ISSUE TITLE
server.use should match exact route name 

### ISSUE THREAD

**Issue by rchod** [typicode/json-server#517]
I have two routes 
route_1: /api/projects/:id/quotas
route_2: /api/projects

when I do 

```
server.use('/api/projects', function (req, res) {
  if (req.method === 'POST') {
    req.body.created          = new Date();
    next();
  }
  if (req.method === 'GET') {
    var projects = router.db
    .get('projects')
    .value();
    res.jsonp({"projects": projects});
  }
});
```
and call /api/projects/54/quotas I get the projects objects not the quotas but when I remove the above code I get the quotas

If the url is  /api/projects/54/quotas why does it execute the code inside server.use('/api/projects'...

**Comment by BrennerSpear** [comment]
What order are they in? I think that matters

**Comment by rchod** [comment]
@BrennerSpear Yes you're right, it was a matter of order.
