### ISSUE TITLE
Does json-server for prototyping only?

### ISSUE THREAD

**Issue by kodekrendel** [typicode/json-server#524]
Hi. Does json-server is for prototyping purpose only? I want to implement simple JSON API server for content. Not mock-up, for production. Does json-server good for that? What you can recommend then?

**Comment by typicode** [comment]
Yes, mainly. Some people are using it for more but It really depends on your case.

If you're doing mostly read without too much traffic and you're using it for a hobby project, it's fine.
If you add caching in front of it, it's even better.

A few things that you need to be aware of:
- You can't scale it more than 1 core. In other words, you can't have multiple instances of Node running the same JSON Server.
- JSON Server uses file system to store database and heroku, for example, doesn't support it.
- You would need to handle database backups yourself.
- If your database is going to be big (10+MB), it won't be performant.

On the other side, if you want to be safe, plan to scale or if your data is critical, I really recommend relying on a classical database like MongoDB, PostgreSQL or Firebase.

As an example, http://jsonplaceholder.typicode.com is serving many requests but it's read-only.
