### ISSUE TITLE
Add delay when using module 

### ISSUE THREAD

**Issue by pantchox** [typicode/json-server#534]
Currently delay is supported on CLI, how can i add this option when using a module?

thanks.

**Comment by betorobson** [comment]
Do this mate:

require connect-pause module:
```javascript
var pause = require('connect-pause');
```
Add after jsonServer.use(middlewares))
```javascript
// pause in ms
jsonServer.use(pause(1000));
```

**Comment by pantchox** [comment]
thanks!

**Comment by ChenReuven** [comment]
> Do this mate:
> 
> require connect-pause module:
> 
> ```js
> var pause = require('connect-pause');
> ```
> 
> Add after jsonServer.use(middlewares))
> 
> ```js
> // pause in ms
> jsonServer.use(pause(1000));
> ```

you are da men! :)
