### ISSUE TITLE
how do i prevent POST data from creating entity in db.json?

### ISSUE THREAD

**Issue by fsw0422** [typicode/json-server#535]
so it seems that this action is a default behavior but if I try to mock a certain request (let's say signin action which is a POST request) the request gets automatically saved in file and starts piling up. I don't want to include this file in .gitignore since it should be updated and all other devs should be able to access it. what can be my solution?

**Comment by aberonni** [comment]
@fsw0422 I have the same request, did you manage to find a solution?

@typicode can you help us out here?

**Comment by likun7981** [comment]
You can use `js` file that is exports a `object`(json)

**Comment by fsw0422** [comment]
I just started using my json server for only GET purpose for mocked data. implementing POST just turns out im writing a new API server
