### ISSUE TITLE
Cannot create items when json-server is mounted on an existing Express Server

### ISSUE THREAD

**Issue by ingro** [typicode/json-server#54]
Hello! I've mounted json-server on an existing Express Server in this way:

```javascript
var express = require('express');
var jsonServer = require('json-server');

var app = express();
app.use(express.static(__dirname + '/public'));
app.set('view engine', 'jade');

// Route index
app.get('/', function (req, res) {
	res.render('index');
});

var router = jsonServer.router(require('./api.js')());

app.use(router);

app.listen(3000, function() {
    console.log('Static server and APIs listening on port 3000');
});
```

Now when I call a POST route on this server I receive this error:

```
TypeError: Cannot read property 'id' of undefined
    at Function.module.exports.insert (D:\projects\api\node_modules\json-server\node_modules\underscore-db\src\index.js:45:12)
```

While if I start json-server stand alone `json-server api.js` everything works as expected and I receive the newly created items as reponse.

I've made some mistakes with my Express server? Is there a better way to integrate json-server with Express? Thank you.

**Comment by typicode** [comment]
Hi @ingro,

Thanks for raising the issue, you were doing it right. 
I've released `v0.6.4` that should fix it.

Actually, the problem was that `body-parser` middleware was needed by the router and it was only present in `jsonServer.create()`. I've moved it to the router so it should be good now.

**Comment by ingro** [comment]
Thank you sir, now it's working fine! :)

**Comment by typicode** [comment]
Great :)
