### ISSUE TITLE
Id auto increment

### ISSUE THREAD

**Issue by rgmez** [typicode/json-server#552]
Is posible to create autoincrement int id?

**Comment by brauliodiez** [comment]
Just saw this issue, why is closed? is already and easy way to do this? Thanks

**Comment by brauliodiez** [comment]
Got it, it automatically takes care of that in a POST :)

https://egghead.io/lessons/javascript-creating-demo-apis-with-json-server

**Comment by HowMade** [comment]
It's also easy to add increment int id manually. The automatical adding id is weird for people encounter it first. And you do not got it beacuse it automatically generates a random id, not a int id.
