### ISSUE TITLE
Add delay

### ISSUE THREAD

**Issue by diegoleme** [typicode/json-server#56]
Add delay option to return requests. Just to be able to test in a more real way.

**Comment by typicode** [comment]
Thanks for the issue. I've thought about that. But since you can throttle now network using Web Inspector in Chrome (I think you can do it with other browser too). So not sure what it would add.
Does the Web Inspector solve your problem?

**Comment by diegoleme** [comment]
Yes! The Web Inspector resolve! :)

Thanks for the lib! It's amazing!!!

**Comment by typicode** [comment]
Thanks for the nice comment :)
I like to create tools for developers, so feel free to check my other projects.
