### ISSUE TITLE
Cannot find module '../lib/cli/bin' ?

### ISSUE THREAD

**Issue by andreGarvin** [typicode/json-server#564]
This my first time trying out json-server, I wanted to contribute this awesome project, as I ran this command I found this error appeared:

module.js:327
    throw err;
    ^

Error: Cannot find module '../lib/cli/bin'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.6.1/lib/node_modules/json-server/bin/index.js:2:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

I am guessing this has to do with the CLI integration of your application, as far as running the command. I made node module that can fix this problem, it is called clib. very easy to use and light weight. Also, this module is not much to setup or configure.

**Comment by scotteg** [comment]
I followed Nilegfx's suggestion ("You could also try:") for [this similar issue](https://github.com/typicode/json-server/issues/454) and it resolved the issue for me.

**Comment by NicoHood** [comment]
I have the same issue. I try to package json-server for archlinux, but i get the same error when running the server. I am using the following PKGBUILD to build json-server:

```bash
# Maintainer: NicoHood <archlinux {cat} nicohood {dog} de>
# PGP ID: 97312D5EB9D7AE7D0BD4307351DAE9B7C1AE9161

pkgname='json-server'
pkgdesc="Get a full fake REST API with zero coding in less than 30 seconds (seriously) "
pkgver=0.14.0
pkgrel=1
arch=('any')
url="https://github.com/typicode/json-server"
license=('MIT')
depends=('nodejs')
makedepends=('npm')
source=("${pkgname}-${pkgver}.tar.gz::https://github.com/typicode/${pkgname}/archive/v${pkgver}.tar.gz")
sha512sums=('9f4a357a8f21a7865c2d03692b6a7c6990e86b4d8d9118560a5205ba52615ce9364b4746db3a7c65f424dd20760ca6d5d654de921ca1733115a608d896b3d1c8')
validpgpkeys=('') # TODO https://github.com/hackerspace-bootstrap/strichliste/issues/277

package() {
    cd "${srcdir}/${pkgname}-${pkgver}"
    export NODE_PATH=/usr/lib/node_modules
    npm install --production -g --user root --prefix "${pkgdir}"/usr "${srcdir}/${pkgname}-${pkgver}.tar.gz"
    rm -rf "${pkgdir}"/usr/etc

    install -d "${pkgdir}/usr/share/licenses/${pkgname}"
    ln -s "../../../lib/node_modules/${pkgname}/LICENSE" "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"

    # Fix npm derp
    find "${pkgdir}/usr" -type d -exec chmod 755 '{}' +
}
```
