### ISSUE TITLE
API Pagination, Filtering and Relationship

### ISSUE THREAD

**Issue by diegoleme** [typicode/json-server#57]
What do you think of implementing the standards?
- [Pagination](http://jsonapi.org/extensions/#profiles)
- [Filtering](http://jsonapi.org/recommendations/#filtering)
- [Relationship](http://jsonapi.org/recommendations/#urls-relationships)

**Comment by typicode** [comment]
That's a very good question.
You can already do pagination, filtering and relationship with JSON Server:

- Pagination using `_start` and `_end` slicing params
- Basic filtering using `prop=someval`
- Relationship up to one degree /posts/1/comments

But all are very basic. Do you need more?

About JSON API spec, I think it's really a great project. However, there are other specs as well, like [Swagger](http://swagger.io/).

So, personally for the moment, I prefer to stick with something basic and without too much strong opinions.

But, if you need specifically a JSON API standard, there's [https://github.com/fortunejs/fortune](fortune.js) which implements it.

Maybe an adapter for [lowdb](https://github.com/typicode/lowdb) which is the DB behind JSON Server would bring the best of both worlds.

**Comment by diegoleme** [comment]
You say create an adapter the lowdb for fortune js?

**Comment by typicode** [comment]
Actually, I may not have been very clear with my thoughts ^_^

So, JSON Server is lowdb + an Express router.
lowdb is what lets you have a simple JSON file as a database.

I was thinking that if there was a lowdb adapter for Fortune as there is for MongoDB, SQLite, ... that would create an experience similar to JSON Server (where you can use a text editor to edit the database) but with an API that follows the JSON API standard.

But, after giving a second thought. I'm not sure it's worth the effort if you just need a JSON API back-end.
So, I think the best would be to stick to Fortune only and forget about what I said. There may be other modules implementing JSON API as well.

Hope it makes more sense?

**Comment by diegoleme** [comment]
I think VERY interesting the way the json-server. Run without extra configuration and using json.

Fortune is another amazing tool, more complete, but requires a pre config.

Join the simplicity of json-server with the power of fortune. I think it would be amazing.

I am willing to code something

**Comment by robcolburn** [comment]
@typicode - weird your link above got messed up by Markdown, copy-paste fixed it
Fortune: https://github.com/fortunejs/fortune
