### ISSUE TITLE
env: node\r: No such file or directory on OS X

### ISSUE THREAD

**Issue by czebe** [typicode/json-server#571]
There's seems to be a linebreak error in node_modules/.bin/json-server:
0.10.2 fails to run on OS X.

Changing the linebreak type fixes the error.

**Comment by typicode** [comment]
Thanks a lot for the heads up, it should be good in `v0.10.3`.
I've transpiled code and published on Windows, must have missed something.

**Comment by czebe** [comment]
Cheers, works like charm!
