### ISSUE TITLE
Use custom reply for POST

### ISSUE THREAD

**Issue by deniseBrise** [typicode/json-server#574]
I currently need to use POST instead of GET on a server. Is possible to use json-server with following behaviour :
a POST don't overwrite db.json, and return same result as GET would have done.

Thanks in advance for your answer

**Comment by stelioschar** [comment]
@deniseBrise did you finally manage this issue?

**Comment by deniseBrise** [comment]
Sorry no,  I have gave up. But I still interested in the solution (if
already possible).
Thanks

Le 20 juil. 2017 06:45, "Stelios Charmpalis" <notifications@github.com> a
écrit :

**Comment by chiptus** [comment]
see #453

**Comment by MickL** [comment]
@deniseBrise Can you close this in favor of #453 ?

**Comment by deniseBrise** [comment]
closed in favor of [453](https://github.com/typicode/json-server/issues/453)
