### ISSUE TITLE
Custom routes filtering not working

### ISSUE THREAD

**Issue by shikaan** [typicode/json-server#577]
Hi everyone!
I'm having some trouble with access to nested resources.

I'd like to query `api/users/:user_id/searches` in order to query all the searches of a user. When I do `GET searches?user_id=123` everything is fine, but when I do `GET api/users/123/searches` json-server's response is not filtered by `user_id` and also search with different `user_id` are shown. What am I missing?

Thank you in advance,
Manuel

_routes.json_
```json
{
  "/api/": "/",
  "/api/users/:user_id/searches": "/searches?user_id=:user_id"
}
```
_db.json_
```json
{
	"searches": [
		{
			"id": 1,
			"user_id": 123,
			"type": "by-destination",
			"params": {}
		},
		{
			"id": 2,
			"user_id": 123,
			"type": "by-destination",
			"params": {}
		},
		{
			"id": 3,
			"user_id": 121,
			"type": "by-destination",
			"params": {}
		}
	]
}
```

**Comment by typicode** [comment]
Hi @RobertBernstein,

Thanks for the help.

You can find them in the CHANGELOG file and I bump the minor version when there's a breaking change :)
https://github.com/typicode/json-server/blob/master/CHANGELOG.md#0110---2017-07-05

**Comment by RobertBernstein** [comment]
Thank you, @typicode!  I just missed seeing that.  I'll keep that in mind for the future.
