### ISSUE TITLE
Return 404s?

### ISSUE THREAD

**Issue by venning** [typicode/json-server#58]
Any way to add a setting/feature that would return 404 status codes instead of `[]` for unmatched GET requests?  I imagine that the 200 response is useful for most people, but it would aid rapid development with `json-server` if we knew that we mistyped something.

My specific use case is in leveraging the `./public` static file serving feature and not getting warnings that we're looking for something that doesn't exist yet.

**Comment by typicode** [comment]
Hi @venning,
You're right, I'll add that.

**Comment by venning** [comment]
Thanks.  Also, json-server is awesome.

**Comment by typicode** [comment]
Thanks for the comment. Glad you like it :)
Just released in `v0.6.8`, if you try to make a GET on /somethingundefined you should get a nice 404.

**Comment by venning** [comment]
Fantastic.  No more `"favicon.ico": []` noise.

**Comment by typicode** [comment]
You're welcome.
