### ISSUE TITLE
Middleware priority 

### ISSUE THREAD

**Issue by Jan0707** [typicode/json-server#585]
Hey folks,

I've just added a bit of middleware via the cli option and thus learned, that the middleware is apparently being called, before any data is being fetched from the db. (I concluded that from the basically empty response object I received in the middleware function).

Is there a way to have my middleware called after the data has been fetched and have it manipulate the response object before its being returned to the client ?

I would like to implement custom referencing behaviour and figured that would be the way to go. If there is any other/better approach, I'm open to that as well.

Best regards !

**Comment by typicode** [comment]
Hi @Jan0707,

Would that do the trick for you?
https://github.com/typicode/json-server#custom-output-example

It's not part of the CLI options though.
