### ISSUE TITLE
DELETE request with axios

### ISSUE THREAD

**Issue by metamorph-online** [typicode/json-server#593]
Is it possible to update or delete elements from .json file with the simple axios request?

I use react-redux app to access the fake API on json-server.  I can get data in my action component with 

const url = `http://localhost:3000/db/`;
const request = axios.get(url);

but when I try to add or delete something I get 404 in server and nothing happens.

const url = `http://localhost:3000/db/`;
const request = axios.delete(url);

Is it possible at all or I have to use some libraries to do that?

**Comment by laistomazz** [comment]
It's possible, but you need to point the id of the item you want to delete

`axios({
  method: 'DELETE',
  url: `http://localhost:3000/posts/1`,
  headers: { 'Content-Type': 'application/json' },
})`

This will delete the first post

**Comment by metamorph-online** [comment]
ok, delete is working with the id of the book I want to delete but I cannot make POST requests to add comments about the book...
my post request look like thiss: let request = axios.post(http://localhost:3000/books/978-0641723445, {comment : myComment});

Errors I get: 
bundle.js:29542 POST http://localhost:3000/books/978-0641723445 404 (Not Found)
dispatchXhrRequest @ bundle.js:29542
xhrAdapter @ bundle.js:29376
dispatchRequest @ bundle.js:30036
Promise resolved (async)
request @ bundle.js:29213
Axios.(anonymous function) @ bundle.js:29233
wrap @ bundle.js:29120
AddComment @ bundle.js:28615
(anonymous) @ bundle.js:20710
submitHandler @ bundle.js:59475
onClick @ bundle.js:59518
callCallback @ bundle.js:3240
invokeGuardedCallbackDev @ bundle.js:3279
invokeGuardedCallback @ bundle.js:3136
invokeGuardedCallbackAndCatchFirstError @ bundle.js:3150
executeDispatch @ bundle.js:3534
executeDispatchesInOrder @ bundle.js:3556
executeDispatchesAndRelease @ bundle.js:3654
executeDispatchesAndReleaseTopLevel @ bundle.js:3665
forEachAccumulated @ bundle.js:3633
processEventQueue @ bundle.js:3805
runEventQueueInBatch @ bundle.js:6300
handleTopLevel @ bundle.js:6309
handleTopLevelImpl @ bundle.js:6040
batchedUpdates @ bundle.js:13766
batchedUpdates @ bundle.js:5023
dispatchEvent @ bundle.js:6114

bundle.js:29599 Uncaught (in promise) Error: Request failed with status code 404
    at createError (bundle.js:29599)
    at settle (bundle.js:29569)
    at XMLHttpRequest.handleLoad (bundle.js:29441)

although I can access http://localhost:3000/books/978-0641723445 with the browser and get book info. Is it possible because my project is located on localhost:8080 ?

**Comment by laistomazz** [comment]
If you want to edit a certain item, you should use PUT,  not POST.
Also, you will have to send the full item as the data (in your case, the book info plus the new comment), you cannot update only one node from the item.

**Comment by pasupuletics** [comment]
@metamorph-online , this should work.
```javascript
const url = 'http://localhost:3000/posts/1',
axios.delete(url)
```
we have to mention route name(in this case` posts`) and record id that is`1`

**Comment by pasupuletics** [comment]
@metamorph-online for `post` request we need not to pass `id` value. url should be `localhost:3000/books`.

**Comment by metamorph-online** [comment]
guys, thank you for your answers and all the help but I wrote API on php for my react/redux app. turned out it would be faster and more clear to me then fight with json-server.

**Comment by harsh-vankar815** [comment]
i used axios to send requests on the json server, get and post requests are working correctly but when i am trying to send put, patch, and delete request it will gives me an error which is 404 not found. How can I solve this problem, and I think this problem can be inside of the json-server package. Please give me the all ways to solve this problem in my react application. I created json server by using this command "npx create json-server -p 3000 -w json/db.json"
