### ISSUE TITLE
"_sort" doesnt work

### ISSUE THREAD

**Issue by pantchox** [typicode/json-server#599]
I tried with many different fields with asc/desc and it just does not work.

Thanks
@typicode

**Comment by toumas** [comment]
It's actually _order that's causing the problem here. Try capitalizing the asc or desc like so: /comments?_sort=id&_order=DESC

**Comment by pantchox** [comment]
thanks! it did the trick, i am not closing it since i think it is still a bug.

**Comment by david-bc** [comment]
https://github.com/typicode/json-server/pull/669
