### ISSUE TITLE
How to serve image files?

### ISSUE THREAD

**Issue by vko-online** [typicode/json-server#60]
Sample image link `http://localhost:3000/assets/images/coffee/large/coffee.gif` not working with json-server, it's not possible to server static assets? (script files, css styles, images)
Or is there any way to plug `sharp` (image resizer node package) into json-server

**Comment by typicode** [comment]
To serve static assets, simply create a `./public` directory.

For example:

```bash
$ mkdir -p public/assets/images
$ echo "hello world" > public/index.html
$ json-server db.json
```

If you need more, you can use `json-server` as a module.

```javascript
var jsonServer = require('json-server')

var object = {
  posts: [
    { id: 1, body: 'foo' }
  ]
}

var router = jsonServer.router(object) // Express router
var server = jsonServer.create()       // Express server

server.use(router)
server.listen(3000)
```

You can add middlewares or custom routes as you would do in an Express server. You can even embed `json-server` router in an existing Express server.

Does that help?

**Comment by typicode** [comment]
Closing for the moment. Feel free to reopen if needed.

**Comment by ponnex** [comment]
I'm new to this thing and would like to ask for advice what would I'll do for windows? tried putting public directory but no luck. Thanks! :D

**Comment by abyabraham** [comment]
Hi typicode,
Would you please elaborate a little on the above solution .I am totally new to this.
-Aby

**Comment by bluemix** [comment]
after you add images to your `public/assets/images` directory,
you can get an image like
```http://localhost/assets/images/truck-4.png```

**Comment by buildAll** [comment]
@camilodelvasto Thanks, it helps me get the images from json server. And for anyone else who comes here, please be aware that the folder name must be public. Then load images like this: http://localhost:3000/assets/images/abc.png

**Comment by mguilhermetavares** [comment]
after I add images to my public/assets/images directory,
and add a Custom route like:
```JSON
{
    "/api/test":"/assets/images/test.png"
} 
```

server return NOT FOUND 404: 
```
GET /api/test 404 1.770 ms - 2
```

but I can access by the full path:
http://localhost:5000/assets/images/test.png -->> 200 OK

**Comment by vickyru** [comment]
@mguilhermetavares any idea how it will work with custom routes also? Facing same issue as you but not able to figure out solution.

**Comment by vickyru** [comment]
@camilodelvasto i used same code as you have given for my middleware  file but while trying to up the json server getting error as below.
Command runed:
 json-server .\mock-server\data\report.json -m .\mock-server\router.js
Error:
  \{^_^}/ hi!

  Loading .\mock-server\data\report.json
  Loading .\mock-server\router.js
  Done
TypeError: app.use() requires a middleware function
    at Function.use (E:\user\forked\reporting-ui\node_modules\express\lib\application.js:210:11)
    at createApp (E:\user\forked\reporting-ui\node_modules\json-server\lib\cli\run.js:74:9)
    at load.then.db (E:\user\forked\reporting-ui\node_modules\json-server\lib\cli\run.js:132:13)
    at <anonymous>

**Comment by vijeth11** [comment]
I have put my images in public/assets/images path 
still I am not able to get image in http://localhost:3000/assets/images/uthappizz.png

**Comment by Gabrielfcs** [comment]
If you are using public/assets/images and all of your images are inside this folder for example, the uri will be http://localhost:3000/image.jpg not http://localhost:3000/public/assets/images/image.jpg

**Comment by pavan-code** [comment]
Images are loading in the local json-server. But when I'm hosting the json server using git repo, images are not accessing. Can anyone tell me how to access the same images through git fake api repo.

**Comment by ank1t** [comment]
as of v 0.17.0, if the image files are placed in ./public/assets/images/ they can be accessed using http://localhost:3000/assets/images/{imagename}

**Comment by valentinesamuel** [comment]
I totally agree with @ank1t @buildAll . I had an svg file called **_jerome.svg_** in my _**public/asset/images folder**_. When i wanted to get the file, i used [http://localhost:3000/assets/images/jerome.svg](http://localhost:3000/assets/images/jerome.svg)

**Comment by dertanzer** [comment]
It's working fine, though I am not sure why but the images are served as document in the response header and not as image/jpg... which is problematic.
