### ISSUE TITLE
Let IDs be strings as well

### ISSUE THREAD

**Issue by iamale** [typicode/json-server#61]
For example, I want usernames to be user IDs, like `/users/iamale`.

**Comment by typicode** [comment]
Hi Ale,

Thanks, it's a bug. I did a quick fix in `v0.6.9`, so:

```javascript
{
  users: [ { id: 'iamale' } ]
}
```

should work now with `/users/iamale`.

However, new users will have a `uuid` generated id.
Do you need to customize newly created ids?

**Comment by iamale** [comment]
Sorry for not responding to this :(
I think it is fine now, thanks!

**Comment by typicode** [comment]
No worries :)
