### ISSUE TITLE
How to set options as a module

### ISSUE THREAD

**Issue by joeruhl** [typicode/json-server#613]
For example, using CLI I can set many options including the routes and delay as follows:

`json-server db.json --routes routes.json --port 8008 --delay 1000`

But using json-server as a module, there is no documentation on how to do this. The only way I found to set the routes is to copy-paste the content of my routes.json file in the code as follows:

`server.use(jsonServer.rewriter({
    '/api/spots/:id/media': '/mediaAssets/:id',
    '/api/spots/:id': '/spots/:id',
    '/api/spots*': '/spots',
    '/api/spotIds*': '/spotIds'
}));`

How do I set the delay option, or any other option for that matter?

**Comment by joeruhl** [comment]
I found how to set the delay. This requires installing the connect-pause package, which is also used in the json-server code (https://www.npmjs.com/package/connect-pause):

`npm install connect-pause`

Then on the server.js file, I added the following a require('connect-pause') and used it in the json server app. Here is my code:

```
const fs = require('fs');
const pause = require('connect-pause');
const jsonServer = require('json-server');
const server = jsonServer.create();
const router = jsonServer.router('db.json');
const middlewares = jsonServer.defaults();

server.use(middlewares);
server.use(jsonServer.bodyParser);

//
// Define custom routes (routes.json)
//
var routes = JSON.parse(fs.readFileSync('routes.json'));
server.use(jsonServer.rewriter(routes));

...

server.use(pause(1000));
server.use(router);
server.listen(8008, () => {
  console.log('JSON Server is running');
});

```

**Comment by marcaltmann** [comment]
Is there any way to set the "id" option when using json-server as a module?

**Comment by joeruhl** [comment]
I updated the above code to include the id option. See if this works for you:

```
const fs = require('fs');
const pause = require('connect-pause');
const jsonServer = require('json-server');
const server = jsonServer.create();
const router = jsonServer.router('db.json');
const middlewares = jsonServer.defaults();

server.use(middlewares);
server.use(jsonServer.bodyParser);

//
// Define custom routes (routes.json)
//
var routes = JSON.parse(fs.readFileSync('routes.json'));
server.use(jsonServer.rewriter(routes));

...

server.use(pause(1000));
router.db._.id = 'myId'; // set id option here
server.db = router.db;
server.use(router);
server.listen(8008, () => {
  console.log('JSON Server is running');
});
```

**Comment by blacksagres** [comment]
@joeruhl great find!

**Comment by blacksagres** [comment]
@typicode I know this is quite specific but would be nice to have it in the documentation. Also on how to set other options as well. 😄

**Comment by joeruhl** [comment]
I believe so, but there is no straightforward or consistent way to set them all. I had to go through the json-server source code to figure out the custom id and delay options.

**Comment by dylanfpaul** [comment]
Thanks for this! I too believe it should be more clear as to the differences in settings options in CLI vs module!
