### ISSUE TITLE
not able to set custom routes

### ISSUE THREAD

**Issue by tremkonzah** [typicode/json-server#615]
Hello 

i am trying to setup custom routes for POST /posts

```
{
  "/api/*": "/$1",
  "/posts/": "/mypath/test"
}
```

submit POST requests to endpoint http://localhost:3000/mypath/test return 404 error code

**Comment by m8r1x** [comment]
Hi @tremkonzah . Have you tried posting to `http://localhost:3000/api/posts/` instead?

**Comment by joeruhl** [comment]
What does your db.json file look like?

You define the custom route on the left side, and define the resource on the right side. I don't think you are allowed to define a resource with multiple levels like "/mypath/test".

**Comment by tremkonzah** [comment]
@joeruhl thank you
