### ISSUE TITLE
whole collection deleted if one of the fieldnames ends with Id

### ISSUE THREAD

**Issue by alaindresse** [typicode/json-server#62]
Hi,
given a database like 
```
"keywords": [
    {
        "id": 0,
        "entity": "messages",
        "entityId": 5,
        "value": "mollit"
    },
    {
        "id": 1,
        "entity": "messages",
        "entityId": 1,
        "value": "consequat"
    }
]
```
if I delete an item with `DELETE /keywords/1`, then all keywords are deleted. If I rename entityId to entityRef, everything is fine.

Is there any way I can specify that entityId is not a foreign key ?

Thanks,
Alain

**Comment by typicode** [comment]
Hi Alain,

Thanks for raising the issue. Unfortunately, not right now. But, it's more a bug than a feature, so I'll fix that.

BTW, do your database contains only `keywords` or you have  an `entity` table?

**Comment by alaindresse** [comment]
Thanks for your answer.

No I don't have an entity table.

I suppose you want to know if you can assume that xxxId is a foreign key if there is a "table" named xxx. I believe it would be a valid assumption.

For info, my current usage of entityId is as follows:
Keywords can be attached to different types of entities - e.g. messages, documents.
```
{
        "id": 0,
        "entity": "messages",
        "entityId": 5,
        "value": "mollit"
}
```
means "molllit" is a keyword for the "messages" entry with id 5, whereas

```
{
        "id": 0,
        "entity": "documents",
        "entityId": 3,
        "value": "consequat"
}
```
means "consequat" is a keyword for the "documents" entry with id 3.

**Comment by typicode** [comment]
Yeah, you read my mind ^^
Ok, I see better how the entity/entityId works, thanks.

**Comment by typicode** [comment]
Just published `v0.6.10`, it should be good.

**Comment by alaindresse** [comment]
Thanks !
I'll check it out later today.

**Comment by typicode** [comment]
Closing for the moment, feel free to reopen if it doesn't work.

**Comment by alaindresse** [comment]
Works fine, thanks !

--

Alain Dresse
Bamboost <http://www.bamboost.org> CEO and co-founder
GSM: +32 478 403027

**Comment by typicode** [comment]
Great :)
