### ISSUE TITLE
Filter on nested object

### ISSUE THREAD

**Issue by StefanDuPreez** [typicode/json-server#622]
Hi,

I am trying to filter based on a nested object, my db.json looks like following

    {
        "menuversion": [
            {
                "id": 1,
                "menuVerId": 1,
                "menuVerDesc": "Version 1",
                "company": {
                    "cpyId": 1
                }
            },
            {
                "id": 2,
                "menuVerId": 2,
                "menuVerDesc": "Version 2",
                "company": {
                    "cpyId": 9
                }
            },
            {
                "id": 3,
                "menuVerId": 3,
                "menuVerDesc": "Version 3",
                "company": {
                    "cpyId": 1
                }
            }
        ],
       "company": [
            {
                "id":1,
                "cpyId": 1,
                "cpyName": "Company 1"
            },
            {
                "id":9,
                "cpyId": 9,
                "cpyName": "Company 9"
            }
        ]
    }

I want to see all the menu versions with the cpyId of 1, is this achievable with the JSON server?
I had a look into the custom routes, but I cannot seem to get it to filter based on a nested object value.

Regards
Stefan du Preez

**Comment by StefanDuPreez** [comment]
I found the answer by actually reading through the readme.
So by using the . in the filter I achieve what I was trying to do

**Comment by dimitraz** [comment]
@StefanDuPreez Hi, can you explain how you did this with your example? I have the same use case and I can't seem to get it to work.

**Comment by StefanDuPreez** [comment]
@dimitraz As the readme states, use a . to filter
in other words, my url looked like the following:

GET *http://localhost:3000/menuversion?company.cpyId=1*

That shows all companies with the company_id of 1
Remember to use the endpoint as normal but reference the company object within the menuversion object.

I hope that helps.

Regards
Stefan du Preez
