### ISSUE TITLE
CI/CD Automated Tests

### ISSUE THREAD

**Issue by jrmcdona** [typicode/json-server#637]
Are we able to run this during a CI/CD tests on the build server?

Not certain if we can spin up the json-server during a test run and shut it down in an automated fashion.

How are others doing this?

**Comment by djhojd** [comment]
Is this [#284](https://github.com/typicode/json-server/issues/284#issuecomment-218406749) answering your question?

**Comment by typicode** [comment]
As @djhojd pointed out, it should be possible to do so if the project is used as a module.
