### ISSUE TITLE
POST & PUT data to db

### ISSUE THREAD

**Issue by Shuunen** [typicode/json-server#64]
Hi,

If I get the readme well, it's possible to use POST and PUT to alter content of the db.json ?

Here is my db & server:
```
// Database
var low = require('lowdb');
low.mixin(require('underscore-db'));
var db = low('db.json');

// Server
var jsonServer = require('json-server');
var router = jsonServer.router(db.object); // Express router
var server = jsonServer.create();          // Express server
server.use(jsonServer.defaults);           // Default middleware (logger, public, ...)
server.use(router);
server.listen(3000);
```
my data in db.json :
```
"posts": [
    {
      "id": 1,
      "title": "json-server",
      "author": "typicode"
    }
  ],
```
and the request I sent with jQuery on client side :
```
$.ajax({
  method: "POST",
  url: "/posts",
  data: {"id": 2, "title": "title test"}
});
```
here is my request visible in chrome dev tools :
```
General :
Remote Address:127.0.0.1:3000
Request URL:http://127.0.0.1:3000/posts
Request Method:POST
Status Code:200 OK

Response Headers :
Access-Control-Allow-Credentials:true
Access-Control-Allow-Origin:http://127.0.0.1:3000
Connection:keep-alive
Content-Length:38
Content-Type:application/json; charset=utf-8
Date:Sun, 26 Apr 2015 21:11:59 GMT
ETag:W/"26-224df703"
Vary:Origin, X-HTTP-Method-Override
X-Content-Type-Options:nosniff
X-Powered-By:Express

Request header :
Accept:*/*
Accept-Encoding:gzip, deflate
Accept-Language:fr,en-GB;q=0.8,en;q=0.6
Connection:keep-alive
Content-Length:21
Content-Type:application/x-www-form-urlencoded; charset=UTF-8
DNT:1
Host:127.0.0.1:3000
Origin:http://127.0.0.1:3000
Referer:http://127.0.0.1:3000/?
User-Agent:Mozilla/5.0 (Windows NT 6.3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36
X-Requested-With:XMLHttpRequest

Form Data :
id:2
title:title test
```
and the response :
```
{
  "id": 2,
  "title": "title test"
}
```

The problem is : db.json is not updated.

It's weird because when I get to http://127.0.0.1:3000/posts I can see the added post :
```
[
  {
    "id": 1,
    "title": "json-server",
    "author": "typicode"
  },
  {
    "id": 2,
    "title": "title test"
  }
]
```
Any idea ?

Thanks :)

**Comment by typicode** [comment]
Hi @Shuunen,

Thanks for raising the issue.
It's missing in the doc, my bad.

You should try something like this:

```javascript
var jsonServer = require('json-server');
var router = jsonServer.router('/some/path/db.json'); // <- use a file path here
var server = jsonServer.create();
server.use(jsonServer.defaults); 
server.use(router);
server.listen(3000);
```

If you pass an object to `jsonServer.router()`, data is modified in memory and not persisted.
If you pass a file path to `jsonServer.router()`, changes will be written to file.

Sorry for the trouble, I'll update the README.

**Comment by Shuunen** [comment]
Yeah works nice !

**Comment by sant123** [comment]
It seems is not working:

![image](https://cloud.githubusercontent.com/assets/7959437/15238692/9e820c50-18a0-11e6-926e-ec5d4b1090f8.png)

I've tested in module and CLI and the data is not persistent, I mean the data is not being stored in db.json.

**Comment by typicode** [comment]
Thank you for the report.

I've updated [lowdb](https://github.com/typicode/lowdb) recently and there are breaking changes in the API. So I think I've not updated JSON Server correctly. Sorry for that, I'll try to fix it today.

For the moment, you can use json-server@0.8.10:

```sh
$ npm install -g json-server@0.8.10
```

You may have a warning about `graceful-fs` but it's a just a warning.

**Comment by sant123** [comment]
Thank you, I'll be waiting for the next release of Json-server ☺. On the other hand I've used this module in the past for ajax testing and I think it's really awesome. Cheers.
