### ISSUE TITLE
support for promise 

### ISSUE THREAD

**Issue by metapraveen** [typicode/json-server#649]
first of all, thank you @typicode for this project, this is one of my favourite tools which makes me more productive.

I always use `json-server` with [jsf](https://github.com/json-schema-faker/json-schema-faker). But with new version of jsf it is async now. So my `index.js` looks like below.
```
var jsf = require('json-schema-faker')
const schema = require('./schema')

module.exports = () => {
  return jsf.resolve(schema).then(data => {
    return { users: data }
  })
}
```
now if I run `json-server index.js` it throws error `Data must be an object. Found object.See https://github.com/typicode/json-server for example`

To support this can we add promise support in `json-server`?
I would be happy to send a PR for this.
Feel free to close this issue if you think its out of scope for `json-server`

**Comment by antipin** [comment]
Any progress on this issue?

**Comment by KingScooty** [comment]
Just stumbled across this issue while also trying to use the latest version of JSON Fake Schema. Would really like this to be supported!

**Comment by upupming** [comment]
async/await is still not supported
