### ISSUE TITLE
How to upload an image to json-server?

### ISSUE THREAD

**Issue by xuyanquan** [typicode/json-server#651]
How to upload an image to json-server? Is there anyway to receive image and save it on server by easy method or API?

**Comment by wangxingxing123654** [comment]
leave it alone

**Comment by xuyanquan** [comment]
ehh~~~ I think so

**Comment by phsantiago** [comment]
Dude, json-server it's to deal with JSON only.

You can store in a base64 string, see https://github.com/typicode/json-server/issues/528#issuecomment-301246568

**Comment by tonyuifalean** [comment]
Any solution, @xuyanquan?

**Comment by xuyanquan** [comment]
There is no answer

**Comment by tavuntu** [comment]
Well, this is old but I agree with @phsantiago that you could store a base64 string. Another solution may be to upload the image to an image host and store the public URL.

**Comment by r2rickards** [comment]
base64 encoded

**Comment by hramdas** [comment]
In react you can get file using let 
`let fileRef = useRef(null)`
  ` let file = URL.createObjectURL(fileRef.current.files[0])`
here file is URL
URL Sample >>  blob:http://localhost:3000/6ab3c928-d659-46e9-b840-36f37c07fca7

**Comment by sanketnchaware** [comment]
> In react you can get file using let `let fileRef = useRef(null)` ` let file = URL.createObjectURL(fileRef.current.files[0])` here file is URL URL Sample >> blob:http://localhost:3000/6ab3c928-d659-46e9-b840-36f37c07fca7


That wont work  on another system if we open that link.

**Comment by kuraiakari** [comment]
> In react you can get file using let `let fileRef = useRef(null)` ` let file = URL.createObjectURL(fileRef.current.files[0])` here file is URL URL Sample >> blob:http://localhost:3000/6ab3c928-d659-46e9-b840-36f37c07fca7

now i have mini project of student. i too have link blob. But i cant read it when use method get of fetch. You have solution for it ? Sr my english very bad :(((
