### ISSUE TITLE
Doc doesn't show how to find specific parameter of _ember relationship

### ISSUE THREAD

**Issue by francisrod01** [typicode/json-server#683]
The documentation doesn't show how to find a specific parameter from a `_ember` relationship.

I try it: https://github.com/typicode/json-server#filter

My http query is below:

```
http://localhost:3001/locations/2/?_embed=locations_transl&locale=es
http://localhost:3001/locations?place_code=xxxxxxxxx&_embed=locations_transl&locale=es
```
* Be careful: `_embed` results is very different of `_expand` results.

The second doesn't show all of results..

Please, I need a help to identify this.

**Comment by Nilegfx** [comment]
@francisrod01 Could you please put some code example or use cases.

**Comment by francisrod01** [comment]
Sure @Nilegfx ! Thank you for your comment! :)

I was trying to access an attribute from a relationship table, without relating this foreign table to a foreign ID.

Example: I was relating a `location table` with `place_id` of Google Places, which is a string, with a `service` table without mentioned a `location_id` (ObjectID or integer field) in  service table.

It was a bad idea, I know, sorry about that!
