### ISSUE TITLE
Setting additional `Access-Control-Expose-Headers`

### ISSUE THREAD

**Issue by richarcher** [typicode/json-server#686]
I have some auth middleware running in a module that attempts to set the `Access-Control-Expose-Headers` and `Authorization` headers:

```js
 ...
  if (someAuthLogic(req)) {
    res.header('Access-Control-Expose-Headers', 'Authorization');
    res.header('Authorization', 'Bearer jwttoken.goes.here');
    next();
  } else {
    res.sendStatus(401);
  }
 ...
```

I find that `'Access-Control-Expose-Headers'` is always overwritten with `Location` seemingly from here: https://github.com/typicode/json-server/blob/master/src/server/router/plural.js#L263.

To get around the issue right now, I've forked the repo and written a function to combine any clashing header values into the single header.. but I can't believe there isn't another way to get around this problem... does anyone have any other solutions?

**Comment by Nilegfx** [comment]
@richarcher 

First of all, Please create a PR with your changes (after adding the corresponding tests) as it is bad to have this hardcoded header. 

alternatively "_still a dirty way_", if you don't want to use special fork of this repo and you know the set of headers you want to expose, you could override the created server response's `.send` method (since it is an instance of [http.ServerResponse](https://nodejs.org/docs/latest-v8.x/api/http.html#http_class_http_serverresponse) you can easily access response headers by [response.*Header(s) methods](https://nodejs.org/docs/latest-v8.x/api/http.html#http_response_getheader_name), an example: 

```js
const jsonServer  = require( 'json-server' );
const server      = jsonServer.create();
const router      = jsonServer.router( 'db.json' );
const middlewares = jsonServer.defaults();

let originalSend     = server.response.send;
server.response.send = function ( body ) {
  let headersToExpose       = [ 'Authorization' ];
  let currentExposedHeaders = this.getHeader( 'Access-Control-Expose-Headers' );

  if ( currentExposedHeaders ) {
    this.setHeader( 'Access-Control-Expose-Headers', headersToExpose.concat( currentExposedHeaders ).join( ',' ) )
  } else {
    this.setHeader( 'Access-Control-Expose-Headers', headersToExpose.join( ',' ) );
  }

  originalSend.call( this, body );

};

//default json-server middlewares
server.use( middlewares );

server.use( ( req, res, next ) => {
  res.header( 'Authorization', 'Bearer 2ee636c8-06b6-474b-b562-f1cde69ea575' );
  next();
} );

server.use( router );

server.listen( 3000, () => {
  console.log( 'http://localhost:3000' );
} );
```

**Comment by Nilegfx** [comment]
My bad, I overcomplicated it, it is as simple as overwriting the `router.render` method: 

```js
const jsonServer  = require( 'json-server' );
const server      = jsonServer.create();
const router      = jsonServer.router( 'db.json' );
const middlewares = jsonServer.defaults();

router.render = (req, res) => {

  let headersToExpose       = [ 'Authorization' ];
  let currentExposedHeaders = res.getHeader( 'Access-Control-Expose-Headers' );

  if ( currentExposedHeaders ) {
    res.header( 'Access-Control-Expose-Headers', headersToExpose.concat( currentExposedHeaders.split(',') ).join( ',' ) )
  } else {
    res.header( 'Access-Control-Expose-Headers', headersToExpose.join( ',' ) );
  }

  res.send(res.locals.data)
}

//default json-server middlewares
server.use( middlewares );

server.use( ( req, res, next ) => {
  res.header( 'Authorization', 'Bearer 2ee636c8-06b6-474b-b562-f1cde69ea575' );
  next();
} );

server.use( router );

server.listen( 3000, () => {
  console.log( 'http://localhost:3000' );
} );
```

**Comment by OndeVai** [comment]
Thanks! This through me though a loop because I forgot the Access-Control-Expose-Headers was even needed for CORS.
