### ISSUE TITLE
PUT merge instead of substitute

### ISSUE THREAD

**Issue by stilllife00** [typicode/json-server#699]
I am trying to send a PUT request with the goal of merging the new props into the existing object instead of substituting the old object entirely. 

Is this possible ? At first I thought this would be the default behavior but it is not apparently.

I have tried using router.db (get, write...) but no luck.

**Comment by Nilegfx** [comment]
I wonder why don't you use the PATCH instead?

nevertheless, you can add simple middleware that changes the method from PUT to PATCH?

**Comment by stilllife00** [comment]
Agreed, Patch is the correct verb to use

**Comment by PLQin** [comment]
```
// here
server.use((req, res, next) => {
  if (req.method === 'POST') {
    req.method = 'GET'
  }
  next()
})

server.use(middlewares)
server.use(jsonServer.rewriter(routes))
server.use(router)
```
