### ISSUE TITLE
How can I get random data

### ISSUE THREAD

**Issue by iulo** [typicode/json-server#70]
I would like some random data. 
I creat db.js:
```javascript
module.exports = function() {
  data = {  };

  data.id = Math.floor( Math.random()*9+1 );
  return data;
};
```

but still return old data
What should I do ?

**Comment by dvidsilva** [comment]
are you running your script like

````
$ json-server db.js
````

**Comment by typicode** [comment]
You need to create it first:

```javascript
// db.js
module.exports = function() {
  data = { users: [] }
  // Create 1000 users
  for (var i = 0; i < 1000; i++) {
    data.users.push({ id: i, name: 'user' + i })
  }
  return data
}
```

You can also use modules like https://github.com/Marak/faker.js or https://github.com/boo1ean/casual to create random data.

**Comment by crswll** [comment]
I've been using mockaroo.com for random data. Nice little UI if you feel like getting something quick and realistic.

**Comment by typicode** [comment]
Good point about mockaroo :+1:  There's [json-generator](http://www.json-generator.com/) that seems pretty popular among JSON Server users too.

By the way, if the service offers a URL for the schema, you don't even need to download the file. JSON Server can load it:

```
json-server http://beta.json-generator.com/api/json/get/FMMNIRS
json-server http://dropbox.com/...
...
```

**Comment by blvz** [comment]
Can I suggest [chance.js](http://chancejs.com)? I think it's pretty awesome.

**Comment by typicode** [comment]
Didn't know chance.js, cool stuff (I've added it to the README alongside other node generators)

**Comment by samuelcotterell** [comment]
I was wondering if its possible to have random data generated for each request? I have copied the random data example provided and added faker, however each time I hit the mock API the same data is returned.

Am I missing something? I just want to simulate polling a server where the data changes.

**Comment by dvidsilva** [comment]
I think you'd have to change it here:
`https://github.com/typicode/json-server/blob/master/src/server/router/index.js`

```
  // GET /db
  router.get('/db', (req, res) => {
    res.jsonp(db.getState())
  })
```

When `get` happens it returns the state of the db, that is set at start time. You'd have to reinitialize the db at every request.

**Comment by samuelcotterell** [comment]
thanks for the reply, I was playing around with that file and the router.get() method is hit when you load up the JSON Server Index page (eg http://localhost:3000/) not when i hit the route (eg. http://localhost:3000/ramp) .

Not sure I follow your approach?
