### ISSUE TITLE
Help with non standard api

### ISSUE THREAD

**Issue by QuantumInformation** [typicode/json-server#700]
I have an api

/items
/items/detail

where the detail contains extra information about a specific item not in just `/items`

db.json:
```js
{
  "items": [
    {
      "id": 1
    },
    {
      "id": 2
    }
  ]
  "detail":{
    "id": 1,
     "foo":2
  }
}

```
routes

I tried this
```js
{
  "/items/:filter": "/item?filter=:filter",
  "/items/foo": "/detail"
}
```
but all my routes go to items, both for
`items?filter=foo `
and
`items/foo `

visiting /detail directly returns the correct item

**Comment by Nilegfx** [comment]
I really want to help you but I can't understand the question. would be helpful if you rephrase it or at least add what do you expect when calling which endpoint.

**Comment by rjoydip** [comment]
@QuantumInformation I think you want to extract property from the output by filtered them (filter=foo), where foo is a property of the detail?

**Comment by mtheoryx** [comment]
Seem like a weird api design, can you provide some more insight?

**Comment by QuantumInformation** [comment]
I'm not working with this client on this project any more, case closed
