### ISSUE TITLE
Custom routing - POST overrides GET data

### ISSUE THREAD

**Issue by ssuperczynski** [typicode/json-server#704]
**Given I have routes.json:**

```
{
  ...
  "/v1/recruitments/:id": "/recruitmentId",
  ...
}
```

and data.json

```
{
  "recruitmentId": {
     "data": {
        id: 1,
        title: "foo"
      }
  },
  ...
}
```

and I started app by `./node_modules/json-server/bin/index.js data.json --routes routes.json`

**When** I do 

`GET /v1/recruitments/1`

**Then** I get:

```
"data": {
  id: 1,
  title: "foo"
}
```

Which is correct. But When I do POST `/v1/recruitments/1`

```
"data": {
  something: 1,
  completely: "foo",
  different: "foo",
}
```

Then `GET /v1/recruitments/1`

```
"data": {
  something: 1,
  completely: "foo",
  different: "foo",
}
```

but I should get 

```
"data": {
  id: 1,
  title: "foo"
}
```

Is it build in behaviour? Or, how can I prevent to override given endpoint by POST, when GET url is the same

**Comment by xRahul** [comment]
POST is used here to `put` some data at `1 recruitmentId`.
What you're doing is this:
1. Get data for id=1
2. Put new data at id=1
3. Get data for id=1

The above 2nd step will overwrite the data at id=1 and you'll get the new data only.

**Comment by zq99299** [comment]
With the question; what should I do to make all the request methods are just the definition of the data, rather than to modify the original data? Because the real business simulation data here is not simulated, so I think it may be very tasteless to change this feature. Most of the time I just need to use different methods of request get, post, put and other access to data, there is a way to achieve only what data?


同问；我要怎么做才能让所有请求方式都只是得到定义的数据，而不是去修改原数据？ 因为真实的业务这里的模拟数据模拟不出来的，所以我觉得可以更改这个功能或许很鸡肋。大部分时间 我只是需要用不同的请求方式 get ,post,put等获取数据，有办法能做到 只获取数据么》？

**Comment by zq99299** [comment]
我已经弄好了

https://github.com/zq99299/rest-api-mock-server

这里

**Comment by mcherb** [comment]
I get the same issue here, i think the readOnly argument could be changed to do what you (I, they) want, instead of returning 403 error.

To fixe this, i had to add the following lines to my .js (as suggested by many other users)

```javascript
server.use(function (req, res, next) {
  if (req.method !== 'GET') {
    // Converts POST to GET and move payload to query params
    // This way it will make JSON Server that it's GET request
    req.method = 'GET';
    req.query = {}
  }
  // Continue to JSON Server router
  next();
});
```

**Comment by przemyslawjanpietrzak** [comment]
or you can add --read-only flag to start command

**Comment by PLQin** [comment]
```
// here
server.use((req, res, next) => {
  if (req.method === 'POST') {
    req.method = 'GET'
  }
  next()
})

server.use(middlewares)
server.use(jsonServer.rewriter(routes))
server.use(router)
```
