### ISSUE TITLE
POST not saving all data

### ISSUE THREAD

**Issue by BrianKrohn** [typicode/json-server#711]
When I POST using the simple setup described on the project page, the post creates a new id, but does not add the title and author I specify in the JSON body.

I do a POST to:  http://localhost:3000/posts
Body is: { "title": "hello world", "author": "typicode" }
Result is HTTP 201, with body: { "id": 2 }
db.json shows id 2, but that's it

What am I missing?

**Comment by Nilegfx** [comment]
make sure you set `content-type` header to `application/json`

**Comment by BrianKrohn** [comment]
It is set to application/json. The server responds 201, creates the post
record, and gives it the next available id. It just fails to create the
title and author field.

**Comment by BrianKrohn** [comment]
Got it.  You're right, the content-type was not being set correctly.  Thank you for the quick response.

**Comment by msninela** [comment]
@BrianKrohn, how did you add the Content-Type?  I have added it on my test, but I still seem to be only able to post IDs. I'm not too sure if I need to associate it with the POST test?

Please see issue 821 > https://github.com/typicode/json-server/issues/821

**Comment by msninela** [comment]
Don't worry guys, I had incorrectly added the HTTP Header Manager. Thanks 👍 :)

**Comment by golestanirad** [comment]
i had the same problem, found the solution here https://www.youtube.com/watch?v=FyZBTbv7UM0

**Comment by vsaiprakash** [comment]
When I am using this way from postman, it is working but when I try with XMLHttpRequest title & author are not getting created only id is created. Anything else i am missing to add in headers.

`request.setRequestHeader("Content-Type", "application/json");`
`var postBody = '{ "title": "hello world", "author": "typicode" }';`

Anything else I need to do when using XMLHttpRequest

**Comment by ms181** [comment]
How to add content type for json-server
