### ISSUE TITLE
events.js:182  throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by ArasGH** [typicode/json-server#731]
Keep getting the same/similar error on my steam level up bot script, if anyone knows the fix or has a similar problem pls help!

![screenshot_2](https://user-images.githubusercontent.com/33665658/36629247-b3d285ac-1953-11e8-8fe9-5ec6bf6345db.jpg)

**Comment by typicode** [comment]
Hi @ArasGH, not really sure how it relates to JSON Server

**Comment by ansarker** [comment]
```
events.js:183
      throw er; // Unhandled 'error' event
      ^

TypeError: res.json is not a function
at /home/void/Documents/github/luvmusic_home/controllers/songs.server.controller.js:221:11
    at /home/void/Documents/github/luvmusic_home/node_modules/mongoose/lib/model.js:3435:16
    at /home/void/Documents/github/luvmusic_home/node_modules/mongoose/lib/services/model/applyHooks.js:146:20
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
I am also getting this problem. What could be the solution of this?

**Comment by dkhandal** [comment]
killall node
execute this command first then start your server again.
