### ISSUE TITLE
PATCHing with a child array

### ISSUE THREAD

**Issue by sigmazen** [typicode/json-server#736]
Hi
Question about PATCHing with a child array.  My data is shown below.

If I run a simple `PATCH http://localhost:3000/users/2 { "name": "Jim" }` everything works as expected and Sam changes to Jim.

Now if my PATCH value is thus:
    { "address_list": [ { "address_type": "Home", "address": "99 West Street" } ] }
during the PATCH I want to update the `address` and add the `updated_date`

So I presume I need to intercept the PATCH and add a new element before the next().

In the following code, the new "test":"Test" is appended at the end but when the update occurs to the Home address it wipes all the address_list values out and replaces the entire array with the incoming address rather than updating only what is specified.

    server.use(jsonServer.bodyParser)
    server.use((req, res, next) => {
      if (req.method === 'PATCH') {
        req.body.test = "Test"
        req.body.address_list[0].updated_date = moment().format()
      }
      next()
    })

If I code it manually it works okay:

    db.get('users')
      .find({id: 2})
      .get('address_list')
      .filter((address) => {return address.address_type === 'Home'})
      .get('[0]')
      .assign({ address: reqBody.address_list[0].address })
      .assign({ updated_date: moment().format() })
      .write()

Do I essentially need to write my own PATCH routine to accomplish this?
Thanks in advance
Cheers

    {
      "users": [
        {
          "id": 1,
          "name": "Joe",
          "address_list": [
            {
              "address_type": "Home",
              "address": "7 High Street",
              "created_date": "2018-01-08",
              "updated_date": ""
            },
            {
              "address_type": "Business",
              "address": "9 Middle Street",
              "created_date": "2018-01-09",
              "updated_date": ""
            }
          ]
        },
        {
          "id": 2,
          "name": "Sam",
          "address_list": [
            {
              "address_type": "Home",
              "address": "99 Portland Drive",
              "created_date": "2018-01-08",
              "updated_date": ""
            },
            {
              "address_type": "Business",
              "address": "99 Elm Road",
              "created_date": "2018-01-09",
              "updated_date": ""
            }
          ]
        }
      ]
    }

**Comment by sigmazen** [comment]
I ended up pulling the complete, original record from the db, updating the appropriate key:value and then setting the `req.body` to the complete, updated record before letting `next()` to do its stuff.

**Comment by sambokai** [comment]
> I ended up pulling the complete, original record from the db

Can you share how you did that? Thanks!
