### ISSUE TITLE
Get req.body from POST request with application/ld+json

### ISSUE THREAD

**Issue by maximelafarie** [typicode/json-server#741]
I would like to mock some endpoints of an API using `application/ld+json`.

GET requests are working well, but when I would like to retrieve the request body with `req.body`, it appears to be empty (`{}`).

Did anybody already faced this issue? Is there any workaround to make it work with `application/ld+json`?

For information, I'm already using `jsonServer.bodyParser`.

Here's the endpoint I'm faking:
```
server.post('/companies', (req, res) => {
  if (isBearerOk(req.headers)) {
    console.log(req.body); // <-- it's empty!!
    res.status(201).json(companies.post.companies(req.body));
  } else {
    res.status(401).json({'error': ['Wrong Bearer token.']});
  }
});
```

**Comment by srounce** [comment]
Use Express' `body-parser` module and set the [`type`](https://github.com/expressjs/body-parser#type) option to your chosen mime-type.

**Comment by maximelafarie** [comment]
It does the job @srounce, thank you! 👌

**Comment by Nagibaba** [comment]
use `req.query` instead of `req.body`
