### ISSUE TITLE
wrong http status codes

### ISSUE THREAD

**Issue by IagoLast** [typicode/json-server#75]
such as returning "200 OK" instead "201 CREATED" after creating a new resource. (POST /resources)

**Comment by typicode** [comment]
Good point :+1: 
It's fixed for POST.

**Comment by IagoLast** [comment]
Great, maybe 204 when deleting a resource should be a good change too. (I prefer 204, but some people uses 200)

Check out this
http://www.restpatterns.org/HTTP_Status_Codes
http://www.restapitutorial.com/httpstatuscodes.html

in order to perform all responses in a standardized way,

**Comment by typicode** [comment]
Yes, not really sure about the DELETE.

At some point, it was returning 204. But maybe to make it easier on clients and to always return JSON data, I've changed it to an empty object `{}` so I was forced to change it to 200.

Maybe it would be better to go back to a 204.
Overall, I try to keep it a general tool that is compatible with most of the libraries.

If you spot other statuses that could get improvement feel free to add to this thread.
And thanks for the detailed status list, I'll check if some things can be changed next week :)
