### ISSUE TITLE
createId seems not in use

### ISSUE THREAD

**Issue by zzz6519003** [typicode/json-server#77]
:beers:

**Comment by zzz6519003** [comment]
maybe i can add test for it XD

**Comment by typicode** [comment]
:beers: 

Except if I'm missing something, it's tested here https://github.com/typicode/json-server/blob/master/test/index.js#L214

And used here https://github.com/typicode/json-server/blob/master/src/router.js#L10

**Comment by zzz6519003** [comment]
thx buddy!
actually, i wonder what `low.mixin({createId: utils.createId})` does.

:beer:

**Comment by typicode** [comment]
I've added some comments to make it clearer.

Basically, it overrides underscore-db's createId method with json-server's createId which has incremental id support in addition to uuid.

**Comment by zzz6519003** [comment]
cool man! just push it!
