### ISSUE TITLE
static server attempting to server JS as JSON

### ISSUE THREAD

**Issue by dredzone** [typicode/json-server#78]
would nice to add namespace for JSON API such that static server can serve resources and don't conflict with REST services.

**Comment by typicode** [comment]
Sure, do you have a scenario that conflicts?
It will help to add the feature.

**Comment by dredzone** [comment]
Example, index.html attempting to server /static/main.js. Workaround is to wrap json-server with your own and use app.use(namespace, jsonRouter(db))

**Comment by typicode** [comment]
Closing this issue since it's now possible to use the `--router` option to add a namespace/prefix.
