### ISSUE TITLE
Problem to use it (CORS)

### ISSUE THREAD

**Issue by hjJunior** [typicode/json-server#783]
I'm realy confused about CORS, so, I'm developing front-end with vuejs in localhost:8080 and json-server is runing in another port (9000)

When I do request with axios and add some header I got this:
![image](https://user-images.githubusercontent.com/10780132/40434655-2c5e6542-5e85-11e8-87ab-0eac35c4a706.png)

So I also created a middleware

    server.use((req, res, next) => {
      res.header('Access-Control-Allow-Origin', '*');
      res.header('Access-Control-Allow-Headers', 'authorization');
      res.header('Access-Control-Request-Headers', 'authorization');
      res.header('Access-Control-Allow-Methods', 'GET');
      res.header('Access-Control-Request-Methods', 'GET');
      if (req.path == '/api/auth/login') {
        next();
      } else {
        if (isAuthorized(req)) { // add your authorization logic here
          next() // continue to JSON Server router
        } else {
          res.sendStatus(401)
        }
      }
    })

I have added this lines trying to allow the request 

      res.header('Access-Control-Allow-Origin', '*');
      res.header('Access-Control-Allow-Headers', 'authorization');
      res.header('Access-Control-Request-Headers', 'authorization');
      res.header('Access-Control-Allow-Methods', 'GET');
      res.header('Access-Control-Request-Methods', 'GET');

and just simple function to compare and authorize

    const isAuthorized = (req) => {
      // console.log(req.headers)
      return (req.headers.authorization == 'Bearer: ' + token);
    }

can you help me please? I don't know if I need to add 'Access-Control-Allow-Origin' in json-server response or in axios, one more detail, is I'm using with default options `const server = jsonServer.create()`

**Comment by esparkman** [comment]
@hjJunior I know you closed this. Did you find a solution? I'm running into this as well.

**Comment by moepkid** [comment]
> 
> 
> @hjJunior I know you closed this. Did you find a solution? I'm running into this as well.

did you find anything? We found out that we have same issue (and with a tiomcat server).

**Comment by MarleneHE** [comment]
@hjJunior : hello, I'm running into the same problem, did you find a solution ? Or any other workaround ? The point is, we need to access our app from the outside and not from localhost.

**Comment by aislanmaia** [comment]
I'm having the same problem

**Comment by hafdon** [comment]
I managed to get this to work

### i have this in index.js on my server
```js
const jsonServer = require('json-server');
const server = jsonServer.create();
const router = jsonServer.router('db.json');
const middlewares = jsonServer.defaults();
const cors = require('cors');

server.use(
    cors({
        origin: true,
        credentials: true,
        preflightContinue: false,
        methods: 'GET,HEAD,PUT,PATCH,POST,DELETE',
    })
);
server.options('*', cors());

server.use(middlewares);
server.use(router);
server.listen(3000, () => {
    console.log('JSON Server is running');
});
```

### and in my client (I'm using Vue and axios) `./src/api/axios.js'
```javascript
import axios from 'axios'

axios.defaults.withCredentials = true

const instance = axios.create({
    baseURL: 'http://10.0.1.7:3000',
    // withCredentials: true,
})
export default instance
```

### and then in Vue: `main.js` I have 
```javascript
// [...]
import axios from '@/api/axios'
import VueAxios from 'vue-axios'
// [...]
Vue.prototype.$axios = axios
Vue.use(VueAxios, axios)
// [...]
```

### and then in my vue component
```vue
                results = await this.$axios.request({
                    method: 'get',
                    url: this.axios.url + `/${id}`,
                })
```

**Comment by kambleaa007** [comment]
@hafdon hi but my 
`app.use(auth);` is not alone it has `const auth = require("json-server-auth");`

**Comment by Miladxsar23** [comment]
**Make the course settings according to the following example:**

```
// server.js
const jsonServer = require("json-server");
const server = jsonServer.create();
const router = jsonServer.router("db.json");
const middlewares = jsonServer.defaults();
const cors = require("cors");

server.use(middlewares);
server.use(router);
server.use(
  cors({
    origin: true,
    credentials: true,
    preflightContinue: false,
    methods: "GET,HEAD,PUT,PATCH,POST,DELETE",
  })
);
server.options("*", cors());
server.listen(3001, () => {
  console.log("JSON Server is running");
});
```

**Terminate the server through the terminal and then clear your browser cache and cookies and run the server again.**

**Comment by Dysco76** [comment]
I know this is closed but if it helps someone - I was able to resolve this on macOS without creating a dedicated server.js. By turning off AirPlay receiver. I was using json-server on port 5000 and it turned out the AirPlay receiver also listens on this port somehow causing the CORS errors.
