### ISSUE TITLE
Cannot listen on all ip addresses

### ISSUE THREAD

**Issue by henkosch** [typicode/json-server#796]
When you define host to be "0.0.0.0", it will change it to "localhost", which will make it listen only on localhost, so it won't be available from outside the host.

https://github.com/typicode/json-server/blob/af07d8b85699de9e2d45e528b6a3386cc2493687/src/cli/run.js#L19

Expected:
Setting host to "0.0.0.0", should listen on "0.0.0.0".
Setting host to "localhost", should listen on "localhost".

**Comment by typicode** [comment]
Hi @henkosch,

`const host = argv.host === '0.0.0.0' ? 'localhost' : argv.host ` is only used to "pretty print" `localhost` when `host` is `0.0.0.0`, it doesn't change the host.

In other words, when setting `--host 0.0.0.0`, it really listens to `0.0.0.0` even if it says `localhost` in the CLI output.

But that's true that it can it can be quite confusing and that was probably a bad choice. I've published a new version `v0.14.0` that should improve this.

By default, `json-server` will now listen to `localhost` and when passed `--host 0.0.0.0`, it will listen to `0.0.0.0` AND it will display `0.0.0.0` as well in the CLI output.

Thanks for the feedback.
