### ISSUE TITLE
Disabling Changes

### ISSUE THREAD

**Issue by isaacrg** [typicode/json-server#80]
Are there options for:

* Disabling the POST/PUT/PATCH/DEL requests?
* Disabling changes to the JSON file.

If these are not presently available, it would be greatly beneficial if they were added, as that way json-server would also be able to serve as a mechanism for delivering read-only JS databases with the ability to be sorted and searched.

**Comment by smartheart1** [comment]
sure need  help,  is this me?

**Comment by isaacrg** [comment]
@typicode?

**Comment by typicode** [comment]
It depends how much "read-only" you want to achieve.
But I would really be interested in knowing the use-case :)

To disable changes to JSON file, you can use a JS file:

```javascript
// db.js
module.exports = function () {
  return { posts: [ ... ] }
})
```

```bash
json-server db.js # it will be an in-memory database and nothing will be written to disk
```

If you want to disable/modify specific routes, it's better to use json-server as a module:

```javascript
var jsonServer = require('json-server')

var server = jsonServer.create()

// Filter by req.method
server.all('*', function (req, res, next) {
  if (req.method === 'GET') {
    next() // Continue
  } else {
    res.sendStatus(403) // Forbidden
  }
})

server.use(jsonServer.defaults)

// You could also use an object here instead of a file
server.use(jsonServer.router('db.json')) 

server.listen(3000)
```

I've not tested this code, but it should work. If it doesn't let me know.

You can have a look as well at:
https://github.com/typicode/jsonplaceholder/blob/master/index.js

It restores database on each requests. So it's kind of read-only too.

Hope this will help :)

**Comment by isaacrg** [comment]
Thanks! Should I make a pull request to add these as options, so that the user can choose for these options to be enabled?

**Comment by typicode** [comment]
No thanks. For the moment, I prefer the CLI to stay simple and let people customize what they want using the project as a module.
Also, I think it would be hard to cover all the particular cases using CLI options.
But, if it happens to be a common case to restrict HTTP verbs, I'll add it to the CLI.

BTW, why did you need to only have GET?

**Comment by isaacrg** [comment]
A potential use case I have concerning transforming very big dataset into an API as q

**Comment by hadynz** [comment]
> To disable changes to JSON file, you can use a JS file ...
> json-server db.js # it will be an **in-memory database** and nothing will be written to disk

You don't know how happy I was to learn about this little nugget of a tip - using `js` files instead of `json` for an in-memory solution. Thanks for the productivity boost you just gave me. I'll try and make a PR to add this to the project's Readme.

**Comment by hameddhib** [comment]
how i can use file.js and apply modification into db.json ??
actually all modification are in memory olny

**Comment by CMCDragonkai** [comment]
Is there a way to disable changes to the object itself? So that way for a given route, it will always return the same data no matter what I post or put into it? I'm using the JS way. But I don't want to just disable POST/PUT... etc.

**Comment by sebmahe** [comment]
If you came like me from a Google Search (aka "json-server read only"), please note that an option have been introduced to support read-only mode and disable POST/PUT/PATCH/DEL requests :

```
json-server --read-only <source>
```

Hope it helps.
