### ISSUE TITLE
json-server to 0.14.0 & react-redux": "5.0.7" Problem Connection

### ISSUE THREAD

**Issue by lvdesign** [typicode/json-server#808]
Hello,
Since I upgrade json-server to 0.14.0, the connection is failling (react-redux": "5.0.7")

Some advice ?
Thanks

Cordially,
osx 10.13.4, yarn : 1.7.0, npm : 6.1.0, node : v8.11.1
"jest-expo": "~27.0.0",
"react-native-scripts": "1.14.0",
"react-test-renderer": "16.3.1"

**Comment by lvdesign** [comment]
OK, I resolve the problem

I downgrade the json-server to @0.11.2 
Perhaps a better soluce but now it's works… ;-)

and that match so becareful with your json-server version  and  your React Native app !

**Comment by typicode** [comment]
Hi @lvdesign,

Thanks for the report.

Not sure if it's related but got some errors after upgrading, I uninstalled json-server and reinstalled it, and I'm not having errors anymore with `0.14`.

If you still some stacktrace, I'd be interested :+1:

**Comment by lvdesign** [comment]
Hello,

I wanted to add that I have this same application in React. It worked perfectly with 0.14.

Thanks for the interest
Have a good day


laurent vignaux
laurent.vignaux@wanadoo.fr
