### ISSUE TITLE
Error with json-server and docker with version 0.14

### ISSUE THREAD

**Issue by dotmobo** [typicode/json-server#811]
Hi,

I use json-server@0.12.2 in a Dockerfile, and it works perfectly with docker !
 
But with json-server@0.14, i have the following error when i try to request a route : 

```
curl -XGET http://localhost:8080/fake-api/v1/towns                                                                                                           
curl: (56) Recv failure: Connection reset by peer
```

Here the docker image : 

```
FROM node:9-stretch

RUN npm install -g json-server@0.14

COPY api /data
WORKDIR /data
VOLUME /data

EXPOSE 8080
ENTRYPOINT ["json-server","--port","8080","--watch","/data/db.json","--routes","/data/routes.json"]
```

Runned by : 

```
docker build -t fake-server-local -f Dockerfile .
docker run -p 8080:8080 fake-server-local

  \{^_^}/ hi!

  Loading /data/db.json
  Loading /data/routes.json
  Done

  Resources
  http://localhost:8080/countries
  http://localhost:8080/towns

  Other routes
  /v1/* -> /$1
  /fake-api/v1/* -> /$1

  Home
  http://localhost:8080

  Type s + enter at any time to create a snapshot of the database
  Watching...

```
With a curl request INSIDE the container with "docker exec", the api works ...
And with version 0.12.2, all works.

Thanks !

**Comment by grenzbotin** [comment]
Hey. 
Stumbled over the same issue and had a look into the Changelog (https://github.com/typicode/json-server/blob/master/CHANGELOG.md). 

The default host address the server was listening to was changed from of `0.0.0.0` to `localhost` .
With adding `--host 0.0.0.0` to your command the server should behave as usual.

**Comment by IvanBodnar** [comment]
Thank you @grenzbotin , it was driving me crazy.

**Comment by eitacode** [comment]
Finally an answer that works

**Comment by eugene-matvejev** [comment]
```
> json-server --watch db.json "--port" "8081" "--host" "0.0.0.0"


  \{^_^}/ hi!

  Loading db.json
  Done

  Resources
  http://0.0.0.0:8081/bills
  http://0.0.0.0:8081/categories

  Home
  http://0.0.0.0:8081

  Type s + enter at any time to create a snapshot of the database
  Watching...

```

Linux Docker.

if i go in browser localhost 8081 doesn't work =/ ping inside  container work
