### ISSUE TITLE
Relations as list of values in a property

### ISSUE THREAD

**Issue by davidmpaz** [typicode/json-server#844]
Assuming there is a relation **admin -> accounts** like:

```
{
    "id": 1,
    "firstName": "Test",
    "lastName": "User",
    "active": true,
    "accountIds": [1, 2, 3, 4, 5]
}
```

it is possible to load all those accounts when requesting admins for example? Something like `/admins/1/accounts`?

Is there a ways to have that or it is required to put the **admin id** in the account object anyways?

thanks in advance,
David

**Comment by GxDesign** [comment]
No, but you can use a module and access the json directly via a custom route. You would use lowDBs documentation to map through the array of IDs and grab each account that matches the iterated id and add it to your response.

**Comment by davidmpaz** [comment]
Thanks!

**Comment by lipengzhou** [comment]
111

**Comment by lipengzhou** [comment]
123

**Comment by lipengzhou** [comment]
555
