### ISSUE TITLE
Live Reload

### ISSUE THREAD

**Issue by fosron** [typicode/json-server#85]
Hey,

so i'm prototyping with help of json-server, and i've noticed i need to do alot of changing of data by hand. That leads to alot of Ctrl-C and reapplying same command in the Terminal. Is it possible to use live-reload or something in line of that so that the data would be reloaded when file is changed? Or atleast a shortcut in terminal to see and reload the file if there are changes (ex. s for snapshot, r for reload) ?

Thanks!

**Comment by typicode** [comment]
Hi @fosron 

I'll see what can be done.
As a temporary work-around, I think something like `nodemon -e json server.js` would work 

```javascript
// server.js
var jsonServer = require('json-server')

var server = jsonServer.create()
var router = jsonServer.router('db.json')

server.use(jsonServer.defaults)
server.use(router)

server.listen(3000)
```

**Comment by typicode** [comment]
Just published `v0.7.7` with `--watch` option :)
I've tested it on Linux.

**Comment by fosron** [comment]
Awesome, it works, thanks! :)

**Comment by typicode** [comment]
You're welcome :)

**Comment by pkellner** [comment]
Hi @fosron and @typicode .  I'm a little confused on this issue and why it's closed (and, sorry for the necro post so I understand if it's fades away).  The original question is about running a custom script, and the solution proposed by @typicode is for running json-server directly from a command.  `nodemon -e json server.js` did work for me, but would be nice if there was some way to address this in the app (if that's even possible)
