### ISSUE TITLE
Queries don't return results

### ISSUE THREAD

**Issue by melnik13** [typicode/json-server#86]
Hello!

I have a silmple database with one record:

    {
      "test": [
        {
          "id": 1,
          "phone": "0666666666",
          "selection": 1
        }
      ]
    }

I can see it when I ask for `GET /text`, but when I ask for `GET /test?phone=0666666666`, I get an empty array:

    []

By the way, `GET /test?selection=1` works fine and returns the expected result.

Am I doing something wrong? Thanks!

**Comment by melnik13** [comment]
By the way, if I have phone equal to something containing letters (e.g. `X0666666666`), `GET /test?phone=X0666666666"` works fine.

**Comment by typicode** [comment]
I can see why. JSON Server tries to convert strings from query parameters.
This allows to use booleans and integers in JSON files:

```
//...
   "published": true // will be matched with ?published=true
```

But here, it considers that `'066666666'` is a number `66666666`.

The code that is responsible for that is here:
https://github.com/typicode/json-server/blob/master/src/utils.js#L10

A quick fix would be not to convert to number if it starts with 0.
But, I'll try to come up with something more reliable.

**Comment by typicode** [comment]
I've released `v0.7.7`.
Now if a query parameter starts with `0` it won't be converted to an integer but will remain a string.

**Comment by melnik13** [comment]
Great news, thank you!

On Thu, May 14, 2015 at 05:45:56PM -0700, typicode wrote:
> I've released `v0.7.7`.
> Now if a query parameter starts with `0` it won't be converted to an integer but will remain a string.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/typicode/json-server/issues/86#issuecomment-102210833

-- 
V.Melnik

**Comment by melnik13** [comment]
Great news, thank you!

**Comment by typicode** [comment]
You're welcome, thanks for letting me know about this issue :)
