### ISSUE TITLE
[Question] Implementation following system

### ISSUE THREAD

**Issue by propanto** [typicode/json-server#892]
These are my data.
```json
{
  "users": [
    { "id": 1, "username": "Alex" },
    { "id": 2, "username": "John" },
    { "id": 3, "username": "Maria" },
    { "id": 4, "username": "Jane" },
    { "id": 5, "username": "Mike" },
    ect...
  ],
  
  "followers": [
    { "id": 1, "userId": 1, "followerId": 4},
    { "id": 2, "userId": 2, "followerId": 5},
    { "id": 3, "userId": 3, "followerId": 1},
    { "id": 4, "userId": 4, "followerId": 2},
    { "id": 5, "userId": 5, "followerId": 3},
    ect...
  ]
}
```
How to get the following users and followers?

**Comment by northkode** [comment]
Read the documentation, it clearly describes how you could go about doing this with _expand and _extend
https://github.com/typicode/json-server#relationships

**Comment by propanto** [comment]
@northkode I read the docs and I test it. I can get the followers but my problem is how to get following users?

**Comment by northkode** [comment]
I really dont know what you mean?  If you read the docs you would see that if you have a route called `/followers` then you need to do what the docs say and do 
`/followers?_expand=user` and it uses the userId to map the users to the follower.
