### ISSUE TITLE
Is json5 format supported?

### ISSUE THREAD

**Issue by xeoshow** [typicode/json-server#900]
Hello, 

I am new to json-server, looks very good, just would like to know if it supports json5? We we could easily use the db.json as a full data model with comments explaining the data attributes ...

https://json5.org/

Thanks!

Best regards, Jason

**Comment by khullah** [comment]
interested in this too  : > )

**Comment by MNF** [comment]
Alternatively it could be [jsonc](https://github.com/microsoft/node-jsonc-parser#readme )    or some other options - see [Should we consolidate the human-readable JSON efforts? #190](https://github.com/json5/json5/issues/190)

**Comment by matthias-ccri** [comment]
I'd like this because then I can use trailing commas. Trailing commas are good for copying and pasting. No more annoying last-comma management.

**Comment by question44** [comment]
I would love to see that

**Comment by typicode** [comment]
Available in `v1-alpha`
