### ISSUE TITLE
Specific route in db json file

### ISSUE THREAD

**Issue by Bierrot** [typicode/json-server#91]
Hi,
I need to mock a real webservice in local, so I need custom route like "users/comments".

For that, I just created a json file with resource like this : 
```json
{  
"users/comments": [
    { "id": 1, "body": "some comment", "postId": 1 }
  ]
}
```

When I start json-server, it says that I can access to  "http://localhost:3000/users/comments" but when I try, I only have 
```json
{}
```
 as response, and it add the following automatically to my db json file.
```json
"users": []
```

I tried to escape the / between "users" and "comments", (users\/comments), but there is exactly the same issue.

**Comment by typicode** [comment]
Currently, you can't do this. To add specific routes, you need to use the project as a module and add a redirection:

```
var jsonServer = require('json-server')

var server = jsonServer.create()
var router = jsonServer.router('db.json')

server.use('/users/comments/:id', function (req, res) {
  res.redirect('/comments/' + req.params.id)
})

server.use(jsonServer.defaults)
server.use(router)

server.listen(3000)
```

You can use also [express-rewrite](https://github.com/joehewitt/express-rewrite) and [express-redirect](https://github.com/buschtoens/express-redirect)

BTW, you can also have multiple routers mounted on different URLs:

```javascript
server.use('/users', jsonServer.router('comments.json')) // { "comments": [ ... ] }
server.use('/posts', jsonServer.router('comments.json')) // { "posts": [ ... ] }
```

Do you have a lot of routes like `users/comments`?

**Comment by tyx** [comment]
This feature would be awesome !

**Comment by jthomas** [comment]
+1

**Comment by abbish** [comment]
+1

**Comment by typicode** [comment]
I've done some prototyping and it's not so simple to mix table names with routes.
Especially, it introduces some edge case.

For example:

```json
{
  "blog/comments": [{ "id": 1, "postId": 1 }],
  "blog/posts": [{ "id": 1 }]
}
```

`/blog/comments/1` would be easy to implement.
But for nested routes like `/blog/posts/1/comments`, it would be quite harder. Especially to extract a table name and a parent id.

@tyx, @jthomas, @abbish, if you have the time to, it would be helpful if you can provide some examples/explanations of what you need?

**Comment by jthomas** [comment]
I'm just looking to provide a relatively flat JSON response through JSON-Server to simulate the REST API for a third-party, which resides at a long URL path. 

I had a path like:
/api/root/resource_name/:id/subresources

with a simple JSON object response to be returned. I would prefer to use the installed binary version rather than having to write my own module.

**Comment by tyx** [comment]
Exactly like @jthomas 

I admit I finally switched to moco which do this job

**Comment by LewisJared** [comment]
PR #121 will allow you to specify a path prefix for the json-server binary using the -r option.  The 

Now if you want to serve: `/api/root/posts/:id/comments`

Your json file can look like:
```json
{
  "posts": [
    {
      "id": 1,
      "title": "json-server",
      "author": "typicode"
    }
  ],
  "comments": [
    {
      "id": 1,
      "body": "some comment",
      "postId": 1
    },
    {
      "id": 2,
      "body": "another comment",
      "postId": 1
    }
  ]
}
```

and run json-server with:
```bash
json-server -r /api/root -w db.json
```
`GET /api/root/posts/1/comments`
Will return
```json
[
  {
    "id": 1,
    "body": "some comment",
    "postId": 1
  },
  {
    "id": 2,
    "body": "another comment",
    "postId": 1
  }
]
```

**Comment by typicode** [comment]
Just added a new `--routes` option to the CLI.
It should cover the situations described in this issue :)

**Comment by Bierrot** [comment]
Awesome ! Perfectly work ;)
Thanks @typicode

**Comment by typicode** [comment]
I think it should be possible to make it work with route and route1/route2.
What are exactly route and route1/route2?

You can also try switching their declaration order in `routes.json`.
