### ISSUE TITLE
"Data must be an object"

### ISSUE THREAD

**Issue by gweinz** [typicode/json-server#920]
I keep getting this error: "Error: Data must be an object. Found object.See https://github.com/typicode/json-server for example."

I thought it may have been my formatting so I used your sample db.json to see but still I get this error. if there's a fix and you could help that would be greatly appreciated.

**Comment by beatakru** [comment]
Only json object can be "parsed" e.g.
{
"jsonarray":[{
}]
}

**Comment by duduindo** [comment]
@beatakru  Tks

**Comment by ranisaini0131** [comment]
@beatakru thanks
