### ISSUE TITLE
Property render does not exist on type Router

### ISSUE THREAD

**Issue by Rutvik17** [typicode/json-server#926]
Custom output example
To modify responses, overwrite router.render method:

```
const router = jsonServer.router(path.join(__dirname, '../db.json'));

// In this example, returned resources will be wrapped in a body property
router.render = (req, res) => {
  res.jsonp({
    body: res.locals.data
  })
}
```
Using router.render throws property render does not exist on type router

**Comment by b4dnewz** [comment]
The error occurs when you execute the node script or when you visit some route?
The code itself it's not failing.

**Comment by Rutvik17** [comment]
The error is shown in the IDE and also when I execute the script.

**Comment by tgillitzer** [comment]
@Rutvik17   What was your other solution?    I'm having the same problem.

@b4dnewz as described, router.render just doesn't exist, so we can't assign to it as the documentation states.

**Comment by Rutvik17** [comment]
> @Rutvik17 What was your other solution? I'm having the same problem.
> 
> @b4dnewz as described, router.render just doesn't exist, so we can't assign to it as the documentation states.

Sorry I actually don't remember what i did, i will need to find the solution.
