### ISSUE TITLE
Multiple _ne operators are ignored

### ISSUE THREAD

**Issue by uminder** [typicode/json-server#929]
Using _ne operator, I can exclude a specific value. When chaining two  _ne operators, they're both ignored.
> GET /posts?id_ne=1&id_ne=5

**Comment by stushurik** [comment]
@uminder I experience the same behavior

**Comment by b4dnewz** [comment]
I can confirm right now is not supported but it's a cool feature
and it could be also `GET /posts?id_ne=1,5` as csv array

**Comment by DuredhelFinceleb** [comment]
Same here and it's quite debilitating
It's a must have!

**Comment by uminder** [comment]
Thanks [b4dnewz](https://github.com/b4dnewz), I'll give it a try.
