### ISSUE TITLE
npm run script never execute after start json-server

### ISSUE THREAD

**Issue by balalaXD** [typicode/json-server#936]
The command `node index.js` after `json-server --delay 1000 --watch db.json` never execute.

```json
{
  "name": "hell",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "json-server --delay 1000 --watch db.json && node index.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
```

**Comment by thatsmeta** [comment]
It looks like you're trying to run two commands concurrently in an npm script. If that is the case, this link might help you: https://stackoverflow.com/questions/30950032/how-can-i-run-multiple-npm-scripts-in-parallel

**Comment by balalaXD** [comment]
thanks
