### ISSUE TITLE
Deep Filtering

### ISSUE THREAD

**Issue by ryancrosser** [typicode/json-server#96]
I am loving the simpleness of json-server, however, I have found the need to query data that is within an array or object.

Using the example below, the current implementation of :resource/?q= only returns results if the query is found in a string, and ignores arrays and objects. 
Meaning if you try to query *Noelia Becker* (name), it will work because the value is a string, however, trying to query *Sandrine Kilback* (alternateName) will not return the result because alternateName is an array.

Is there a plan to add deep querying functionality or did I just miss it? For a quick demo, I simply stringified the value before the indexOf check, however, this will return true if the the query is a property within the object. Obviously this is not the best solution, but it worked for my immediate need.

If this functionality is not already available and sounds like something that would add value to the library, I can try to find an elegant way to recursively search through the object (I actually started going down this path, before trying the JSON.stringify() option).

```
{
    "id": 1,
    "name": "Noelia Becker",
    "alternateName": [
        "Sandrine Kilback",
        "Marie Oberbrunner",
        "Phyllis Labadie"
    ],
    "locations": [{
        "street": "2896 Windler Course",
        "city": "South Florineville",
        "state": "Maryland",
        "zip": "60064-3365",
        "country": "Rwanda",
        "grid": {
            "latitude": "-58.2677",
            "longitude": "-62.2457"
        }
    },{
        "street": "6577 Burnice Row",
        "city": "Nicolefurt",
        "state": "Indiana",
        "zip": "54190",
        "country": "Saint Vincent and the Grenadines",
        "grid": {
            "latitude": "-44.6137",
            "longitude": "160.4332"
        }
    }]
}
```

**Comment by typicode** [comment]
Hi @ryancrosser 

Sounds good :+1:

Easiest thing I found so far is https://github.com/marklagendijk/lodash-deep (may be worth to switch from underscore to lodash then). And it could be used to add "deep" query parameters.
I don't think it would be possible to do this only using `lodash` though.

Maybe you have found some better solution?

**Comment by ryancrosser** [comment]
Sorry for the delay in responding. I will definitely work on a solution, although I probably will not be able to do anything until this weekend.

I took a quick look through the project to see what the side effects might be of switching to lodash. I see you just removed ```underscore-inflection```, would ```underscore-db``` work with lodash? The router mixes it in with ```lowdb```.

Just wanted to get your opinion on the underscore dependencies.

On a side note, I prefer lodash as it will correctly identify an object using ```_.isPlainObject()```, underscore's ```isObject()``` method returns true for an array or object.

**Comment by typicode** [comment]
No worries. Yes, it should work with lodash.
I have some free time right now, I can take care of it if you want?

Didn't know about this, good to know :)

**Comment by ryancrosser** [comment]
I was able to submit a pull request today. I had to keep `underscore`, seems that `lodash` is not exactly the same. The `getRemovable()` function was failing. If we actually need `lodash` functionality, that method will need to be refactored.

As of now, the only thing that would require lodash is if you wanted to provide nested attribute functionality. So instead of `:resources?name=something`, it could be `"resources?name.first=firstName`. This would use lodash's `_.get` function (same as lodash-deep). Just some thoughts

**Comment by typicode** [comment]
Thanks for sharing thoughts.
I've just released `v0.7.10` with your feature and moved to `lodash` :)

**Comment by hatavan83** [comment]
@typicode 
Could you give me some guideline about deep filter 
I try ex as:
/posts?_embed=comments&comment.userId=1

**Comment by typicode** [comment]
Hi @hatavan83 

Hmm I'm not sure it's possible to do it this way.
But maybe you can try getting comments from user 1 and then associated posts:

/comments?userId=1&expand=post

**Comment by hatavan83** [comment]
@typicode
I already try and json server cannot deep filter :( I hope json server can support more param to filter like the operator "or" , check param value in  arrays embed object
