### ISSUE TITLE
Creating multiple resources at once?

### ISSUE THREAD

**Issue by codfish** [typicode/json-server#977]
Is it possible, via middleware or some other mechanism, to create multiple resources on a POST?

We're uploading a csv and we're going to storing the upload (and various metadata) separately from the individual rows.

**Comment by samuelcolburn** [comment]
I imagine you could do that pretty easily with a custom middleware,  The  `jsonServer.router()` exposes a `db` prop that allows you to interface directly with the underlying `lowdb` instance. From there you can use any of the `lowdb` methods to create your resources. [https://github.com/typicode/lowdb](https://github.com/typicode/lowdb)

Generally though I think its considered best-practice to avoid making one-off routes for an api.

You could probably do something like this:

**this code is just a rough example**

```javascript
const server = jsonServer.create()

// Create your router via jsonServer
// the router exposes a db prop 
const router = jsonServer.router('db.json)


const middlewares = jsonServer.defaults()

server.use(middlewares)

// add the bodyParser to handle POST requests
server.use(jsonServer.bodyParser)

// Add a custom route to handle your mutli-insert request
server.post('/my-csv-route', (req, res, next) => {
  const db = router.db

  // do your db stuff
  const updates = db.get('posts')
    .insert({ title: 'low!' })
    .write()

  // send the response
  res.status(201)
  res.locals.data = updates
  next()
})

server.use(router)
server.listen(3000, () => {
  console.log('JSON Server is running')
})
```

**Comment by codfish** [comment]
Awesome, much appreciated. thank you!
